### ISSUE TITLE
Creatting unassigned tasks returns 500 Internal server error

### ISSUE THREAD

**Issue by kazufumi-nishida** [taigaio/taiga-back#1034]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

When we create unassigned task in taskboard view, API returns 500 internal server error.
However, there is the task after browser page refresh.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. (taiga version up from 2.x to 3.x?)
1. Configure webhook
1. Create Project
1. Create Sprint
1. Go Taskboard
1. Create Unassigned task

**What is the expected behavior?**

API return 20X.

**Is it happening in taiga.io or in your own instance?**

own instance

**What browser/version are you using?**

Chrome  61.0.3163.100（Official Build） （64 bit）

**Are there any console errors *(Ctrl + F12)* in red?**

yes, 500 Internal server error

**Additional Information**

taiga-back error log in /home/ubuntu/logs/gunicorn.stderr.log

```
ERROR:2017-10-13 10:31:53,900: Internal Server Error: /api/v1/tasks/14801
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/taiga-back/taiga/base/api/viewsets.py", line 106, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ubuntu/taiga-back/taiga/base/api/views.py", line 461, in dispatch
    response = self.handle_exception(exc)
  File "/home/ubuntu/taiga-back/taiga/base/api/views.py", line 458, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/ubuntu/taiga-back/taiga/base/api/mixins.py", line 207, in partial_update
    return self.update(request, *args, **kwargs)
  File "/home/ubuntu/taiga-back/taiga/projects/tasks/api.py", line 203, in update
    return super().update(request, *args, **kwargs)
  File "/usr/lib/python3.5/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/transaction.py", line 267, in __exit__
    connection.set_autocommit(True)
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/backends/base/base.py", line 396, in set_autocommit
    self.run_and_clear_commit_hooks()
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/backends/base/base.py", line 624, in run_and_clear_commit_hooks
    func()
  File "/home/ubuntu/taiga-back/taiga/webhooks/signal_handlers.py", line 75, in <lambda>
    connection.on_commit(lambda: _execute_task(task, webhooks_args))
  File "/home/ubuntu/taiga-back/taiga/webhooks/signal_handlers.py", line 84, in _execute_task
    task(*webhook_args)
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.5/site-packages/celery/local.py", line 191, in __call__
    return self._get_current_object()(*a, **kw)
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.5/site-packages/celery/app/task.py", line 379, in __call__
    return self.run(*args, **kwargs)
  File "/home/ubuntu/taiga-back/taiga/webhooks/tasks.py", line 142, in change_webhook
    data['data'] = _serialize(obj)
  File "/home/ubuntu/taiga-back/taiga/webhooks/tasks.py", line 47, in _serialize
    return TaskSerializer(obj).data
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.5/site-packages/serpy/serializer.py", line 134, in data
    self._data = self.to_value(self.instance)
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.5/site-packages/serpy/serializer.py", line 124, in to_value
    return self._serialize(instance, fields)
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.5/site-packages/serpy/serializer.py", line 114, in _serialize
    result = to_value(result)
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.5/site-packages/serpy/serializer.py", line 124, in to_value
    return self._serialize(instance, fields)
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.5/site-packages/serpy/serializer.py", line 107, in _serialize
    result = getter(self, instance)
  File "/home/ubuntu/taiga-back/taiga/webhooks/serializers.py", line 165, in get_custom_attributes_values
    values = obj.custom_attributes_values.attributes_values
AttributeError: 'NoneType' object has no attribute 'custom_attributes_values'
```

**Comment by jespino** [comment]
Yes, looks like a problem with celery. Have you changed the task_serializer from "pickle" to other serializer?

**Comment by kazufumi-nishida** [comment]
Thanks response.

> Have you changed the task_serializer from "pickle" to other serializer?

No.

P.S.

We created another taiga environment and do same procedure but we cannot reproduce this error.

**Comment by jespino** [comment]
Looks like an environment problem then, so I close the bug.
