### ISSUE TITLE
Error deleting a project from taiga

### ISSUE THREAD

**Issue by vikrantrathore** [taigaio/taiga-back#1058]
What is the current behavior?

After adding the project wanted to delete it, the front-end gives an error. 

If the current behavior is a bug, please provide the steps to reproduce?

1. Add a new project.
2. Go to project details.
3. Click on gear icon (admin)
4. Select Delete this project
5. Confirm in next screen

What is the expected behavior?
Project should be deleted with success message.

Is it happening in taiga.io or in your own instance?
Yes

What browser/version are you using?
Firefox 57.0.4

*Are there any console errors *(Ctrl + F12)* in red?
Yes

Below is the log:

ERROR:2018-01-12 03:07:30,750: Internal Server Error: /api/v1/projects/15
Traceback (most recent call last):
  File "/home/rokapm/.virtualenvs/taiga/lib/python3.5/site-packages/kombu/utils/functional.py", line 36, in __call__
    return self.__value__
AttributeError: 'ChannelPromise' object has no attribute '__value__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rokapm/.virtualenvs/taiga/lib/python3.5/site-packages/kombu/connection.py", line 494, in _ensured
    return fun(*args, **kwargs)
  File "/home/rokapm/.virtualenvs/taiga/lib/python3.5/site-packages/kombu/messaging.py", line 187, in _publish
    channel = self.channel
  File "/home/rokapm/.virtualenvs/taiga/lib/python3.5/site-packages/kombu/messaging.py", line 209, in _get_channel
    channel = self._channel = channel()
  File "/home/rokapm/.virtualenvs/taiga/lib/python3.5/site-packages/kombu/utils/functional.py", line 38, in __call__
    value = self.__value__ = self.__contract__()
  File "/home/rokapm/.virtualenvs/taiga/lib/python3.5/site-packages/kombu/messaging.py", line 224, in <lambda>
    channel = ChannelPromise(lambda: connection.default_channel)
  File "/home/rokapm/.virtualenvs/taiga/lib/python3.5/site-packages/kombu/connection.py", line 819, in default_channel
    self.connection
  File "/home/rokapm/.virtualenvs/taiga/lib/python3.5/site-packages/kombu/connection.py", line 802, in connection
    self._connection = self._establish_connection()
  File "/home/rokapm/.virtualenvs/taiga/lib/python3.5/site-packages/kombu/connection.py", line 757, in _establish_connection
    conn = self.transport.establish_connection()
  File "/home/rokapm/.virtualenvs/taiga/lib/python3.5/site-packages/kombu/transport/pyamqp.py", line 130, in establish_connection
    conn.connect()
  File "/home/rokapm/.virtualenvs/taiga/lib/python3.5/site-packages/amqp/connection.py", line 294, in connect
    self.transport.connect()
  File "/home/rokapm/.virtualenvs/taiga/lib/python3.5/site-packages/amqp/transport.py", line 120, in connect
    self._connect(self.host, self.port, self.connect_timeout)
  File "/home/rokapm/.virtualenvs/taiga/lib/python3.5/site-packages/amqp/transport.py", line 161, in _connect
    self.sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rokapm/.virtualenvs/taiga/lib/python3.5/site-packages/kombu/connection.py", line 414, in _reraise_as_library_errors
    yield
  File "/home/rokapm/.virtualenvs/taiga/lib/python3.5/site-packages/kombu/connection.py", line 515, in _ensured
    reraise_as_library_errors=False,
  File "/home/rokapm/.virtualenvs/taiga/lib/python3.5/site-packages/kombu/connection.py", line 405, in ensure_connection
    callback)
  File "/home/rokapm/.virtualenvs/taiga/lib/python3.5/site-packages/kombu/utils/functional.py", line 333, in retry_over_time
    return fun(*args, **kwargs)
  File "/home/rokapm/.virtualenvs/taiga/lib/python3.5/site-packages/kombu/connection.py", line 261, in connect
    return self.connection
  File "/home/rokapm/.virtualenvs/taiga/lib/python3.5/site-packages/kombu/connection.py", line 802, in connection
    self._connection = self._establish_connection()
  File "/home/rokapm/.virtualenvs/taiga/lib/python3.5/site-packages/kombu/connection.py", line 757, in _establish_connection
    conn = self.transport.establish_connection()
  File "/home/rokapm/.virtualenvs/taiga/lib/python3.5/site-packages/kombu/transport/pyamqp.py", line 130, in establish_connection
    conn.connect()
  File "/home/rokapm/.virtualenvs/taiga/lib/python3.5/site-packages/amqp/connection.py", line 294, in connect
    self.transport.connect()
  File "/home/rokapm/.virtualenvs/taiga/lib/python3.5/site-packages/amqp/transport.py", line 120, in connect
    self._connect(self.host, self.port, self.connect_timeout)
  File "/home/rokapm/.virtualenvs/taiga/lib/python3.5/site-packages/amqp/transport.py", line 161, in _connect
    self.sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rokapm/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/home/rokapm/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/rokapm/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rokapm/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rokapm/projects/taiga-back/taiga/base/api/viewsets.py", line 106, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/rokapm/.virtualenvs/taiga/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rokapm/projects/taiga-back/taiga/base/api/views.py", line 461, in dispatch
    response = self.handle_exception(exc)
  File "/home/rokapm/projects/taiga-back/taiga/base/api/views.py", line 458, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/rokapm/projects/taiga-back/taiga/projects/api.py", line 481, in destroy
    self.pre_delete(obj)
  File "/home/rokapm/projects/taiga-back/taiga/projects/history/mixins.py", line 83, in pre_delete
    self.persist_history_snapshot(obj, delete=True)
  File "/home/rokapm/projects/taiga-back/taiga/projects/history/mixins.py", line 75, in persist_history_snapshot
    self.__last_history = take_snapshot(sobj, comment=comment, user=user, delete=delete)
  File "/usr/lib/python3.5/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/home/rokapm/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/transaction.py", line 267, in __exit__
    connection.set_autocommit(True)
  File "/home/rokapm/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/backends/base/base.py", line 396, in set_autocommit
    self.run_and_clear_commit_hooks()
  File "/home/rokapm/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/backends/base/base.py", line 624, in run_and_clear_commit_hooks
    func()
  File "/home/rokapm/projects/taiga-back/taiga/timeline/signals.py", line 47, in <lambda>
    refresh_totals=refresh_totals))
  File "/home/rokapm/.virtualenvs/taiga/lib/python3.5/site-packages/celery/app/task.py", line 412, in delay
    return self.apply_async(args, kwargs)
  File "/home/rokapm/.virtualenvs/taiga/lib/python3.5/site-packages/celery/app/task.py", line 535, in apply_async
    **options
  File "/home/rokapm/.virtualenvs/taiga/lib/python3.5/site-packages/celery/app/base.py", line 737, in send_task
    amqp.send_task_message(P, name, message, **options)
  File "/home/rokapm/.virtualenvs/taiga/lib/python3.5/site-packages/celery/app/amqp.py", line 558, in send_task_message
    **properties
  File "/home/rokapm/.virtualenvs/taiga/lib/python3.5/site-packages/kombu/messaging.py", line 181, in publish
    exchange_name, declare,
  File "/home/rokapm/.virtualenvs/taiga/lib/python3.5/site-packages/kombu/connection.py", line 527, in _ensured
    errback and errback(exc, 0)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/rokapm/.virtualenvs/taiga/lib/python3.5/site-packages/kombu/connection.py", line 419, in _reraise_as_library_errors
    sys.exc_info()[2])
  File "/home/rokapm/.virtualenvs/taiga/lib/python3.5/site-packages/vine/five.py", line 175, in reraise
    raise value.with_traceback(tb)
  File "/home/rokapm/.virtualenvs/taiga/lib/python3.5/site-packages/kombu/connection.py", line 414, in _reraise_as_library_errors
    yield
  File "/home/rokapm/.virtualenvs/taiga/lib/python3.5/site-packages/kombu/connection.py", line 515, in _ensured
    reraise_as_library_errors=False,
  File "/home/rokapm/.virtualenvs/taiga/lib/python3.5/site-packages/kombu/connection.py", line 405, in ensure_connection
    callback)
  File "/home/rokapm/.virtualenvs/taiga/lib/python3.5/site-packages/kombu/utils/functional.py", line 333, in retry_over_time
    return fun(*args, **kwargs)
  File "/home/rokapm/.virtualenvs/taiga/lib/python3.5/site-packages/kombu/connection.py", line 261, in connect
    return self.connection
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/kombu/connection.py", line 802, in connection
    self._connection = self._establish_connection()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/kombu/connection.py", line 757, in _establish_connection
    conn = self.transport.establish_connection()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/kombu/transport/pyamqp.py", line 130, in establish_connection
    conn.connect()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/amqp/connection.py", line 294, in connect
    self.transport.connect()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/amqp/transport.py", line 120, in connect
    self._connect(self.host, self.port, self.connect_timeout)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/amqp/transport.py", line 161, in _connect
    self.sock.connect(sa)
kombu.exceptions.OperationalError: [Errno 111] Connection refused

**Comment by vikrantrathore** [comment]
Sorry for the time taken, it was just that rabbitmq stopped itself and needed to just start it.
