### ISSUE TITLE
User Signup problem!!!

### ISSUE THREAD

**Issue by ThangarajRavi** [taigaio/taiga-back#1075]
After i installed the centos bash scripts . every thing is working fine except user signup.
![taiga](https://user-images.githubusercontent.com/36756285/36581646-f93b48e0-183b-11e8-82b5-75ca7c743115.PNG)

**Comment by ThangarajRavi** [comment]
After i did some logs it shows.

ERROR:2018-02-22 14:27:19,498: Internal Server Error: /api/v1/projects
Traceback (most recent call last):
  File "/opt/python3.5/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: relation "projects_project" does not exist
LINE 1: SELECT COUNT(*) AS "__count" FROM "projects_project" WHERE "...
                                          ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/python3.5/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/opt/python3.5/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/opt/python3.5/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/python3.5/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/viewsets.py", line 106, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/python3.5/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/views.py", line 460, in dispatch
    response = self.handle_exception(exc)
  File "/home/taiga/taiga-back/taiga/base/api/views.py", line 458, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/mixins.py", line 137, in list
    page = self.paginate_queryset(self.object_list)
  File "/home/taiga/taiga-back/taiga/base/api/pagination.py", line 223, in paginate_queryset
    page_number = paginator.validate_number(page)
  File "/opt/python3.5/lib/python3.5/site-packages/django/core/paginator.py", line 46, in validate_number
    if number > self.num_pages:
  File "/opt/python3.5/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/python3.5/lib/python3.5/site-packages/django/core/paginator.py", line 91, in num_pages
    if self.count == 0 and not self.allow_empty_first_page:
  File "/opt/python3.5/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/python3.5/lib/python3.5/site-packages/django/core/paginator.py", line 79, in count
    return self.object_list.count()
  File "/opt/python3.5/lib/python3.5/site-packages/django/db/models/query.py", line 364, in count
    return self.query.get_count(using=self.db)
  File "/opt/python3.5/lib/python3.5/site-packages/django/db/models/sql/query.py", line 499, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "/opt/python3.5/lib/python3.5/site-packages/django/db/models/sql/query.py", line 480, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/opt/python3.5/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 886, in execute_sql
    raise original_exception
  File "/opt/python3.5/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 876, in execute_sql
    cursor.execute(sql, params)
  File "/opt/python3.5/lib/python3.5/site-packages/raven/contrib/django/client.py", line 114, in execute
    return real_execute(self, sql, params)
  File "/opt/python3.5/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/opt/python3.5/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/opt/python3.5/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/opt/python3.5/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "projects_project" does not exist
LINE 1: SELECT COUNT(*) AS "__count" FROM "projects_project" WHERE "...


Than i started to assuming that there is no tables in the DB. Then i gone inside postersql it shows that
postgres=# \q
[root@ip-172-31-19-151 logs]# su postgres -c psql
psql (9.5.11)
Type "help" for help.

postgres=# /l
postgres-# \connect taiga
You are now connected to database "taiga" as user "postgres".
taiga-# \dt
             List of relations
 Schema |       Name        | Type  | Owner
--------+-------------------+-------+-------
 public | django_migrations | table | taiga
(1 row)

taiga-#

It don't have any tables except  django_migrations.

How can i get all tables manually.

**Comment by ThangarajRavi** [comment]
I followed script based installation and i'm using  centos7.

**Comment by nsomaru** [comment]
@ThangarajRavi try running `./manage.py migrate`
