### ISSUE TITLE
On upgrade can no longer access US or issues 

### ISSUE THREAD

**Issue by mgilroy** [taigaio/taiga-back#1119]
Upgraded our own server today to the latest stable branch for the UI and backend today. Appeared to complete the upgrade without issue. However, I can no longer view user stories or issues. 

When I attempt to view either I get the following errors in the browser console:

No module named 'smart_strong'

"No StorageEntry matches the given query."

I've attempted to re-create the virtualenv but still hit the same issue.

From the logs on the taiga server I get the following:

ERROR:2018-06-04 14:55:21,036: Internal Server Error: /api/v1/userstories/by_ref
Traceback (most recent call last):
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/viewsets.py", line 106, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/views.py", line 460, in dispatch
    response = self.handle_exception(exc)
  File "/home/taiga/taiga-back/taiga/base/api/views.py", line 458, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/taiga/taiga-back/taiga/projects/mixins/by_ref.py", line 48, in by_ref
    return self.retrieve(request, **retrieve_kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/mixins.py", line 159, in retrieve
    return response.Ok(serializer.data)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/serpy/serializer.py", line 134, in data
    self._data = self.to_value(self.instance)
  File "/home/taiga/taiga-back/taiga/projects/mixins/serializers.py", line 90, in to_value
    return super().to_value(instance)
  File "/home/taiga/taiga-back/taiga/projects/mixins/serializers.py", line 30, in to_value
    return super().to_value(instance)
  File "/home/taiga/taiga-back/taiga/projects/mixins/serializers.py", line 66, in to_value
    return super().to_value(instance)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/serpy/serializer.py", line 124, in to_value
    return self._serialize(instance, fields)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/serpy/serializer.py", line 107, in _serialize
    result = getter(self, instance)
  File "/home/taiga/taiga-back/taiga/projects/userstories/serializers.py", line 162, in get_blocked_note_html
    return mdrender(obj.project, obj.blocked_note)
  File "/home/taiga/taiga-back/taiga/mdrender/service.py", line 99, in _decorator
    returned_value = func(project, text)
  File "/home/taiga/taiga-back/taiga/mdrender/service.py", line 115, in render
    md = _get_markdown(project)
  File "/home/taiga/taiga-back/taiga/mdrender/service.py", line 108, in _get_markdown
    md = Markdown(extensions=extensions)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/markdown/core.py", line 78, in __init__
    configs=kwargs.get('extension_configs', {}))
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/markdown/core.py", line 106, in registerExtensions
    ext.extendMarkdown(self, globals())
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/markdown/extensions/extra.py", line 59, in extendMarkdown
    md.registerExtensions(extensions, self.config)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/markdown/core.py", line 104, in registerExtensions
    ext = self.build_extension(ext, configs.get(ext, {}))
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/markdown/core.py", line 142, in build_extension
    module = importlib.import_module(ext_name)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'smart_strong'

I

**Comment by mgilroy** [comment]
So found a solution. We had a stray process that had not stopped

`
ps -efwww

taiga     1252  1004  0 Jan04 ?        00:24:16 /home/taiga/.virtualenvs/taiga/bin/python3.5 /home/taiga/.virtualenvs/taiga/bin/gunicorn -w 3 -t 60 --pythonpath=. -b 127.0.0.1:8001 taiga.wsgi

(bad stray) ^^^ / vvv (good new)

taiga     9452  1252  0 Jun04 ?        00:00:02 /home/taiga/.virtualenvs/taiga/bin/python3.5 /home/taiga/.virtualenvs/taiga/bin/gunicorn -w 3 -t 60 --pythonpath=. -b 127.0.0.1:8001 taiga.wsgi
taiga     9453  1252  0 Jun04 ?        00:00:02 /home/taiga/.virtualenvs/taiga/bin/python3.5 /home/taiga/.virtualenvs/taiga/bin/gunicorn -w 3 -t 60 --pythonpath=. -b 127.0.0.1:8001 taiga.wsgi
taiga     9454  1252  0 Jun04 ?        00:00:02 /home/taiga/.virtualenvs/taiga/bin/python3.5 /home/taiga/.virtualenvs/taiga/bin/gunicorn -w 3 -t 60 --pythonpath=. -b 127.0.0.1:8001 taiga.wsgi

$ sudo kill -TERM 1252
`
Killing the process fixed everything.

**Comment by Pitel** [comment]
Same here. Rebooted and it fixed itself.
