### ISSUE TITLE
symbol __res_maybe_init version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference

### ISSUE THREAD

**Issue by mahmoodn** [taigaio/taiga-back#1122]
Following the steps to build and run the taiga-bak ([here](http://taigaio.github.io/taiga-doc/dist/setup-development.html)), I hit an error when running `python manage.py migrate --noinput`. Please see below

```
(taiga) mahmood@student-virtual-machine:~/taiga-back$ pip install -r requirements-devel.txt
Collecting git+git://github.com/Python-Markdown/markdown.git@a4d4b61b5ce4a7dd96ddc13c66b8716d3ad8eb51 (from -r requirements.txt (line 4))
  Cloning git://github.com/Python-Markdown/markdown.git (to revision a4d4b61b5ce4a7dd96ddc13c66b8716d3ad8eb51) to /tmp/pip-req-build-hje0dlz9
Collecting git+https://github.com/Xof/django-pglocks.git (from -r requirements.txt (line 25))
  Cloning https://github.com/Xof/django-pglocks.git to /tmp/pip-req-build-wnki3d9k
Requirement already satisfied: CairoSVG==2.0.3 in /home/mahmood/.virtualenvs/taiga/lib/python3.6/site-packages (from -r requirements.txt (line 2)) (2.0.3)
Requirement already satisfied: Django==1.11.2 in /home/mahmood/.virtualenvs/taiga/lib/python3.6/site-packages (from -r requirements.txt (line 3)) (1.11.2)
Requirement already satisfied: Pillow==4.1.1 in /home/mahmood/.virtualenvs/taiga/lib/python3.6/site-packages (from -r requirements.txt (line 5)) (4.1.1)
Requirement already satisfied: PyJWT==1.5.0 in /home/mahmood/.virtualenvs/taiga/lib/python3.6/site-packages (from -r requirements.txt (line 6)) (1.5.0)
Requirement already satisfied: Unidecode==0.4.20 in /home/mahmood/.virtualenvs/taiga/lib/python3.6/site-packages (from -r requirements.txt (line 7)) (0.4.20)
Requirement already satisfied: amqp==2.1.4 in /home/mahmood/.virtualenvs/taiga/lib/python3.6/site-packages (from -r requirements.txt (line 8)) (2.1.4)
Requirement already satisfied: asana==0.6.7 in /home/mahmood/.virtualenvs/taiga/lib/python3.6/site-packages (from -r requirements.txt (line 9)) (0.6.7)
Requirement already satisfied: bleach==2.0.0 in /home/mahmood/.virtualenvs/taiga/lib/python3.6/site-packages (from -r requirements.txt (line 10)) (2.0.0)
Requirement already satisfied: celery==4.0.2 in /home/mahmood/.virtualenvs/taiga/lib/python3.6/site-packages (from -r requirements.txt (line 11)) (4.0.2)
Requirement already satisfied: kombu==4.0.2 in /home/mahmood/.virtualenvs/taiga/lib/python3.6/site-packages (from -r requirements.txt (line 12)) (4.0.2)
Collecting cryptography==1.9 (from -r requirements.txt (line 13))
  Using cached https://files.pythonhosted.org/packages/2a/0c/31bd69469e90035381f0197b48bf71032991d9f07a7e444c311b4a23a3df/cryptography-1.9.tar.gz
Collecting cssutils==1.0.2 (from -r requirements.txt (line 14))
  Using cached https://files.pythonhosted.org/packages/6b/15/a9fb9010f58d1c55dd0b7779db2334feb9a572d407024f39a60f44293861/cssutils-1.0.2-py3-none-any.whl
Collecting diff-match-patch==20121119 (from -r requirements.txt (line 15))
Collecting django-ipware==1.1.6 (from -r requirements.txt (line 16))
Collecting django-jinja==2.3.1 (from -r requirements.txt (line 17))
  Using cached https://files.pythonhosted.org/packages/2f/b8/60dde72027b0d6f8ce670cddb5503c06baa5b6d984d668c8a89d01aeadc3/django_jinja-2.3.1-py3-none-any.whl
Collecting django-picklefield==0.3.2 (from -r requirements.txt (line 18))
  Using cached https://files.pythonhosted.org/packages/b1/67/0f7f24e61f71aa7c604dab55497495f599906a20187e92edf70939c71d80/django_picklefield-0.3.2-py2.py3-none-any.whl
Collecting django-sampledatahelper==0.4.1 (from -r requirements.txt (line 19))
Collecting django-sites==0.9 (from -r requirements.txt (line 20))
Collecting django-sr==0.0.4 (from -r requirements.txt (line 21))
Collecting djmail==1.0.1 (from -r requirements.txt (line 22))
Collecting easy-thumbnails==2.4.1 (from -r requirements.txt (line 23))
  Using cached https://files.pythonhosted.org/packages/e1/e1/5d305ec7b894d0ae629593b10b0c33e913bfa0179fead8b8732aa0c01cf7/easy_thumbnails-2.4.1-py2.py3-none-any.whl
Collecting fn==0.4.3 (from -r requirements.txt (line 24))
Collecting gunicorn==19.7.1 (from -r requirements.txt (line 26))
  Using cached https://files.pythonhosted.org/packages/64/32/becbd4089a4c06f0f9f538a76e9fe0b19a08f010bcb47dcdbfbc640cdf7d/gunicorn-19.7.1-py2.py3-none-any.whl
Collecting jinja2==2.9.6 (from -r requirements.txt (line 27))
  Using cached https://files.pythonhosted.org/packages/5e/73/10c45b82a88ed6b7751bd40da31eeefd7b362e07b56a99aa6e56655a0794/Jinja2-2.9.6-py2.py3-none-any.whl
Requirement already satisfied: idna==2.5 in /home/mahmood/.virtualenvs/taiga/lib/python3.6/site-packages (from -r requirements.txt (line 28)) (2.5)
Requirement already satisfied: lxml==3.8.0 in /home/mahmood/.virtualenvs/taiga/lib/python3.6/site-packages (from -r requirements.txt (line 29)) (3.8.0)
Collecting netaddr==0.7.19 (from -r requirements.txt (line 30))
  Using cached https://files.pythonhosted.org/packages/ba/97/ce14451a9fd7bdb5a397abf99b24a1a6bb7a1a440b019bebd2e9a0dbec74/netaddr-0.7.19-py2.py3-none-any.whl
Collecting premailer==3.0.1 (from -r requirements.txt (line 31))
  Using cached https://files.pythonhosted.org/packages/d8/bb/ca2d0ec8d3f364bea9b2dec013d089940031b456e99c3cc213d05b824f22/premailer-3.0.1-py2.py3-none-any.whl
Collecting psd-tools==1.4 (from -r requirements.txt (line 32))
Collecting psycopg2==2.7.1 (from -r requirements.txt (line 33))
  Using cached https://files.pythonhosted.org/packages/90/bb/fd1a81e1a51b2df2d825e778fd58d508a4fc9ab360684348222bda3ff704/psycopg2-2.7.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting pygments==2.2.0 (from -r requirements.txt (line 34))
  Using cached https://files.pythonhosted.org/packages/02/ee/b6e02dc6529e82b75bb06823ff7d005b141037cb1416b10c6f00fc419dca/Pygments-2.2.0-py2.py3-none-any.whl
Collecting pyjwkest==1.3.2 (from -r requirements.txt (line 35))
Collecting python-dateutil==2.6.0 (from -r requirements.txt (line 36))
  Using cached https://files.pythonhosted.org/packages/40/8b/275015d7a9ec293cf1bbf55433258fbc9d0711890a7f6dc538bac7b86bce/python_dateutil-2.6.0-py2.py3-none-any.whl
Collecting python-magic==0.4.13 (from -r requirements.txt (line 37))
  Using cached https://files.pythonhosted.org/packages/b5/af/74f2df75e372a21547b4dc0d0878f883be4bfa936ddd835e285cb4aab538/python_magic-0.4.13-py2.py3-none-any.whl
Requirement already satisfied: pytz==2017.2 in /home/mahmood/.virtualenvs/taiga/lib/python3.6/site-packages (from -r requirements.txt (line 38)) (2017.2)
Collecting raven==6.1.0 (from -r requirements.txt (line 39))
  Using cached https://files.pythonhosted.org/packages/17/c0/c78198b9f2459f28de1bcba7a3586602a5b85858e9657db59e881fbea89f/raven-6.1.0-py2.py3-none-any.whl
Collecting redis==2.10.5 (from -r requirements.txt (line 40))
  Using cached https://files.pythonhosted.org/packages/08/c1/457428f7507e27ba7144758a7b716ea35766e6d602f4a0c16e443ab3d381/redis-2.10.5-py2.py3-none-any.whl
Requirement already satisfied: requests-oauthlib==0.8.0 in /home/mahmood/.virtualenvs/taiga/lib/python3.6/site-packages (from -r requirements.txt (line 41)) (0.8.0)
Requirement already satisfied: requests==2.17.3 in /home/mahmood/.virtualenvs/taiga/lib/python3.6/site-packages (from -r requirements.txt (line 42)) (2.17.3)
Collecting serpy==0.1.1 (from -r requirements.txt (line 43))
  Using cached https://files.pythonhosted.org/packages/5a/4e/a8f667bcacfc7fc8b011484e5642055bbc57d1755cc82ee337753777c877/serpy-0.1.1-py2.py3-none-any.whl
Requirement already satisfied: six==1.10.0 in /home/mahmood/.virtualenvs/taiga/lib/python3.6/site-packages (from -r requirements.txt (line 44)) (1.10.0)
Collecting webcolors==1.7 (from -r requirements.txt (line 45))
Collecting coverage==4.4.1 (from -r requirements-devel.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/12/9f/b5030263383b551ae844b2365b9a607a3266c48b0f7cc55fc2a6c852d6e3/coverage-4.4.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting coveralls==1.1 (from -r requirements-devel.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/81/f9/da2ad9334f60e418cb229c58724330be2635b369676d3eec8f61e1f85faa/coveralls-1.1-py2.py3-none-any.whl
Collecting django-slowdown==0.0.1 (from -r requirements-devel.txt (line 5))
Collecting factory_boy==2.8.1 (from -r requirements-devel.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/8d/0a/1466fd13883dbc4a47e16d4a316389f0e0aa23bdef27759603467f9e6ecb/factory_boy-2.8.1-py2.py3-none-any.whl
Collecting py==1.4.34 (from -r requirements-devel.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/53/67/9620edf7803ab867b175e4fd23c7b8bd8eba11cb761514dcd2e726ef07da/py-1.4.34-py2.py3-none-any.whl
Collecting pytest-django==3.1.2 (from -r requirements-devel.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/0f/c4/123ec7829e175af511c5be0501df9552261c2bf549b8e7a43ba35505594e/pytest_django-3.1.2-py2.py3-none-any.whl
Collecting pytest-pythonpath==0.7.1 (from -r requirements-devel.txt (line 9))
Collecting pytest==3.1.1 (from -r requirements-devel.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/43/67/bd3a6148fc8a2d989ded3af319100e30fb6908f2d0a284e5cd9d20fbeb6d/pytest-3.1.1-py2.py3-none-any.whl
Collecting transifex-client==0.12.4 (from -r requirements-devel.txt (line 11))
Requirement already satisfied: tinycss in /home/mahmood/.virtualenvs/taiga/lib/python3.6/site-packages (from CairoSVG==2.0.3->-r requirements.txt (line 2)) (0.4)
Requirement already satisfied: cairocffi in /home/mahmood/.virtualenvs/taiga/lib/python3.6/site-packages (from CairoSVG==2.0.3->-r requirements.txt (line 2)) (0.8.1)
Requirement already satisfied: cssselect in /home/mahmood/.virtualenvs/taiga/lib/python3.6/site-packages (from CairoSVG==2.0.3->-r requirements.txt (line 2)) (1.0.3)
Requirement already satisfied: olefile in /home/mahmood/.virtualenvs/taiga/lib/python3.6/site-packages (from Pillow==4.1.1->-r requirements.txt (line 5)) (0.45.1)
Requirement already satisfied: vine>=1.1.3 in /home/mahmood/.virtualenvs/taiga/lib/python3.6/site-packages (from amqp==2.1.4->-r requirements.txt (line 8)) (1.1.4)
Requirement already satisfied: html5lib>=0.99999999 in /home/mahmood/.virtualenvs/taiga/lib/python3.6/site-packages (from bleach==2.0.0->-r requirements.txt (line 10)) (1.0.1)
Requirement already satisfied: billiard<3.6.0,>=3.5.0.2 in /home/mahmood/.virtualenvs/taiga/lib/python3.6/site-packages (from celery==4.0.2->-r requirements.txt (line 11)) (3.5.0.3)
Requirement already satisfied: asn1crypto>=0.21.0 in /home/mahmood/.virtualenvs/taiga/lib/python3.6/site-packages (from cryptography==1.9->-r requirements.txt (line 13)) (0.24.0)
Requirement already satisfied: cffi>=1.7 in /home/mahmood/.virtualenvs/taiga/lib/python3.6/site-packages (from cryptography==1.9->-r requirements.txt (line 13)) (1.11.5)
Collecting sampledata (from django-sampledatahelper==0.4.1->-r requirements.txt (line 19))
Collecting MarkupSafe>=0.23 (from jinja2==2.9.6->-r requirements.txt (line 27))
Collecting docopt>=0.5 (from psd-tools==1.4->-r requirements.txt (line 32))
Collecting future (from pyjwkest==1.3.2->-r requirements.txt (line 35))
Collecting pycryptodomex (from pyjwkest==1.3.2->-r requirements.txt (line 35))
  Using cached https://files.pythonhosted.org/packages/b1/1a/c3f07c05556de1bf0469b92d797708272a7e06ea92be5882e32e9089cee7/pycryptodomex-3.6.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting contextlib2 (from raven==6.1.0->-r requirements.txt (line 39))
  Using cached https://files.pythonhosted.org/packages/a2/71/8273a7eeed0aff6a854237ab5453bc9aa67deb49df4832801c21f0ff3782/contextlib2-0.5.5-py2.py3-none-any.whl
Requirement already satisfied: oauthlib>=0.6.2 in /home/mahmood/.virtualenvs/taiga/lib/python3.6/site-packages (from requests-oauthlib==0.8.0->-r requirements.txt (line 41)) (2.1.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/mahmood/.virtualenvs/taiga/lib/python3.6/site-packages (from requests==2.17.3->-r requirements.txt (line 42)) (3.0.4)
Requirement already satisfied: urllib3<1.22,>=1.21.1 in /home/mahmood/.virtualenvs/taiga/lib/python3.6/site-packages (from requests==2.17.3->-r requirements.txt (line 42)) (1.21.1)
Requirement already satisfied: certifi>=2017.4.17 in /home/mahmood/.virtualenvs/taiga/lib/python3.6/site-packages (from requests==2.17.3->-r requirements.txt (line 42)) (2018.4.16)
Collecting Faker>=0.7.0 (from factory_boy==2.8.1->-r requirements-devel.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/5c/50/69efd9250a2be64f23ba1985e6b61ab9fcf829d75850044e2a8e4dfb909c/Faker-0.8.15-py2.py3-none-any.whl
Requirement already satisfied: setuptools in /home/mahmood/.virtualenvs/taiga/lib/python3.6/site-packages (from pytest==3.1.1->-r requirements-devel.txt (line 10)) (39.2.0)
Requirement already satisfied: webencodings in /home/mahmood/.virtualenvs/taiga/lib/python3.6/site-packages (from html5lib>=0.99999999->bleach==2.0.0->-r requirements.txt (line 10)) (0.5.1)
Requirement already satisfied: pycparser in /home/mahmood/.virtualenvs/taiga/lib/python3.6/site-packages (from cffi>=1.7->cryptography==1.9->-r requirements.txt (line 13)) (2.18)
Collecting text-unidecode==1.2 (from Faker>=0.7.0->factory_boy==2.8.1->-r requirements-devel.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/79/42/d717cc2b4520fb09e45b344b1b0b4e81aa672001dd128c180fabc655c341/text_unidecode-1.2-py2.py3-none-any.whl
Building wheels for collected packages: cryptography, Markdown, django-pglocks
  Running setup.py bdist_wheel for cryptography ... done
  Stored in directory: /home/mahmood/.cache/pip/wheels/0a/4c/1e/245b5da19dd23c6f10837990be2e221c03f0450b6363ef68b6
  Running setup.py bdist_wheel for Markdown ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-6alu5c6t/wheels/54/d8/4e/c42d3fac79a0e88ca7b6a2ac8a3b14f68c0a3e7b367df384e4
  Running setup.py bdist_wheel for django-pglocks ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-6alu5c6t/wheels/fb/d0/35/3b2ebb60f1a2378b9a9bae075d436e44556cc08d9abe978858
Successfully built cryptography Markdown django-pglocks
Installing collected packages: cryptography, cssutils, diff-match-patch, django-ipware, MarkupSafe, jinja2, django-jinja, django-picklefield, sampledata, django-sampledatahelper, django-sites, django-sr, djmail, easy-thumbnails, fn, gunicorn, netaddr, premailer, docopt, psd-tools, psycopg2, pygments, future, pycryptodomex, pyjwkest, python-dateutil, python-magic, contextlib2, raven, redis, serpy, webcolors, coverage, coveralls, django-slowdown, text-unidecode, Faker, factory-boy, py, pytest, pytest-django, pytest-pythonpath, transifex-client, Markdown, django-pglocks
Successfully installed Faker-0.8.15 Markdown-3.0.dev0 MarkupSafe-1.0 contextlib2-0.5.5 coverage-4.4.1 coveralls-1.1 cryptography-1.9 cssutils-1.0.2 diff-match-patch-20121119 django-ipware-1.1.6 django-jinja-2.3.1 django-pglocks-1.0.2 django-picklefield-0.3.2 django-sampledatahelper-0.4.1 django-sites-0.9 django-slowdown-0.0.1 django-sr-0.0.4 djmail-1.0.1 docopt-0.6.2 easy-thumbnails-2.4.1 factory-boy-2.8.1 fn-0.4.3 future-0.16.0 gunicorn-19.7.1 jinja2-2.9.6 netaddr-0.7.19 premailer-3.0.1 psd-tools-1.4 psycopg2-2.7.1 py-1.4.34 pycryptodomex-3.6.1 pygments-2.2.0 pyjwkest-1.3.2 pytest-3.1.1 pytest-django-3.1.2 pytest-pythonpath-0.7.1 python-dateutil-2.6.0 python-magic-0.4.13 raven-6.1.0 redis-2.10.5 sampledata-0.3.7 serpy-0.1.1 text-unidecode-1.2 transifex-client-0.12.4 webcolors-1.7
(taiga) mahmood@student-virtual-machine:~/taiga-back$
(taiga) mahmood@student-virtual-machine:~/taiga-back$
(taiga) mahmood@student-virtual-machine:~/taiga-back$
(taiga) mahmood@student-virtual-machine:~/taiga-back$
(taiga) mahmood@student-virtual-machine:~/taiga-back$
(taiga) mahmood@student-virtual-machine:~/taiga-back$
(taiga) mahmood@student-virtual-machine:~/taiga-back$ vim settings/local.py
(taiga) mahmood@student-virtual-machine:~/taiga-back$ python manage.py migrate --noinput
Trying import local.py settings...
Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/home/mahmood/.virtualenvs/taiga/lib/python3.6/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/home/mahmood/.virtualenvs/taiga/lib/python3.6/site-packages/django/core/management/__init__.py", line 337, in execute
    django.setup()
  File "/home/mahmood/.virtualenvs/taiga/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/mahmood/.virtualenvs/taiga/lib/python3.6/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/mahmood/.virtualenvs/taiga/lib/python3.6/site-packages/django/apps/config.py", line 120, in create
    mod = import_module(mod_path)
  File "/home/mahmood/.virtualenvs/taiga/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mahmood/.virtualenvs/taiga/lib/python3.6/site-packages/django/contrib/postgres/apps.py", line 8, in <module>
    from .signals import register_type_handlers
  File "/home/mahmood/.virtualenvs/taiga/lib/python3.6/site-packages/django/contrib/postgres/signals.py", line 1, in <module>
    import psycopg2
  File "/home/mahmood/.virtualenvs/taiga/lib/python3.6/site-packages/psycopg2/__init__.py", line 50, in <module>
    from psycopg2._psycopg import (                     # noqa
ImportError: /home/mahmood/.virtualenvs/taiga/lib/python3.6/site-packages/psycopg2/.libs/libresolv-2-c4c53def.5.so: symbol __res_maybe_init version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference

```

How can I fix that? The OS is Ubuntu 18.04

**Comment by alexhermida** [comment]
Hello @mahmoodn 

Seems to be a problem with pyscopg2 2.7.1 version and glibc (https://github.com/psycopg/psycopg2-wheels/issues/2). You can try to update to 2.7.3.2 `pip install pyscopg2==2.7.3.2` or  `pip install pyscopg2 --upgrade`

Anyway we're going to evaluate upgrading pyscopg2 to the latest version.

**Comment by mahmoodn** [comment]
Yup. Thank you very much.

**Comment by muellert** [comment]
I encountered this error today as well, with the latest Taiga.

**Comment by oleyet** [comment]
Hola, yo pude resolver el problema, desinstalando versiones anteriores que tenia del paquete en otros virtual env y luego instalando de nuevo 2.7.3.1

**Comment by eliadl** [comment]
[Release notes](http://initd.org/psycopg/docs/news.html#what-s-new-in-psycopg-2-7-3-1) say 2.7.3.1 was released to solve exactly this issue:

> Dropped libresolv from wheel package to avoid incompatibility with glibc 2.26 (wheels ticket [#2](https://github.com/psycopg/psycopg2-wheels/issues/2)).

**Comment by muaaz123** [comment]
Try this 

sudo pip install psycopg2==2.7.3.2
