### ISSUE TITLE
can't run the test suite

### ISSUE THREAD

**Issue by muellert** [taigaio/taiga-back#1128]
**Do you want to request a *feature* or report a *bug*?**

This is a bug.

**What is the current behavior?**

I can't run the test suite:

   (taiga)$ pytest
    Trying import local.py settings...
    Traceback (most recent call last):
      File "/home/debian/.virtualenvs/taiga/bin/pytest", line 11, in <module>
        sys.exit(main())
      File "/home/debian/.virtualenvs/taiga/lib/python3.6/site-packages/_pytest/config.py", line 49, in main
        config = _prepareconfig(args, plugins)
      File "/home/debian/.virtualenvs/taiga/lib/python3.6/site-packages/_pytest/config.py", line 158, in _prepareconfig
        pluginmanager=pluginmanager, args=args)
      File "/home/debian/.virtualenvs/taiga/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
        return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
      File "/home/debian/.virtualenvs/taiga/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
        return self._inner_hookexec(hook, methods, kwargs)
      File "/home/debian/.virtualenvs/taiga/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
        _MultiCall(methods, kwargs, hook.spec_opts).execute()
      File "/home/debian/.virtualenvs/taiga/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 613, in execute
        return _wrapped_call(hook_impl.function(*args), self.execute)
      File "/home/debian/.virtualenvs/taiga/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 250, in _wrapped_call
        wrap_controller.send(call_outcome)
      File "/home/debian/.virtualenvs/taiga/lib/python3.6/site-packages/_pytest/helpconfig.py", line 34, in pytest_cmdline_parse
        config = outcome.get_result()
      File "/home/debian/.virtualenvs/taiga/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 279, in get_result
        raise ex[1].with_traceback(ex[2])
      File "/home/debian/.virtualenvs/taiga/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 265, in __init__
        self.result = func()
      File "/home/debian/.virtualenvs/taiga/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
        res = hook_impl.function(*args)
      File "/home/debian/.virtualenvs/taiga/lib/python3.6/site-packages/_pytest/config.py", line 928, in pytest_cmdline_parse
        self.parse(args)
      File "/home/debian/.virtualenvs/taiga/lib/python3.6/site-packages/_pytest/config.py", line 1100, in parse
        self._preparse(args, addopts=addopts)
      File "/home/debian/.virtualenvs/taiga/lib/python3.6/site-packages/_pytest/config.py", line 1071, in _preparse
        args=args, parser=self._parser)
      File "/home/debian/.virtualenvs/taiga/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
        return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
      File "/home/debian/.virtualenvs/taiga/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
        return self._inner_hookexec(hook, methods, kwargs)
      File "/home/debian/.virtualenvs/taiga/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
        _MultiCall(methods, kwargs, hook.spec_opts).execute()
      File "/home/debian/.virtualenvs/taiga/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 613, in execute
        return _wrapped_call(hook_impl.function(*args), self.execute)
      File "/home/debian/.virtualenvs/taiga/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 254, in _wrapped_call
        return call_outcome.get_result()
      File "/home/debian/.virtualenvs/taiga/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 279, in get_result
        raise ex[1].with_traceback(ex[2])
      File "/home/debian/.virtualenvs/taiga/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 265, in __init__
        self.result = func()
      File "/home/debian/.virtualenvs/taiga/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
        res = hook_impl.function(*args)
      File "/home/debian/.virtualenvs/taiga/lib/python3.6/site-packages/pytest_django/plugin.py", line 246, in pytest_load_initial_conftests
        _setup_django()
      File "/home/debian/.virtualenvs/taiga/lib/python3.6/site-packages/pytest_django/plugin.py", line 149, in _setup_django
        django.setup()
      File "/home/debian/.virtualenvs/taiga/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
        apps.populate(settings.INSTALLED_APPS)
      File "/home/debian/.virtualenvs/taiga/lib/python3.6/site-packages/django/apps/registry.py", line 85, in populate
        app_config = AppConfig.create(entry)
      File "/home/debian/.virtualenvs/taiga/lib/python3.6/site-packages/django/apps/config.py", line 120, in create
        mod = import_module(mod_path)
      File "/home/debian/.virtualenvs/taiga/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 678, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/home/debian/.virtualenvs/taiga/lib/python3.6/site-packages/django/contrib/postgres/apps.py", line 8, in <module>
        from .signals import register_type_handlers
      File "/home/debian/.virtualenvs/taiga/lib/python3.6/site-packages/django/contrib/postgres/signals.py", line 1, in <module>
        import psycopg2
      File "/home/debian/.virtualenvs/taiga/lib/python3.6/site-packages/psycopg2/__init__.py", line 50, in <module>
    from psycopg2._psycopg import (                     # noqa
ImportError: /home/debian/.virtualenvs/taiga/lib/python3.6/site-packages/psycopg2/.libs/libresolv-2-c4c53def.5.so: symbol __res_maybe_init version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference

**If the current behavior is a bug, please provide the steps to reproduce.**

On a Debian/buster machine, do the following:

1. get the repo
2. install the devel requirements
3. run 'pytest'

(You need to unpin 'cryptography' to get to a point where pip will succeed.)

**What is the expected behavior?**

The test suite should run.

**Is it happening in taiga.io or in your own instance?**

This is happening locally. Also, it happens on both master and stable.

**What browser/version are you using?**

n/a

**Are there any console errors *(Ctrl + F12)* in red?**

Yes, see above

**Comment by muellert** [comment]
It works after upgrading psycopg to the latest version:

1. unpin psycopg2 in requirements.txt
2. pip install -U psycopg2
