### ISSUE TITLE
Received this upon upgrade

### ISSUE THREAD

**Issue by uhlhosting** [taigaio/taiga-back#1165]
```
(taiga) taiga@ipm:~/taiga-back$ python manage.py loaddata initial_project_templates --traceback
Trying import local.py settings...
/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Traceback (most recent call last):
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: column "us_duedates" of relation "projects_projecttemplate" does not exist
LINE 1: ..._limit": null, "slug": "archived", "order": 6}]', "us_duedat...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/management/commands/loaddata.py", line 69, in handle
    self.loaddata(fixture_labels)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/management/commands/loaddata.py", line 109, in loaddata
    self.load_label(fixture_label)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/management/commands/loaddata.py", line 175, in load_label
    obj.save(using=self.using)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/serializers/base.py", line 205, in save
    models.Model.save_base(self.object, using=using, raw=True, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/models/base.py", line 836, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/models/base.py", line 903, in _save_table
    forced_update)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/models/base.py", line 953, in _do_update
    return filtered._update(values) > 0
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/models/query.py", line 664, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1191, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 886, in execute_sql
    raise original_exception
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 876, in execute_sql
    cursor.execute(sql, params)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/raven/contrib/django/client.py", line 114, in execute
    return real_execute(self, sql, params)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: Problem installing fixture '/home/taiga/taiga-back/taiga/projects/fixtures/initial_project_templates.json': Could not load projects.ProjectTemplate(pk=1): column "us_duedates" of relation "projects_projecttemplate" does not exist
LINE 1: ..._limit": null, "slug": "archived", "order": 6}]', "us_duedat...
                                                             ^

(taiga) taiga@ipm:~/taiga-back$ 

```

**Comment by uhlhosting** [comment]
Maybe the documentation can be updated in the upgrade area, since I had to always run the last command in order to have my context in my site, previous commands, make it all vanish. Problem solved after running second command, despite the warning error from python psycopg2

**Comment by alexhermida** [comment]
@uhlhosting you can check the documentation at http://taigaio.github.io/taiga-doc/dist/upgrades.html#_3_3_0_3_4_x 

First of all it says that you have to follow the default process, it includes the migration. Maybe we can add a link in the `Follow the default process.` text to make it more explicit.
