### ISSUE TITLE
/api/v1/importer : internal server error

### ISSUE THREAD

**Issue by tcharlss** [taigaio/taiga-back#1205]
Hi,

I tried the [Redmine to Taiga migrator](https://github.com/taigaio/redmine-migrator), it seemed to work fine, but about half of the issues where not imported.

In the migrator logs, I can indeed see these errors : `2018-11-26 15:17:56.515 ERROR - org.apache.log4j.Category$error$2Server response ===> <h1>Server Error (500)</h1>`

And in gunicorn logs, I see the corresponding errors : `ERROR:2018-11-26 15:17:56,817: Internal Server Error: /api/v1/importer/25/issue`

So it seems the problem comes from Taiga, not the migrator.
It is our own instance of Taiga, at the latest stable git revision (taiga-back : 3.4.4)

**Comment by tcharlss** [comment]
Here's the complete log :
```
ERROR:2019-02-21 09:40:22,993: Internal Server Error: /api/v1/importer/34/issue
Traceback (most recent call last):
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/viewsets.py", line 106, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/views.py", line 460, in dispatch
    response = self.handle_exception(exc)
  File "/home/taiga/taiga-back/taiga/base/api/views.py", line 458, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/lib/python3.5/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/taiga/taiga-back/taiga/export_import/api.py", line 280, in issue
    issue = services.store.store_issue(project, request.DATA.copy())
  File "/home/taiga/taiga-back/taiga/export_import/services/store.py", line 576, in store_issue
    _store_history(project, validator.object, history, statuses)
  File "/home/taiga/taiga-back/taiga/export_import/services/store.py", line 160, in _store_history
    if validator.is_valid():
  File "/home/taiga/taiga-back/taiga/base/api/serializers.py", line 601, in is_valid
    return not self.errors
  File "/home/taiga/taiga-back/taiga/base/api/serializers.py", line 593, in errors
    ret = self.from_native(data, files)
  File "/home/taiga/taiga-back/taiga/base/api/serializers.py", line 1105, in from_native
    instance = super(ModelSerializer, self).from_native(data, files)
  File "/home/taiga/taiga-back/taiga/base/api/serializers.py", line 420, in from_native
    return self.restore_object(attrs, instance=getattr(self, "object", None))
  File "/home/taiga/taiga-back/taiga/export_import/validators/mixins.py", line 49, in restore_object
    snapshot = attrs["snapshot"]
KeyError: 'snapshot'
```
