### ISSUE TITLE
[BUG] admin login crashing with Postgres 14

### ISSUE THREAD

**Issue by nebulade** [taigaio/taiga-back#122]
**Describe the bug**
When trying to login at `/admin/login` the app is crashing with status code 500 due to non existing column `users_user.uuid`

**How can we reproduce the behavior**
Install taiga-back 6.6.0. This worked fine in the previous version.

**Taiga environment**
Running Taiga on Cloudron. Our e2e tests for a new package were failing due to that.

Full logs of the crash:
```
14:37:55 - ERROR:2023-03-06 13:37:55,638: Internal Server Error: /admin/login/
14:37:55 - Traceback (most recent call last):
14:37:55 - File "/app/code/taiga/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
14:37:55 - return self.cursor.execute(sql, params)
14:37:55 - psycopg2.errors.UndefinedColumn: column users_user.uuid does not exist
14:37:55 - LINE 1: ..._user"."last_login", "users_user"."is_superuser", "users_use...
14:37:55 - ^
14:37:55 - HINT:  Perhaps you meant to reference the column "users_user.id".
14:37:55 - 
14:37:55 - 
14:37:55 - The above exception was the direct cause of the following exception:
14:37:55 - 
14:37:55 - Traceback (most recent call last):
14:37:55 - File "/app/code/taiga/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
14:37:55 - response = get_response(request)
14:37:55 - File "/app/code/taiga/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
14:37:55 - response = wrapped_callback(request, *callback_args, **callback_kwargs)
14:37:55 - File "/app/code/taiga/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
14:37:55 - response = view_func(request, *args, **kwargs)
14:37:55 - File "/app/code/taiga/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 414, in login
14:37:55 - return LoginView.as_view(**defaults)(request)
14:37:55 - File "/app/code/taiga/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
14:37:55 - return self.dispatch(request, *args, **kwargs)
14:37:55 - File "/app/code/taiga/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
14:37:55 - return bound_method(*args, **kwargs)
14:37:55 - File "/app/code/taiga/lib/python3.8/site-packages/django/views/decorators/debug.py", line 89, in sensitive_post_parameters_wrapper
14:37:55 - return view(request, *args, **kwargs)
14:37:55 - File "/app/code/taiga/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
14:37:55 - return bound_method(*args, **kwargs)
14:37:55 - File "/app/code/taiga/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
14:37:55 - response = view_func(request, *args, **kwargs)
14:37:55 - File "/app/code/taiga/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
14:37:55 - return bound_method(*args, **kwargs)
14:37:55 - File "/app/code/taiga/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
14:37:55 - response = view_func(request, *args, **kwargs)
14:37:55 - File "/app/code/taiga/lib/python3.8/site-packages/django/contrib/auth/views.py", line 63, in dispatch
14:37:55 - return super().dispatch(request, *args, **kwargs)
14:37:55 - File "/app/code/taiga/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
14:37:55 - return handler(request, *args, **kwargs)
14:37:55 - File "/app/code/taiga/lib/python3.8/site-packages/django/views/generic/edit.py", line 141, in post
14:37:55 - if form.is_valid():
14:37:55 - File "/app/code/taiga/lib/python3.8/site-packages/django/forms/forms.py", line 175, in is_valid
14:37:55 - return self.is_bound and not self.errors
14:37:55 - File "/app/code/taiga/lib/python3.8/site-packages/django/forms/forms.py", line 170, in errors
14:37:55 - self.full_clean()
14:37:55 - File "/app/code/taiga/lib/python3.8/site-packages/django/forms/forms.py", line 373, in full_clean
14:37:55 - self._clean_form()
14:37:55 - File "/app/code/taiga/lib/python3.8/site-packages/django/forms/forms.py", line 400, in _clean_form
14:37:55 - cleaned_data = self.clean()
14:37:55 - File "/app/code/taiga/lib/python3.8/site-packages/django/contrib/auth/forms.py", line 202, in clean
14:37:55 - self.user_cache = authenticate(self.request, username=username, password=password)
14:37:55 - File "/app/code/taiga/lib/python3.8/site-packages/django/views/decorators/debug.py", line 42, in sensitive_variables_wrapper
14:37:55 - return func(*func_args, **func_kwargs)
14:37:55 - File "/app/code/taiga/lib/python3.8/site-packages/django/contrib/auth/__init__.py", line 76, in authenticate
14:37:55 - user = backend.authenticate(request, **credentials)
14:37:55 - File "/app/code/taiga/lib/python3.8/site-packages/django/contrib/auth/backends.py", line 42, in authenticate
14:37:55 - user = UserModel._default_manager.get_by_natural_key(username)
14:37:55 - File "/app/code/taiga/lib/python3.8/site-packages/django/contrib/auth/base_user.py", line 45, in get_by_natural_key
14:37:55 - return self.get(**{self.model.USERNAME_FIELD: username})
14:37:55 - File "/app/code/taiga/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
14:37:55 - return getattr(self.get_queryset(), name)(*args, **kwargs)
14:37:55 - File "/app/code/taiga/lib/python3.8/site-packages/django/db/models/query.py", line 431, in get
14:37:55 - num = len(clone)
14:37:55 - File "/app/code/taiga/lib/python3.8/site-packages/django/db/models/query.py", line 262, in __len__
14:37:55 - self._fetch_all()
14:37:55 - File "/app/code/taiga/lib/python3.8/site-packages/django/db/models/query.py", line 1324, in _fetch_all
14:37:55 - self._result_cache = list(self._iterable_class(self))
14:37:55 - File "/app/code/taiga/lib/python3.8/site-packages/django/db/models/query.py", line 51, in __iter__
14:37:55 - results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
14:37:55 - File "/app/code/taiga/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
14:37:55 - cursor.execute(sql, params)
14:37:55 - File "/app/code/taiga/lib/python3.8/site-packages/raven/contrib/django/client.py", line 127, in execute
14:37:55 - return real_execute(self, sql, params)
14:37:55 - File "/app/code/taiga/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
14:37:55 - return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
14:37:55 - File "/app/code/taiga/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
14:37:55 - return executor(sql, params, many, context)
14:37:55 - File "/app/code/taiga/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
14:37:55 - return self.cursor.execute(sql, params)
14:37:55 - File "/app/code/taiga/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
14:37:55 - raise dj_exc_value.with_traceback(traceback) from exc_value
14:37:55 - File "/app/code/taiga/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
```

**Comment by gramakri** [comment]
This crashes with python 3.10 as well.

**Comment by gramakri** [comment]
On further investigation, the issue is when using taiga with PostgreSQL 14. It works with PostgreSQL 12.

**Comment by bameda** [comment]
Yes, taiga is only compatible with postgresql >= 9.4 and  < 14 because some migrations require postgresql functions that have been deprecated (they have a new name and param list). 

Review the traces of the migrate command and you will see how not all of them could be applied.

**Comment by stefano-pogliani** [comment]
Hello,
Are there any plans to support PostgreSQL 14+?

**Comment by stefanoginella** [comment]
> Hello, Are there any plans to support PostgreSQL 14+?

Interested in this too. Is it in the roadmap?
