### ISSUE TITLE
Jira importer not working

### ISSUE THREAD

**Issue by Chilinot** [taigaio/taiga-back#1227]
**Do you want to request a *feature* or report a *bug*?**
Report bug

**What is the current behavior?**
Importing Jira projects is not possible.

Most likely Jira has changed their API, and Taiga has not been updated to accommodate.

Backend fails with the following stacktrace:
```
 ERROR:2019-01-11 20:50:18,877: Internal Server Error: /api/v1/importers/jira/import_project
 Traceback (most recent call last):
   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
     response = get_response(request)
   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
     response = self._get_response(request)
   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
     response = self.process_exception_by_middleware(e, request)
   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
     response = wrapped_callback(request, *callback_args, **callback_kwargs)
   File "/usr/src/taiga-back/taiga/base/api/viewsets.py", line 106, in view
     return self.dispatch(request, *args, **kwargs)
   File "/usr/local/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
     return view_func(*args, **kwargs)
   File "/usr/src/taiga-back/taiga/base/api/views.py", line 460, in dispatch
     response = self.handle_exception(exc)
   File "/usr/src/taiga-back/taiga/base/api/views.py", line 458, in dispatch
     response = handler(request, *args, **kwargs)
   File "/usr/src/taiga-back/taiga/importers/jira/api.py", line 166, in import_project
     project = importer.import_project(project_id, options)
   File "/usr/src/taiga-back/taiga/importers/jira/normal.py", line 53, in import_project
     self._import_issues_data(project_id, project, options)
   File "/usr/src/taiga-back/taiga/importers/jira/normal.py", line 331, in _import_issues_data
     issue['fields']['issuelinks'] += self._client.get("/issue/{}/remotelink".format(issue['key']))
 KeyError: 'issuelinks'
```

**If the current behavior is a bug, please provide the steps to reproduce.**

* Run Jira Software version v7.11.1
* Attempt to import projects from Jira using Taiga v4.0.3

**What is the expected behavior?**
Project should be imported.

**Is it happening in taiga.io or in your own instance?**
My own instance.

**What browser/version are you using?**
Firefox 64

**Are there any console errors *(Ctrl + F12)* in red?**
No

Thanks for reporting!

**Comment by Chilinot** [comment]
Dumping out the response from Jira and then searching it yields no matches for `issuelinks`.

**Comment by Chilinot** [comment]
I have been able to patch the importer to get it to work. And have been able to import a project now. However, I have not verified if my patch breaks anything. So I will not create a pull request unless you want me to.

Below is the patch:
```
diff --git a/taiga/importers/jira/normal.py b/taiga/importers/jira/normal.py
index 0293d7e..1f4f5a4 100644
--- a/taiga/importers/jira/normal.py
+++ b/taiga/importers/jira/normal.py
@@ -199,7 +199,8 @@ class JiraNormalImporter(JiraImporterCommon):
                 offset += issues['maxResults']
 
                 for issue in issues['issues']:
-                    issue['fields']['issuelinks'] += self._client.get("/issue/{}/remotelink".format(issue['key']))
+                    if 'issuelinks' in issue['fields']:
+                        issue['fields']['issuelinks'] += self._client.get("/issue/{}/remotelink".format(issue['key']))
                     assigned_to = users_bindings.get(issue['fields']['assignee']['key'] if issue['fields']['assignee'] else None, None)
                     owner = users_bindings.get(issue['fields']['creator']['key'] if issue['fields']['creator'] else None, self._user)
 
@@ -218,7 +219,7 @@ class JiraNormalImporter(JiraImporterCommon):
                         backlog_order=counter,
                         subject=issue['fields']['summary'],
                         description=issue['fields']['description'] or '',
-                        tags=issue['fields']['labels'],
+                        tags=issue['fields']['labels'] if 'labels' in issue['fields'] else [],
                         external_reference=external_reference,
                     )
 
@@ -258,7 +259,7 @@ class JiraNormalImporter(JiraImporterCommon):
     def _import_subtasks(self, project_id, project, us, issue, options):
         users_bindings = options.get('users_bindings', {})
 
-        if len(issue['fields']['subtasks']) == 0:
+        if 'subtasks' not in issue['fields'] or len(issue['fields']['subtasks']) == 0:
             return
 
         counter = 0
@@ -273,7 +274,8 @@ class JiraNormalImporter(JiraImporterCommon):
             offset += issues['maxResults']
 
             for issue in issues['issues']:
-                issue['fields']['issuelinks'] += self._client.get("/issue/{}/remotelink".format(issue['key']))
+                if 'issuelinks' in issue['fields']:
+                    issue['fields']['issuelinks'] += self._client.get("/issue/{}/remotelink".format(issue['key']))
                 assigned_to = users_bindings.get(issue['fields']['assignee']['key'] if issue['fields']['assignee'] else None, None)
                 owner = users_bindings.get(issue['fields']['creator']['key'] if issue['fields']['creator'] else None, self._user)
 
@@ -289,7 +291,7 @@ class JiraNormalImporter(JiraImporterCommon):
                     status=project.task_statuses.get(name=issue['fields']['status']['name']),
                     subject=issue['fields']['summary'],
                     description=issue['fields']['description'] or '',
-                    tags=issue['fields']['labels'],
+                    tags=issue['fields']['labels'] if 'labels' in issue['fields'] else [],
                     external_reference=external_reference,
                 )
 
@@ -328,7 +330,8 @@ class JiraNormalImporter(JiraImporterCommon):
                 offset += issues['maxResults']
 
                 for issue in issues['issues']:
-                    issue['fields']['issuelinks'] += self._client.get("/issue/{}/remotelink".format(issue['key']))
+                    if 'issuelinks' in issue['fields']:
+                        issue['fields']['issuelinks'] += self._client.get("/issue/{}/remotelink".format(issue['key']))
                     assigned_to = users_bindings.get(issue['fields']['assignee']['key'] if issue['fields']['assignee'] else None, None)
                     owner = users_bindings.get(issue['fields']['creator']['key'] if issue['fields']['creator'] else None, self._user)
 
@@ -343,7 +346,7 @@ class JiraNormalImporter(JiraImporterCommon):
                         status=project.issue_statuses.get(name=issue['fields']['status']['name']),
                         subject=issue['fields']['summary'],
                         description=issue['fields']['description'] or '',
-                        tags=issue['fields']['labels'],
+                        tags=issue['fields']['labels'] if 'labels' in issue['fields'] else [],
                         external_reference=external_reference,
                     )
 
@@ -356,8 +359,9 @@ class JiraNormalImporter(JiraImporterCommon):
                         created_date=issue['fields']['created']
                     )
                     take_snapshot(taiga_issue, comment="", user=None, delete=False)
-                    for subtask in issue['fields']['subtasks']:
-                        print("WARNING: Ignoring subtask {} because parent isn't a User Story".format(subtask['key']))
+                    if 'subtasks' in issue['fields']:
+                        for subtask in issue['fields']['subtasks']:
+                            print("WARNING: Ignoring subtask {} because parent isn't a User Story".format(subtask['key']))
                     self._import_comments(taiga_issue, issue, options)
                     self._import_attachments(taiga_issue, issue, options)
                     self._import_changelog(project, taiga_issue, issue, options)
@@ -383,7 +387,8 @@ class JiraNormalImporter(JiraImporterCommon):
                 offset += issues['maxResults']
 
                 for issue in issues['issues']:
-                    issue['fields']['issuelinks'] += self._client.get("/issue/{}/remotelink".format(issue['key']))
+                    if 'issuelinks' in issue['fields']:
+                        issue['fields']['issuelinks'] += self._client.get("/issue/{}/remotelink".format(issue['key']))
                     assigned_to = users_bindings.get(issue['fields']['assignee']['key'] if issue['fields']['assignee'] else None, None)
                     owner = users_bindings.get(issue['fields']['creator']['key'] if issue['fields']['creator'] else None, self._user)
 
@@ -399,7 +404,7 @@ class JiraNormalImporter(JiraImporterCommon):
                         subject=issue['fields']['summary'],
                         description=issue['fields']['description'] or '',
                         epics_order=counter,
-                        tags=issue['fields']['labels'],
+                        tags=issue['fields']['labels'] if 'labels' in issue['fields'] else [],
                         external_reference=external_reference,
                     )
 
```
