### ISSUE TITLE
Empty Epics, User Stories, Tasks, and Issues (extendMarkdown error)

### ISSUE THREAD

**Issue by bastianvergara** [taigaio/taiga-back#1229]
Hello,

After updating to 4.0.4 following the procedure in https://taigaio.github.io/taiga-doc/dist/upgrades.html, I find that Epics, User Stories, Tasks, and Issues are completely empty. There's an error 500 everytime I go inside one of this elements, the results of which you can see in the attachment.

![user story](https://user-images.githubusercontent.com/21223384/51251534-538c8a00-1978-11e9-8a60-cda7a142a21e.png)

I went to see the gunicorn log, and find several errors, like this one:

```
> ERROR:2019-01-16 13:12:58,044: Internal Server Error: /api/v1/userstories/by_ref
> Traceback (most recent call last):
>   File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
>     response = get_response(request)
>   File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
>     response = self._get_response(request)
>   File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
>     response = self.process_exception_by_middleware(e, request)
>   File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>   File "/home/taiga/taiga-back/taiga/base/api/viewsets.py", line 106, in view
>     return self.dispatch(request, *args, **kwargs)
>   File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
>     return view_func(*args, **kwargs)
>   File "/home/taiga/taiga-back/taiga/base/api/views.py", line 460, in dispatch
>     response = self.handle_exception(exc)
>   File "/home/taiga/taiga-back/taiga/base/api/views.py", line 458, in dispatch
>     response = handler(request, *args, **kwargs)
>   File "/home/taiga/taiga-back/taiga/projects/mixins/by_ref.py", line 48, in by_ref
>     return self.retrieve(request, **retrieve_kwargs)
>   File "/home/taiga/taiga-back/taiga/base/api/mixins.py", line 159, in retrieve
>     return response.Ok(serializer.data)
>   File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/serpy/serializer.py", line 134, in data
>     self._data = self.to_value(self.instance)
>   File "/home/taiga/taiga-back/taiga/projects/mixins/serializers.py", line 90, in to_value
>     return super().to_value(instance)
>   File "/home/taiga/taiga-back/taiga/projects/mixins/serializers.py", line 30, in to_value
>     return super().to_value(instance)
>   File "/home/taiga/taiga-back/taiga/projects/mixins/serializers.py", line 66, in to_value
>     return super().to_value(instance)
>   File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/serpy/serializer.py", line 124, in to_value
>     return self._serialize(instance, fields)
>   File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/serpy/serializer.py", line 107, in _serialize
>     result = getter(self, instance)
>   File "/home/taiga/taiga-back/taiga/projects/userstories/serializers.py", line 162, in get_blocked_note_html
>     return mdrender(obj.project, obj.blocked_note)
>   File "/home/taiga/taiga-back/taiga/mdrender/service.py", line 99, in _decorator
>     returned_value = func(project, text)
>   File "/home/taiga/taiga-back/taiga/mdrender/service.py", line 115, in render
>     md = _get_markdown(project)
>   File "/home/taiga/taiga-back/taiga/mdrender/service.py", line 108, in _get_markdown
>     md = Markdown(extensions=extensions)
>   File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/markdown/core.py", line 78, in __init__
>     configs=kwargs.get('extension_configs', {}))
>   File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/markdown/core.py", line 106, in registerExtensions
>     ext.extendMarkdown(self, globals())
> TypeError: extendMarkdown() takes 2 positional arguments but 3 were given
> 
> 
```

I've regenerated the virtualenv but it remains the same.

**Comment by bastianvergara** [comment]
It was indeed a problem with markdown version, but I'm not sure how it was caused.

I bypassed it by creating the virtualenv again, this time with the same linux user that was used for the intital Taiga installation.

Apparently I was given a different user to acess the server, so I figure it must have haf an undesired effect during the upgrade process.

I'm closing this issue. 
Thanks for the help.
