### ISSUE TITLE
Error displaying page after update (extendMarkdown)

### ISSUE THREAD

**Issue by neugii** [taigaio/taiga-back#1234]
Hi, 

i've done a upgrade to tiga 4.04 and now i'm not able to display any userstory/epic/task. 

From the Error log i see that there is a problem with:  extendMarkdown()

Detail Log: 

`ERROR:2019-01-25 07:42:57,890: Internal Server Error: /api/v1/milestones/18
Traceback (most recent call last):
  File "/appl/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/appl/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/appl/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/appl/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/appl/taiga/taiga-back/taiga/base/api/viewsets.py", line 106, in view
    return self.dispatch(request, *args, **kwargs)
  File "/appl/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/appl/taiga/taiga-back/taiga/base/api/views.py", line 460, in dispatch
    response = self.handle_exception(exc)
  File "/appl/taiga/taiga-back/taiga/base/api/views.py", line 458, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/lib64/python3.5/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/appl/taiga/taiga-back/taiga/base/decorators.py", line 60, in decorator
    return func(self, *args, **kwargs)
  File "/appl/taiga/taiga-back/taiga/base/api/mixins.py", line 249, in destroy
    self.pre_delete(obj)
  File "/appl/taiga/taiga-back/taiga/projects/history/mixins.py", line 83, in pre_delete
    self.persist_history_snapshot(obj, delete=True)
  File "/appl/taiga/taiga-back/taiga/projects/history/mixins.py", line 73, in persist_history_snapshot
    notifications_services.analize_object_for_watchers(obj, comment, user)
  File "/appl/taiga/taiga-back/taiga/projects/notifications/services.py", line 106, in analize_object_for_watchers
    mentions = get_object_mentions(obj, comment)
  File "/appl/taiga/taiga-back/taiga/projects/notifications/services.py", line 128, in get_object_mentions
    return get_mentions(obj.get_project(), "\n".join(texts))
  File "/appl/taiga/taiga-back/taiga/projects/notifications/services.py", line 133, in get_mentions
    _, data = render_and_extract(project, text)
  File "/appl/taiga/taiga-back/taiga/mdrender/service.py", line 120, in render_and_extract
    md = _get_markdown(project)
  File "/appl/taiga/taiga-back/taiga/mdrender/service.py", line 108, in _get_markdown
    md = Markdown(extensions=extensions)
  File "/appl/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/markdown/core.py", line 78, in __init__
    configs=kwargs.get('extension_configs', {}))
  File "/appl/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/markdown/core.py", line 106, in registerExtensions
    ext.extendMarkdown(self)
TypeError: extendMarkdown() takes 2 positional arguments but 3 were given
`
Any Infos on how to fix this?

best

**Comment by alexhermida** [comment]
Comments in issue #1229
