### ISSUE TITLE
Notification Error: Exception: listen EADDRINUSE

### ISSUE THREAD

**Issue by virse** [taigaio/taiga-back#1242]
Hey there,

 I receive the following error every few minutes in my taigaevents.stdout.log:

`2019-02-07 18:00:10 error uncaughtException: listen EADDRINUSE :::8888
Error: listen EADDRINUSE :::8888
    at Server.setupListenHandle [as _listen2] (net.js:1360:14)
    at listenInCluster (net.js:1401:12)
    at Server.listen (net.js:1485:7)
    at new WebSocketServer (/home/taiga/taiga-events/node_modules/ws/lib/WebSocketServer.js:77:20)
    at Object.<anonymous> (/home/taiga/taiga-events/index.coffee:14:7)
    at Object.<anonymous> (/home/taiga/taiga-events/index.coffee:1:1)
    at Module._compile (module.js:653:30)
    at Object.exports.run (/home/taiga/taiga-events/node_modules/coffeescript/lib/coffee-script/coffee-script.js:173:23)
    at compileScript (/home/taiga/taiga-events/node_modules/coffeescript/lib/coffee-script/command.js:224:29)
    at compilePath (/home/taiga/taiga-events/node_modules/coffeescript/lib/coffee-script/command.js:174:14)
    at Object.exports.run (/home/taiga/taiga-events/node_modules/coffeescript/lib/coffee-script/command.js:98:20)
    at Object.<anonymous> (/usr/lib/node_modules/coffeescript/bin/coffee:22:45)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3`

It is a fresh installation on my own server. I followed all the installation steps provided in the docs for production server. 

RabbitMQ is listening as expected on port 8888. But I thought that the event-modul uses the RabbitMQ-Server to launch the notifications.

What do I have to do to bring the notifications back to live?

My config.json

`{
    "url": "amqp://taiga:xxxx+@localhost:5672/taiga",
    "secret": "xxxx",
    "webSocketServer": {
        "port": 8888
    }
}`

Thanks for help
virse

**Comment by virse** [comment]
I did a fresh installation of rabbit and the error disappeared.

greets
