### ISSUE TITLE
Bitbucket webhook error

### ISSUE THREAD

**Issue by er-tho** [taigaio/taiga-back#1261]
Hello!
Taiga is setup on my company servers.
I've setup the bitbucket integration (not really difficult).

Unfortunately, when a request is made by Bitbucket I get an error.
Here you can find the error in the taiga log:

```
ERROR:2019-02-27 14:47:04,500: Internal Server Error: /api/v1/bitbucket-hook
Traceback (most recent call last):
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/viewsets.py", line 106, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/views.py", line 460, in dispatch
    response = self.handle_exception(exc)
  File "/home/taiga/taiga-back/taiga/base/api/views.py", line 458, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/taiga/taiga-back/taiga/hooks/api.py", line 79, in create
    event_hook.process_event()
  File "/home/taiga/taiga-back/taiga/hooks/event_hooks.py", line 250, in process_event
    send_notifications(element, history=snapshot)
  File "/usr/lib/python3.5/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/home/taiga/taiga-back/taiga/projects/notifications/services.py", line 267, in send_notifications
    send_sync_notifications(notification.id)
  File "/usr/lib/python3.5/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/home/taiga/taiga-back/taiga/projects/notifications/services.py", line 342, in send_sync_notifications
    email.send(user.email, context, headers=headers)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/djmail/template_mail.py", line 122, in send
    return email.send()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/mail/message.py", line 348, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/mail/backends/smtp.py", line 104, in send_messages
    new_conn_created = self.open()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/mail/backends/smtp.py", line 64, in open
    self.connection = self.connection_class(self.host, self.port, **connection_params)
  File "/usr/lib/python3.5/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.5/smtplib.py", line 335, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.5/smtplib.py", line 306, in _get_socket
    self.source_address)
  File "/usr/lib/python3.5/socket.py", line 711, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 702, in create_connection
    sock.connect(sa)
OSError: [Errno 113] No route to host
```

Im not really good in python development but as I understand the error comes from a socket connection (I guess the API tried to connect to the back or something like that).
Is it due to a misconfiguration of my own?
And so do you have any idea how I could resolve that?
Thanks!

**Comment by er-tho** [comment]
Ok Im closing this, I figured it out this was an error with notifications (yes it's written in the logs sorry ^^). Not the webhook.
It appears that the webhook still works so I only need to figure out why my mail server doesn't work.
