### ISSUE TITLE
Exception when run migrations

### ISSUE THREAD

**Issue by apardo** [taigaio/taiga-back#1269]
Hi, when I run the migration script I get this exception:

```python
  Applying users.0026_auto_20180514_1513... OK
  Applying users.0027_auto_20180610_2011... OK
  Applying userstorage.0001_initial... OK
  Applying userstorage.0002_fix_json_field_not_null... OK
  Applying userstorage.0003_json_to_jsonb... OK
  Applying userstories.0013_auto_20160722_1018... OK
  Applying userstories.0014_auto_20160928_0540... OK
  Applying userstories.0015_add_due_date... OK
  Applying userstories.0016_userstory_assigned_users... OK
  Applying userstories.0017_userstory_generated_from_task... OK
  Applying votes.0001_initial... OK
  Applying votes.0002_auto_20150805_1600... OK
  Applying webhooks.0001_initial... OK
  Applying webhooks.0002_webhook_name... OK
  Applying webhooks.0003_auto_20150122_1021... OK
  Applying webhooks.0004_auto_20150202_0834... OK
  Applying webhooks.0005_auto_20150505_1639... OK
  Applying webhooks.0006_json_to_jsonb... OK
  Applying wiki.0004_auto_20160928_0540... OK
  Applying wiki.0005_auto_20161201_1628... OK
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fe0403ec2f0>
Traceback (most recent call last):
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fe0403ec2f0>
Traceback (most recent call last):
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
```
I'm installing Taiga in Debian stretch and following the production installation guide.

Ciao

**Comment by apardo** [comment]
In Ubuntu 16.04 there is no issue.
