### ISSUE TITLE
Problems exporting project

### ISSUE THREAD

**Issue by jsancheztheia** [taigaio/taiga-back#1277]
Clicking export button results on http error 500.

I have taiga installed on my own server (Ubuntu 18.04). I have initially used it on taiga online and then exported the project. That project had an user, and I have changed its email. When I try to export the project again (now on my own server) taiga throws the following exception:

> Traceback (most recent call last):
  File "/home/taiga/.virtualenvs/taiga/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/viewsets.py", line 106, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/views.py", line 460, in dispatch
    response = self.handle_exception(exc)
  File "/home/taiga/taiga-back/taiga/base/api/views.py", line 458, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/taiga/taiga-back/taiga/export_import/api.py", line 84, in retrieve
    services.render_project(project, outfile)
  File "/home/taiga/taiga-back/taiga/export_import/services/render.py", line 73, in render_project
    dumped_value = json.dumps(field.to_value(item))
  File "/home/taiga/taiga-back/taiga/export_import/serializers/serializers.py", line 44, in to_value
    return super().to_value(value)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.6/site-packages/serpy/serializer.py", line 124, in to_value
    return self._serialize(instance, fields)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.6/site-packages/serpy/serializer.py", line 107, in _serialize
    result = getter(self, instance)
  File "/home/taiga/taiga-back/taiga/export_import/serializers/mixins.py", line 91, in get_history
    return HistoryExportSerializer(history_qs, many=True, statuses_queryset=self.statuses_queryset(obj.project)).data
  File "/home/taiga/.virtualenvs/taiga/lib/python3.6/site-packages/serpy/serializer.py", line 134, in data
    self._data = self.to_value(self.instance)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.6/site-packages/serpy/serializer.py", line 123, in to_value
    return [serialize(o, fields) for o in instance]
  File "/home/taiga/.virtualenvs/taiga/lib/python3.6/site-packages/serpy/serializer.py", line 123, in <listcomp>
    return [serialize(o, fields) for o in instance]
  File "/home/taiga/.virtualenvs/taiga/lib/python3.6/site-packages/serpy/serializer.py", line 107, in _serialize
    result = getter(self, instance)
  File "/home/taiga/taiga-back/taiga/export_import/serializers/mixins.py", line 64, in get_snapshot
    owner = cached_get_user_by_pk(snapshot.get("owner", None))
  File "/home/taiga/taiga-back/taiga/export_import/serializers/cache.py", line 37, in cached_get_user_by_pk
    _cache_user_by_pk[pk] = users_models.User.objects.get(pk=pk)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.6/site-packages/django/db/models/query.py", line 371, in get
    clone = self.filter(*args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.6/site-packages/django/db/models/query.py", line 787, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.6/site-packages/django/db/models/query.py", line 805, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/taiga/.virtualenvs/taiga/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1250, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/home/taiga/.virtualenvs/taiga/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1210, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1104, in build_lookup
    return final_lookup(lhs, rhs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.6/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.6/site-packages/django/db/models/lookups.py", line 74, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 966, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'HERE IS THE OLD EMAIL, WHICH I HAVE ALREADY CHANGED'

Any ideas?

**Comment by alexhermida** [comment]
@jsancheztheia seems that it is a bug when it's trying to make a relationship. It is using an email address instead of an integer.

**Comment by jsancheztheia** [comment]
Thanks for the answer @alexhermida 

Like I said, the email that is trying to use to make the relationship belongs to a user that is already deleted. Maybe when I deleted it, some transaction didn't end well, and the user is still there somewhere in the database.

I wonder if someone can guide me in order to find where is the user in the database and delete it, so I can export the project until the bug is solved.

Thanks in advance

**Comment by alexhermida** [comment]
@jsancheztheia we tried to reproduce in a working project changing project owner email address but I couldn't. The issue may refer to history activity in some user story or issue. We need more details so we can look into it to solve it. 
To unblock the export, you could try to remove from the table 'history_historyentry' some activity regarding that project and the old user. Take care of the query and the where clause.

**Comment by jsancheztheia** [comment]
Thanks for the answer @alexhermida

I looked in the 'history_historyentry' table but there's anything related to the user that is causing the problem. 

If you need further information, please let me know what else do you need to know in order to reproduce the error.

**Comment by alexhermida** [comment]
@jsancheztheia we just released a new version [4.2.6](https://github.com/taigaio/taiga-back/releases/tag/4.2.6) could you try to reproduce it with this new version?

**Comment by migonzalvar** [comment]
Should be solved at the moment. Please let us know if it is not.
