### ISSUE TITLE
No module named 'settings' error

### ISSUE THREAD

**Issue by hoangnkvti** [taigaio/taiga-back#1294]
**Do you want to request a *feature* or report a *bug*?**
 Bug

**What is the current behavior?**
When I run migrate command: `python manage.py migrate --noinput`
I got this error:

```
Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.7/site-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/home/taiga/.virtualenvs/taiga/lib/python3.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.7/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'settings'
```

I use Ubuntu 19.04 x64

Thanks a lot,

**Comment by alexhermida** [comment]
@hoangnkvti did you copy-paste the `~/taiga-back/settings/local.py.example` to `~/taiga-back/settings/local.py` and configured it? If it doesn't work,  Could you provide us which path and directory name are you using for taiga-back application?
