### ISSUE TITLE
Server application error when creating Project using API

### ISSUE THREAD

**Issue by tocloco** [taigaio/taiga-back#1302]
I am using the API to create a project, but getting a Server application error response.

I am sending in this to create the project:

{"name":"The Project","description":"Project description","is_epics_activated":true,"is_kanban_activated":true}

Here is the error log created when making the API call:

`ERROR:2019-05-14 08:41:21,134: Internal Server Error: /api/v1/projects
Traceback (most recent call last):
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/viewsets.py", line 106, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/views.py", line 460, in dispatch
    response = self.handle_exception(exc)
  File "/home/taiga/taiga-back/taiga/base/api/views.py", line 458, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/mixins.py", line 100, in create
    self.object = validator.save(force_insert=True)
  File "/home/taiga/taiga-back/taiga/base/api/serializers.py", line 1116, in save
    self.object = super().save(**kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/serializers.py", line 649, in save
    self.save_object(self.object, **kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/serializers.py", line 1134, in save_object
    obj.save(**kwargs)
  File "/home/taiga/taiga-back/taiga/projects/models.py", line 299, in save
    super().save(*args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/models/base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/models/base.py", line 848, in save_base
    update_fields=update_fields, raw=raw, using=using,
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/dispatch/dispatcher.py", line 193, in send
    for receiver in self._live_receivers(sender)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/dispatch/dispatcher.py", line 193, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/home/taiga/taiga-back/taiga/projects/signals.py", line 72, in project_post_save
    template.apply_to_project(instance)
  File "/home/taiga/taiga-back/taiga/projects/models.py", line 1104, in apply_to_project
    for us_duedate in self.us_duedates:
TypeError: 'NoneType' object is not iterable`

taiga-back is version 4.0.4

Any help much appreciated!

**Comment by tocloco** [comment]
Sorry, I just found an upgrade script that hadn't been run that caused the issue
