### ISSUE TITLE
test_emails command generating an exception with membership invitations

### ISSUE THREAD

**Issue by jwir3** [taigaio/taiga-back#1319]
I've recently been removing old projects and adding a few new ones, so it's possible this is a result of this, but when I run `python manage.py test_emails <my@email.address>`, I receive the following error message:
```
Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/var/www/foamfactory.io/taiga.foamfactory.io/taiga-back/taiga/base/management/commands/test_emails.py", line 63, in handle
    membership.invited_by = get_user_model().objects.all().order_by("?").first()
AttributeError: 'NoneType' object has no attribute 'invited_by'
```

If I comment out lines 62-68 of `taiga/base/management/test_emails.py`, this works as expected (although I don't get the membership invitation email, for obvious reasons).

As I mentioned, prior to cleaning up some old test projects, this command ran without a hitch, and I received a bunch of emails in my inbox. I was deleting the project(s) via the taiga tool, rather than the administrative interface, although I think there was one project I didn't notice in the tool itself that may have been removed via the admin interface called something like "Test Project" or something similar. Perhaps the removal of this project manually caused this?

Thoughts on what might be causing this?

**Comment by andreashaerter** [comment]
I can confirm this, completely fresh install:

```
$ python manage.py test_emails REDACTED@REDACTED.com
Trying import local.py settings...
WARNING	Property: Unknown Property name. [6:51: -webkit-text-size-adjust]
WARNING	Property: Unknown Property name. [6:82: -ms-text-size-adjust]
WARNING	Property: Unknown Property name. [7:23: mso-table-lspace]
WARNING	Property: Unknown Property name. [7:45: mso-table-rspace]
WARNING	Property: Unknown Property name. [8:17: -ms-interpolation-mode]
ERROR	Property: Invalid value for "CSS Level 2.1" property: 0.8rem 3rem [173:17: padding]
WARNING	Property: Unknown Property name. [240:55: -webkit-text-size-adjust]
WARNING	Property: Unknown Property name.
WARNING	Property: Unknown Property name. [1:1: -webkit-text-size-adjust]
WARNING	Property: Unknown Property name. [1:31: -ms-text-size-adjust]
WARNING	Property: Unknown Property name. [1:1: -webkit-text-size-adjust]
WARNING	Property: Unknown Property name. [1:31: -ms-text-size-adjust]
WARNING	Property: Unknown Property name. [1:1: -webkit-text-size-adjust]
WARNING	Property: Unknown Property name. [1:31: -ms-text-size-adjust]
WARNING	Property: Unknown Property name. [1:1: -webkit-text-size-adjust]
WARNING	Property: Unknown Property name. [1:31: -ms-text-size-adjust]
WARNING	Property: Unknown Property name. [1:1: -webkit-text-size-adjust]
WARNING	Property: Unknown Property name. [1:31: -ms-text-size-adjust]
WARNING	Property: Unknown Property name. [1:1: mso-table-lspace]
WARNING	Property: Unknown Property name. [1:20: mso-table-rspace]
WARNING	Property: Unknown Property name. [1:1: mso-table-lspace]
WARNING	Property: Unknown Property name. [1:20: mso-table-rspace]
WARNING	Property: Unknown Property name. [1:1: -ms-interpolation-mode]
WARNING	Property: Unknown Property name. [1:1: -ms-interpolation-mode]
Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/taiga/taiga-back/taiga/base/management/commands/test_emails.py", line 63, in handle
    membership.invited_by = get_user_model().objects.all().order_by("?").first()
AttributeError: 'NoneType' object has no attribute 'invited_by'
```

**Comment by andreashaerter** [comment]
Me again:
* I could reproduce the error on a clone with live data of an instance where deletion of users and projects happened.
* On a fresh install, after importing sample data via `python manage.py sample_data`, it works.

So I guess without further debugging, this error is indeed triggered by left-overs of deleted users referenced by ".invited_by".

**Comment by benzkji** [comment]
after upgrading, no more notifications are sent on my installation...and test_emails fails with said exception. confirmed.

**Comment by benzkji** [comment]
it sends an email anyway, though ;-)
