### ISSUE TITLE
Syntax error when migration

### ISSUE THREAD

**Issue by mzch** [taigaio/taiga-back#1328]
**Before adding an issue**
Please ensure that your issue is not already reported in our [issues list](https://tree.taiga.io/project/taiga/issues?order_by=-created_date).
If this issue was already reported, remember that you can upvote it to raise its importance.

**Do you want to request a *feature* or report a *bug*?**
*bug*
**What is the current behavior?**
Unable to install.
**If the current behavior is a bug, please provide the steps to reproduce.**
python manage.py migrate --noinput
**What is the expected behavior?**
done successfully.
**Is it happening in taiga.io or in your own instance?**
my own instance
**What browser/version are you using?**
Nop
**Are there any console errors *(Ctrl + F12)* in red?**
```
(taiga) taiga@n10:/srv/taiga-back$ python manage.py migrate --noinput
Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.7/site-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/home/taiga/.virtualenvs/taiga/lib/python3.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.7/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/srv/taiga-back/settings/__init__.py", line 22, in <module>
    from .celery import *
  File "/srv/taiga-back/settings/celery.py", line 19, in <module>
    from kombu import Queue
  File "<frozen importlib._bootstrap>", line 1032, in _handle_fromlist
  File "/home/taiga/.virtualenvs/taiga/lib/python3.7/site-packages/kombu/__init__.py", line 81, in __getattr__
    module = __import__(object_origins[name], None, None, [name])
  File "/home/taiga/.virtualenvs/taiga/lib/python3.7/site-packages/kombu/entity.py", line 6, in <module>
    from .abstract import MaybeChannelBound, Object
  File "/home/taiga/.virtualenvs/taiga/lib/python3.7/site-packages/kombu/abstract.py", line 6, in <module>
    from .connection import maybe_channel
  File "/home/taiga/.virtualenvs/taiga/lib/python3.7/site-packages/kombu/connection.py", line 893
    return self.transport.implements.async
                                         ^
SyntaxError: invalid syntax
```
Thanks for reporting!

**Comment by mzch** [comment]
I forgot some infos...

Python: 3.7.2
OS: Debian/GNU Linux 10 (Buster)

**Comment by alexhermida** [comment]
@mzch it seems related to https://github.com/celery/kombu/issues/841.

Current recommended version to run Taiga it's Python 3.6.x, not because of Python itself but because of the dependencies. If you use `pipenv` for the installation is pinned to Python 3.6.

**Comment by iwkse** [comment]
Please update kombu, https://github.com/celery/kombu/issues/841 the issues has been fixed more than a year ago. It's difficult to get python3.6 at least in Debian.
Cheers

**Comment by migonzalvar** [comment]
@iwkse kombu is now updated in the master branch
