### ISSUE TITLE
Trying import local.py settings... Trying import development.py settings...

### ISSUE THREAD

**Issue by programmerqn** [taigaio/taiga-back#1347]
Trying import local.py settings...
Trying import development.py settings...
Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.7/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/taiga/taiga-back/taiga/users/models.py", line 50, in <module>
    from . import services
  File "/home/taiga/taiga-back/taiga/users/services.py", line 45, in <module>
    from taiga.projects.notifications.services import get_projects_watched
  File "/home/taiga/taiga-back/taiga/projects/notifications/services.py", line 37, in <module>
    from taiga.projects.history.services import (make_key_from_model_object,
  File "/home/taiga/taiga-back/taiga/projects/history/services.py", line 51, in <module>
    from .freeze_impl import project_freezer
  File "/home/taiga/taiga-back/taiga/projects/history/freeze_impl.py", line 31, in <module>
    from taiga.projects.attachments.services import get_timeline_image_thumbnail_name
  File "/home/taiga/taiga-back/taiga/projects/attachments/services.py", line 18, in <module>
    from taiga.base.utils.thumbnails import get_thumbnail_url, get_thumbnail
  File "/home/taiga/taiga-back/taiga/base/utils/thumbnails.py", line 21, in <module>
    from psd_tools import PSDImage
  File "/home/taiga/.virtualenvs/taiga/lib/python3.7/site-packages/psd_tools/__init__.py", line 2, in <module>
    from .user_api import PSDImage, Layer, Group, BBox, Embedded
  File "/home/taiga/.virtualenvs/taiga/lib/python3.7/site-packages/psd_tools/user_api/__init__.py", line 4, in <module>
    from psd_tools.user_api.psd_image import PSDImage, Layer, Group, BBox
  File "/home/taiga/.virtualenvs/taiga/lib/python3.7/site-packages/psd_tools/user_api/psd_image.py", line 7, in <module>
    import psd_tools.reader
  File "/home/taiga/.virtualenvs/taiga/lib/python3.7/site-packages/psd_tools/reader/__init__.py", line 3, in <module>
    from .reader import parse
  File "/home/taiga/.virtualenvs/taiga/lib/python3.7/site-packages/psd_tools/reader/reader.py", line 8, in <module>
    import psd_tools.reader.layers
  File "/home/taiga/.virtualenvs/taiga/lib/python3.7/site-packages/psd_tools/reader/layers.py", line 17, in <module>
    LayerAndMaskData = pretty_namedtuple('LayerAndMaskData', 'layers global_mask_info tagged_blocks')
  File "/home/taiga/.virtualenvs/taiga/lib/python3.7/site-packages/psd_tools/debug.py", line 39, in pretty_namedtuple
    cls = namedtuple(typename, field_names, verbose=verbose)
TypeError: namedtuple() got an unexpected keyword argument 'verbose'

**Comment by migonzalvar** [comment]
It seems an issue related with Python 3.7 support of the required package psd-tools. Please, use python3.6 by now.
