### ISSUE TITLE
Syntax error when migrating 'NAME':

### ISSUE THREAD

**Issue by mfarmitage** [taigaio/taiga-back#1349]
Hopefully someone can help,

Using MAC Python 3.7 and Django and MYSQL i have followed all fix suggestions but whenever i try migrate i get the following error:

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/Users/michaelforrest/.virtualenvs/myvenv/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Users/michaelforrest/.virtualenvs/myvenv/lib/python3.7/site-packages/django/core/management/__init__.py", line 325, in execute
    settings.INSTALLED_APPS
  File "/Users/michaelforrest/.virtualenvs/myvenv/lib/python3.7/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/Users/michaelforrest/.virtualenvs/myvenv/lib/python3.7/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/Users/michaelforrest/.virtualenvs/myvenv/lib/python3.7/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/michaelforrest/django1/django1/settings.py", line 79
    'NAME': 'djangoProject'),
                           ^
SyntaxError: invalid syntax
(myvenv) Michaels-MacBook-Pro:django1 michaelforrest$ which python
/Users/michaelforrest/.virtualenvs/myvenv/bin/python
(myvenv) Michaels-MacBook-Pro:django1 michaelforrest$ python
Python 3.7.4 (v3.7.4:e09359112e, Jul  8 2019, 14:54:52) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

**Comment by benzkji** [comment]
you'll need to fix the syntax error in your settings.py, I guess?

**Comment by alexhermida** [comment]
@mfarmitage review your local.py settings as @benzkji you can check the documentation https://taigaio.github.io/taiga-doc/dist/setup-development.html#_setup_python_environment
