### ISSUE TITLE
smtplib.SMTPNotSupportedError: SMTP AUTH extension not supported by server.

### ISSUE THREAD

**Issue by danielzzz** [taigaio/taiga-back#1384]
**Before adding an issue**
Please ensure that your issue is not already reported in our [issues list](https://tree.taiga.io/project/taiga/issues?order_by=-created_date).
If this issue was already reported, remember that you can upvote it to raise its importance.

**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
cannot send invitation to users

**If the current behavior is a bug, please provide the steps to reproduce.**
add an user, send invitation

**What is the expected behavior?**
getting an email

**Is it happening in taiga.io or in your own instance?**
own

**What browser/version are you using?**
 chrome, latest

**Are there any console errors *(Ctrl + F12)* in red?**
no

when sending an invitation, I am getting the following error:
ERROR:2020-01-07 11:44:29,070: Internal Server Error: /api/v1/memberships/4/resend_invitation
Traceback (most recent call last):
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/viewsets.py", line 106, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/views.py", line 460, in dispatch
    response = self.handle_exception(exc)
  File "/home/taiga/taiga-back/taiga/base/api/views.py", line 458, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/taiga/taiga-back/taiga/projects/api.py", line 1020, in resend_invitation
    services.send_invitation(invitation=invitation)
  File "/home/taiga/taiga-back/taiga/projects/services/invitations.py", line 34, in send_invitation
    email.send()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/mail/message.py", line 348, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/mail/backends/smtp.py", line 104, in send_messages
    new_conn_created = self.open()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/mail/backends/smtp.py", line 71, in open
    self.connection.login(force_str(self.username), force_str(self.password))
  File "/usr/lib/python3.5/smtplib.py", line 696, in login
    "SMTP AUTH extension not supported by server.")
smtplib.SMTPNotSupportedErr

the smtp data tested and works fine.

please advice, thanks!
dan

**Comment by danielzzz** [comment]
I found a solution here:
https://tree.taiga.io/project/taiga/issue/5769

enabling tls in local.py solved the problem (even if the server is not using it)

**Comment by migonzalvar** [comment]
The terminology is confusing. Usually, the best config for email is to use port 587 (Submission), as formalized in RFC 6409 with `EMAIL_USE_TLS - True`.

```
EMAIL_PORT = 587
EMAIL_USE_TLS = True
```
