### ISSUE TITLE
Error creating issues in taiga-back 5.0.8

### ISSUE THREAD

**Issue by vikrantrathore** [taigaio/taiga-back#1408]
Error on self installed instance of taiga version 5.0.8 in Issues. When creating an issue getting a following error:

```
ERROR:2020-02-26 12:31:18,732: Internal Server Error: /api/v1/issues/474
Traceback (most recent call last):
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/taiga/projects/taiga-back/taiga/base/api/viewsets.py", line 106, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/taiga/projects/taiga-back/taiga/base/api/views.py", line 460, in dispatch
    response = self.handle_exception(exc)
  File "/home/taiga/projects/taiga-back/taiga/base/api/views.py", line 458, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/taiga/projects/taiga-back/taiga/base/api/mixins.py", line 204, in partial_update
    return self.update(request, *args, **kwargs)
  File "/home/taiga/projects/taiga-back/taiga/projects/issues/api.py", line 147, in update
    return super().update(request, *args, **kwargs)
  File "/home/taiga/projects/taiga-back/taiga/projects/notifications/mixins.py", line 117, in update
    old_mentions = self._get_old_mentions_in_field(obj, field_name)
  File "/home/taiga/projects/taiga-back/taiga/projects/notifications/mixins.py", line 209, in _get_old_mentions_in_field
    return services.get_mentions(obj, getattr(obj, field_name))
  File "/home/taiga/projects/taiga-back/taiga/projects/notifications/services.py", line 137, in get_mentions
    _, data = render_and_extract(project, text)
  File "/home/taiga/projects/taiga-back/taiga/mdrender/service.py", line 123, in render_and_extract
    result = bleach.clean(md.convert(text))
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/markdown/core.py", line 272, in convert
    newRoot = treeprocessor.run(root)
  File "/home/taiga/projects/taiga-back/taiga/mdrender/extensions/wikilinks.py", line 94, in run
    url = resolve("wiki", self.project.slug, href)
AttributeError: 'Issue' object has no attribute 'slug'
```

**Comment by migonzalvar** [comment]
Thank you for reporting. We will try to fix it soon.
