### ISSUE TITLE
Import Github project failed

### ISSUE THREAD

**Issue by Smilefounder** [taigaio/taiga-back#1425]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Import Github project with 500 error.
> https://taiga.mixcore.studio/taiga-back/api/v1/importers/github/list_users

**If the current behavior is a bug, please provide the steps to reproduce.**
Select Github repo from dropdown to import. Then the issue happens

**What is the expected behavior?**
Import successful without any errors.

**Is it happening in taiga.io or in your own instance?**
My own instance

**What browser/version are you using?**
MS Edge / Version 81.0.416.64 (Official build) (64-bit)

**Are there any console errors *(Ctrl + F12)* in red?**
![image](https://user-images.githubusercontent.com/3785721/80270362-621c3200-86e1-11ea-8ed2-02431fd2c28f.png)

Thanks for reporting!

**Comment by Smilefounder** [comment]
This is the log file
`App 1483842 output: /opt/passenger-5.3.7-9.el7.cloudlinux/src/helper-scripts/wsgi-loader.py:26: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
App 1483842 output:   import sys, os, io, re, imp, threading, signal, traceback, socket, select, struct, logging, errno
App 1483842 output: Trying import local.py settings...
App 1483842 output: 
App 1484059 output: /opt/passenger-5.3.7-9.el7.cloudlinux/src/helper-scripts/wsgi-loader.py:26: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
App 1484059 output:   import sys, os, io, re, imp, threading, signal, traceback, socket, select, struct, logging, errno
App 1484059 output: Trying import local.py settings...
App 1484059 output: 
App 1487179 output: /opt/passenger-5.3.7-9.el7.cloudlinux/src/helper-scripts/wsgi-loader.py:26: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
App 1487179 output:   import sys, os, io, re, imp, threading, signal, traceback, socket, select, struct, logging, errno
App 1487179 output: Trying import local.py settings...
App 1487179 output: 
App 1483842 output: ERROR:2020-04-25 09:06:29,104: Internal Server Error: /taiga-back/api/v1/importers/github/list_users
App 1483842 output: Traceback (most recent call last):
App 1483842 output:   File "/home/smilewa2/virtualenv/_sites/taiga.mixcore.studio/taiga-back/3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 41, in inner
App 1483842 output:     response = get_response(request)
App 1483842 output:   File "/home/smilewa2/virtualenv/_sites/taiga.mixcore.studio/taiga-back/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
App 1483842 output:     response = self._get_response(request)
App 1483842 output:   File "/home/smilewa2/virtualenv/_sites/taiga.mixcore.studio/taiga-back/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
App 1483842 output:     response = self.process_exception_by_middleware(e, request)
App 1483842 output:   File "/home/smilewa2/virtualenv/_sites/taiga.mixcore.studio/taiga-back/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
App 1483842 output:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
App 1483842 output:   File "/home/smilewa2/_sites/taiga.mixcore.studio/taiga-back/taiga/base/api/viewsets.py", line 106, in view
App 1483842 output:     return self.dispatch(request, *args, **kwargs)
App 1483842 output:   File "/home/smilewa2/virtualenv/_sites/taiga.mixcore.studio/taiga-back/3.7/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
App 1483842 output:     return view_func(*args, **kwargs)
App 1483842 output:   File "/home/smilewa2/_sites/taiga.mixcore.studio/taiga-back/taiga/base/api/views.py", line 460, in dispatch
App 1483842 output:     response = self.handle_exception(exc)
App 1483842 output:   File "/home/smilewa2/_sites/taiga.mixcore.studio/taiga-back/taiga/base/api/views.py", line 458, in dispatch
App 1483842 output:     response = handler(request, *args, **kwargs)
App 1483842 output:   File "/home/smilewa2/_sites/taiga.mixcore.studio/taiga-back/taiga/importers/github/api.py", line 47, in list_users
App 1483842 output:     users = importer.list_users(project_id)
App 1483842 output:   File "/home/smilewa2/_sites/taiga.mixcore.studio/taiga-back/taiga/importers/github/importer.py", line 106, in list_users
App 1483842 output:     collaborators = self._client.get("/repos/{}/collaborators".format(project_full_name))
App 1483842 output:   File "/home/smilewa2/_sites/taiga.mixcore.studio/taiga-back/taiga/importers/github/importer.py", line 70, in get
App 1483842 output:     raise Exception("Resource Unavailable: %s at %s" % (response.text, url), response)
App 1483842 output: Exception: ('Resource Unavailable: {"message":"Resource not accessible by integration","documentation_url":"https://developer.github.com/v3/repos/collaborators/#list-collaborators"} at https://api.github.com/repos/mixcore/mix.core/collaborators', <Response [403]>)
`

**Comment by Smilefounder** [comment]
Fixed by use OAuth Apps token of Github App token.
