### ISSUE TITLE
Current docker image is not running

### ISSUE THREAD

**Issue by christianlupus** [taigaio/taiga-back#1429]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
The docker container `taiga-back` is not able to start/migrate the database.
The frontend shows a ton of errors of various kinds in the network logs and starts always from scratch (introduction to taiga for new users).

<details><summary>Logs are here</summary>

```
taiga-back | Waiting for database to become ready...
taiga-back | trying to connect: host='db' dbname='taiga' user='postgres' password='password'...
taiga-back | Running database update...
taiga-back | Traceback (most recent call last):
taiga-back |   File "manage.py", line 29, in <module>
taiga-back |     execute_from_command_line(sys.argv)
taiga-back |   File "/usr/lib/python3.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
taiga-back |     utility.execute()
taiga-back |   File "/usr/lib/python3.7/site-packages/django/core/management/__init__.py", line 308, in execute
taiga-back |     settings.INSTALLED_APPS
taiga-back |   File "/usr/lib/python3.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
taiga-back |     self._setup(name)
taiga-back |   File "/usr/lib/python3.7/site-packages/django/conf/__init__.py", line 41, in _setup
taiga-back |     self._wrapped = Settings(settings_module)
taiga-back |   File "/usr/lib/python3.7/site-packages/django/conf/__init__.py", line 110, in __init__
taiga-back |     mod = importlib.import_module(self.SETTINGS_MODULE)
taiga-back |   File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
taiga-back |     return _bootstrap._gcd_import(name[level:], package, level)
taiga-back |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
taiga-back |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
taiga-back |   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
taiga-back |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
taiga-back |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
taiga-back |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
taiga-back |   File "/srv/taiga/back/settings/__init__.py", line 22, in <module>
taiga-back |     from .celery import *
taiga-back | ModuleNotFoundError: No module named 'settings.celery'
taiga-back | Traceback (most recent call last):
taiga-back |   File "manage.py", line 29, in <module>
taiga-back |     execute_from_command_line(sys.argv)
taiga-back |   File "/usr/lib/python3.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
taiga-back |     utility.execute()
taiga-back |   File "/usr/lib/python3.7/site-packages/django/core/management/__init__.py", line 308, in execute
taiga-back |     settings.INSTALLED_APPS
taiga-back |   File "/usr/lib/python3.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
taiga-back |     self._setup(name)
taiga-back |   File "/usr/lib/python3.7/site-packages/django/conf/__init__.py", line 41, in _setup
taiga-back |     self._wrapped = Settings(settings_module)
taiga-back |   File "/usr/lib/python3.7/site-packages/django/conf/__init__.py", line 110, in __init__
taiga-back |     mod = importlib.import_module(self.SETTINGS_MODULE)
taiga-back |   File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
taiga-back |     return _bootstrap._gcd_import(name[level:], package, level)
taiga-back |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
taiga-back |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
taiga-back |   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
taiga-back |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
taiga-back |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
taiga-back |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
taiga-back |   File "/srv/taiga/back/settings/__init__.py", line 22, in <module>
taiga-back |     from .celery import *
taiga-back | ModuleNotFoundError: No module named 'settings.celery'
taiga-back | Traceback (most recent call last):
taiga-back |   File "manage.py", line 29, in <module>
taiga-back |     execute_from_command_line(sys.argv)
taiga-back |   File "/usr/lib/python3.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
taiga-back |     utility.execute()
taiga-back |   File "/usr/lib/python3.7/site-packages/django/core/management/__init__.py", line 308, in execute
taiga-back |     settings.INSTALLED_APPS
taiga-back |   File "/usr/lib/python3.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
taiga-back |     self._setup(name)
taiga-back |   File "/usr/lib/python3.7/site-packages/django/conf/__init__.py", line 41, in _setup
taiga-back |     self._wrapped = Settings(settings_module)
taiga-back |   File "/usr/lib/python3.7/site-packages/django/conf/__init__.py", line 110, in __init__
taiga-back |     mod = importlib.import_module(self.SETTINGS_MODULE)
taiga-back |   File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
taiga-back |     return _bootstrap._gcd_import(name[level:], package, level)
taiga-back |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
taiga-back |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
taiga-back |   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
taiga-back |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
taiga-back |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
taiga-back |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
taiga-back |   File "/srv/taiga/back/settings/__init__.py", line 22, in <module>
taiga-back |     from .celery import *
taiga-back | ModuleNotFoundError: No module named 'settings.celery'
taiga-back | Installing cron jobs...
taiga-back | [2020-05-05 14:40:52 +0000] [14] [INFO] Starting gunicorn 19.9.0
taiga-back | [2020-05-05 14:40:52 +0000] [14] [INFO] Listening at: http://127.0.0.1:8000 (14)
taiga-back | [2020-05-05 14:40:52 +0000] [14] [INFO] Using worker: sync
taiga-back | [2020-05-05 14:40:52 +0000] [23] [INFO] Booting worker with pid: 23
taiga-back | [2020-05-05 14:40:52 +0000] [24] [INFO] Booting worker with pid: 24
taiga-back | [2020-05-05 14:40:52 +0000] [25] [INFO] Booting worker with pid: 25
taiga-back | Error: 
taiga-back | Unable to load celery application.
taiga-back | The module settings.celery was not found.
taiga-back | 
taiga-back | [2020-05-05 14:40:52 +0000] [26] [INFO] Booting worker with pid: 26
taiga-back | [2020-05-05 14:40:52 +0000] [23] [ERROR] Exception in worker process
taiga-back | Traceback (most recent call last):
taiga-back |   File "/srv/taiga/back/taiga/celery.py", line 28, in <module>
taiga-back |     from settings import celery_local as celery_settings
taiga-back |   File "/srv/taiga/back/settings/__init__.py", line 22, in <module>
taiga-back |     from .celery import *
taiga-back | ModuleNotFoundError: No module named 'settings.celery'
taiga-back | 
taiga-back | During handling of the above exception, another exception occurred:
taiga-back | 
taiga-back | Traceback (most recent call last):
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
taiga-back |     worker.init_process()
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
taiga-back |     self.load_wsgi()
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
taiga-back |     self.wsgi = self.app.wsgi()
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
taiga-back |     self.callable = self.load()
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
taiga-back |     return self.load_wsgiapp()
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
taiga-back |     return util.import_app(self.app_uri)
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
taiga-back |     __import__(module)
taiga-back |   File "/srv/taiga/back/taiga/__init__.py", line 19, in <module>
taiga-back |     from . import celery
taiga-back |   File "/srv/taiga/back/taiga/celery.py", line 30, in <module>
taiga-back |     from settings import celery as celery_settings
taiga-back |   File "/srv/taiga/back/settings/__init__.py", line 22, in <module>
taiga-back |     from .celery import *
taiga-back | ModuleNotFoundError: No module named 'settings.celery'
taiga-back | [2020-05-05 14:40:52 +0000] [23] [INFO] Worker exiting (pid: 23)
taiga-back | [2020-05-05 14:40:52 +0000] [24] [ERROR] Exception in worker process
taiga-back | Traceback (most recent call last):
taiga-back |   File "/srv/taiga/back/taiga/celery.py", line 28, in <module>
taiga-back |     from settings import celery_local as celery_settings
taiga-back |   File "/srv/taiga/back/settings/__init__.py", line 22, in <module>
taiga-back |     from .celery import *
taiga-back | ModuleNotFoundError: No module named 'settings.celery'
taiga-back | 
taiga-back | During handling of the above exception, another exception occurred:
taiga-back | 
taiga-back | Traceback (most recent call last):
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
taiga-back |     worker.init_process()
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
taiga-back |     self.load_wsgi()
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
taiga-back |     self.wsgi = self.app.wsgi()
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
taiga-back |     self.callable = self.load()
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
taiga-back |     return self.load_wsgiapp()
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
taiga-back |     return util.import_app(self.app_uri)
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
taiga-back |     __import__(module)
taiga-back |   File "/srv/taiga/back/taiga/__init__.py", line 19, in <module>
taiga-back |     from . import celery
taiga-back |   File "/srv/taiga/back/taiga/celery.py", line 30, in <module>
taiga-back |     from settings import celery as celery_settings
taiga-back |   File "/srv/taiga/back/settings/__init__.py", line 22, in <module>
taiga-back |     from .celery import *
taiga-back | ModuleNotFoundError: No module named 'settings.celery'
taiga-back | [2020-05-05 14:40:52 +0000] [24] [INFO] Worker exiting (pid: 24)
taiga-back | [2020-05-05 14:40:53 +0000] [25] [ERROR] Exception in worker process
taiga-back | Traceback (most recent call last):
taiga-back |   File "/srv/taiga/back/taiga/celery.py", line 28, in <module>
taiga-back |     from settings import celery_local as celery_settings
taiga-back |   File "/srv/taiga/back/settings/__init__.py", line 22, in <module>
taiga-back |     from .celery import *
taiga-back | ModuleNotFoundError: No module named 'settings.celery'
taiga-back | 
taiga-back | During handling of the above exception, another exception occurred:
taiga-back | 
taiga-back | Traceback (most recent call last):
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
taiga-back |     worker.init_process()
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
taiga-back |     self.load_wsgi()
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
taiga-back |     self.wsgi = self.app.wsgi()
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
taiga-back |     self.callable = self.load()
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
taiga-back |     return self.load_wsgiapp()
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
taiga-back |     return util.import_app(self.app_uri)
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
taiga-back |     __import__(module)
taiga-back |   File "/srv/taiga/back/taiga/__init__.py", line 19, in <module>
taiga-back |     from . import celery
taiga-back |   File "/srv/taiga/back/taiga/celery.py", line 30, in <module>
taiga-back |     from settings import celery as celery_settings
taiga-back |   File "/srv/taiga/back/settings/__init__.py", line 22, in <module>
taiga-back |     from .celery import *
taiga-back | ModuleNotFoundError: No module named 'settings.celery'
taiga-back | [2020-05-05 14:40:53 +0000] [25] [INFO] Worker exiting (pid: 25)
taiga-back | [2020-05-05 14:40:53 +0000] [26] [ERROR] Exception in worker process
taiga-back | Traceback (most recent call last):
taiga-back |   File "/srv/taiga/back/taiga/celery.py", line 28, in <module>
taiga-back |     from settings import celery_local as celery_settings
taiga-back |   File "/srv/taiga/back/settings/__init__.py", line 22, in <module>
taiga-back |     from .celery import *
taiga-back | ModuleNotFoundError: No module named 'settings.celery'
taiga-back | 
taiga-back | During handling of the above exception, another exception occurred:
taiga-back | 
taiga-back | Traceback (most recent call last):
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
taiga-back |     worker.init_process()
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
taiga-back |     self.load_wsgi()
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
taiga-back |     self.wsgi = self.app.wsgi()
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
taiga-back |     self.callable = self.load()
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
taiga-back |     return self.load_wsgiapp()
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
taiga-back |     return util.import_app(self.app_uri)
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
taiga-back |     __import__(module)
taiga-back |   File "/srv/taiga/back/taiga/__init__.py", line 19, in <module>
taiga-back |     from . import celery
taiga-back |   File "/srv/taiga/back/taiga/celery.py", line 30, in <module>
taiga-back |     from settings import celery as celery_settings
taiga-back |   File "/srv/taiga/back/settings/__init__.py", line 22, in <module>
taiga-back |     from .celery import *
taiga-back | ModuleNotFoundError: No module named 'settings.celery'
taiga-back | [2020-05-05 14:40:53 +0000] [26] [INFO] Worker exiting (pid: 26)
taiga-back | Traceback (most recent call last):
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/arbiter.py", line 210, in run
taiga-back |     self.sleep()
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/arbiter.py", line 360, in sleep
taiga-back |     ready = select.select([self.PIPE[0]], [], [], 1.0)
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/arbiter.py", line 245, in handle_chld
taiga-back |     self.reap_workers()
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
taiga-back |     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
taiga-back | gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
taiga-back | 
taiga-back | During handling of the above exception, another exception occurred:
taiga-back | 
taiga-back | Traceback (most recent call last):
taiga-back |   File "/usr/bin/gunicorn", line 10, in <module>
taiga-back |     sys.exit(run())
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 61, in run
taiga-back |     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/app/base.py", line 223, in run
taiga-back |     super(Application, self).run()
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/app/base.py", line 72, in run
taiga-back |     Arbiter(self).run()
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/arbiter.py", line 232, in run
taiga-back |     self.halt(reason=inst.reason, exit_status=inst.exit_status)
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/arbiter.py", line 345, in halt
taiga-back |     self.stop()
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/arbiter.py", line 393, in stop
taiga-back |     time.sleep(0.1)
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/arbiter.py", line 245, in handle_chld
taiga-back |     self.reap_workers()
taiga-back |   File "/usr/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
taiga-back |     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
taiga-back | gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
```

</details>

**If the current behavior is a bug, please provide the steps to reproduce.**
I had an older installation (image id `20bd37a345c0`) that was running successfully. I simply updated to the latest image (`adde26492803`). Upon recreation of the container, it did not start correctly.

**What is the expected behavior?**
The backend starts correctly and does a migration if needed.

**Is it happening in taiga.io or in your own instance?**
own instance

**What browser/version are you using?**
```
dockertaiga/back                        latest              adde26492803        4 weeks ago         217MB
dockertaiga/rabbit                      latest              b661b8e3c4d1        2 months ago        104MB
dockertaiga/proxy                       latest              4efdad935492        3 months ago        21.5MB
dockertaiga/back                        test                20bd37a345c0        3 months ago        218MB
dockertaiga/events                      latest              4f32daf27866        14 months ago       90.7MB
```

**Are there any console errors *(Ctrl + F12)* in red?**
The problem is purely on the backend, thus no reasonable error messages on the frontend. I can provide them if needed anyways.

**Comment by migonzalvar** [comment]
Docker is not officially supported by the Taiga development team.

it seems you are using the _non official_ project https://github.com/docker-taiga/taiga. Please, ask there.
