### ISSUE TITLE
Trello import fails.

### ISSUE THREAD

**Issue by Navneet-Suresh** [taigaio/taiga-back#1571]
## System INFO:

System: Ubuntu 20.04.1 LTS
Setup type: Production

Followed the [guide](https://taigaio.github.io/taiga-doc/dist/setup-production.html#_introduction) to upgrade to Taiga 6 from source.

Configured Trello import for Taiga using the [official guide](https://taigaio.github.io/taiga-doc/dist/importers.html).

## Expected Result:
Import successful.

## Current result:

```
Feb 03 15:11:51 pm gunicorn[17920]: ERROR:2021-02-03 15:11:48,639: Internal Server Error: /api/v1/importers/trello/list>
Feb 03 15:11:51 pm gunicorn[17920]: Traceback (most recent call last):
Feb 03 15:11:51 pm gunicorn[17920]:   File "/home/taiga/taiga-back/.venv/lib/python3.8/site-packages/django/core/handle>
Feb 03 15:11:51 pm gunicorn[17920]:     response = get_response(request)
Feb 03 15:11:51 pm gunicorn[17920]:   File "/home/taiga/taiga-back/.venv/lib/python3.8/site-packages/django/core/handle>
Feb 03 15:11:51 pm gunicorn[17920]:     response = self.process_exception_by_middleware(e, request)
Feb 03 15:11:51 pm gunicorn[17920]:   File "/home/taiga/taiga-back/.venv/lib/python3.8/site-packages/django/core/handle>
Feb 03 15:11:51 pm gunicorn[17920]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
Feb 03 15:11:51 pm gunicorn[17920]:   File "/home/taiga/taiga-back/taiga/base/api/viewsets.py", line 104, in view
Feb 03 15:11:51 pm gunicorn[17920]:     return self.dispatch(request, *args, **kwargs)
Feb 03 15:11:51 pm gunicorn[17920]:   File "/home/taiga/taiga-back/.venv/lib/python3.8/site-packages/django/views/decor>
Feb 03 15:11:51 pm gunicorn[17920]:     return view_func(*args, **kwargs)
Feb 03 15:11:51 pm gunicorn[17920]:   File "/home/taiga/taiga-back/taiga/base/api/views.py", line 458, in dispatch
Feb 03 15:11:51 pm gunicorn[17920]:     response = self.handle_exception(exc)
Feb 03 15:11:51 pm gunicorn[17920]:   File "/home/taiga/taiga-back/taiga/base/api/views.py", line 456, in dispatch
Feb 03 15:11:51 pm gunicorn[17920]:     response = handler(request, *args, **kwargs)
Feb 03 15:11:51 pm gunicorn[17920]:   File "/home/taiga/taiga-back/taiga/importers/trello/api.py", line 74, in list_pro>
Feb 03 15:11:51 pm gunicorn[17920]:     projects = importer.list_projects()
Feb 03 15:11:51 pm gunicorn[17920]:   File "/home/taiga/taiga-back/taiga/importers/trello/importer.py", line 114, in li>
Feb 03 15:11:51 pm gunicorn[17920]:     elif project['organization']['prefs']['permissionLevel'] == "private":
Feb 03 15:11:51 pm gunicorn[17920]: KeyError: 'prefs'

```

**Comment by yamila-moreno** [comment]
I cannot reproduce the behaviour. Has the trello project any special plugin?

**Comment by Navneet-Suresh** [comment]
> I cannot reproduce the behaviour. Has the trello project any special plugin?

One of the boards that I am part of is private, would it cause any issues?

**Comment by Navneet-Suresh** [comment]
Thanks! Will try it out when it's available.

**Comment by yamila-moreno** [comment]
The image is already available; don't forget to pull the image again.

**Comment by Navneet-Suresh** [comment]
Works as expected now. Thanks again for a quick fix.
