### ISSUE TITLE
installed apps problem

### ISSUE THREAD

**Issue by burtsevyg** [taigaio/taiga-back#1579]
Good day!

Trying update from taiga 5 to taiga 6:

If I add
`INSTALLED_APPS += ["taiga_contrib_ldap_auth_ext"]`
in config.py https://raw.githubusercontent.com/taigaio/taiga-back/master/docker/config.py
even without any custom changes. When I run:

`docker-compose up -d taiga-back`

I always get:
`ModuleNotFoundError: No module named 'taiga-contrib-ldap-auth-ext'`

Need your help.
Thank you!

**Comment by burtsevyg** [comment]
```
# docker logs -fn 1000 taiga-docker_taiga-back_1
Executing pending migrations
Traceback (most recent call last):
  File "manage.py", line 27, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/opt/venv/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/venv/lib/python3.7/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/opt/venv/lib/python3.7/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'taiga_contrib_ldap_auth_ext'
```

**Comment by yamila-moreno** [comment]
Hi @burtsevyg If I understand correctly:
- you are using docker-compose repository
- you are using a custom config in a bind mount volume
Is that correct?

If you want to use the ldap plugin, currently you need to build your own docker image, as the official image is only distributed with plugins maintained by Taiga. You can use the `docker/Dockerfile` in this repository and add the corresponding installation of the plugin ldap. Besides, you have to map the `config.json` file in the taiga-front service to add the configuration for the LDAP plugin.

Good luck!

**Comment by burtsevyg** [comment]
You understand correctly. Thank you very much!

**Comment by burtsevyg** [comment]
add 
`git+https://github.com/Monogramm/taiga-contrib-ldap-auth-ext.git@v0.4.4#egg=taiga-contrib-ldap-auth-ext&subdirectory=back`
to `https://raw.githubusercontent.com/taigaio/taiga-back/master/requirements-contribs.in`
