### ISSUE TITLE
Taiga on Ubuntu 20.04 ARM 64 Raspberry Pi 4  using Postgres 13 Database Install from Source

### ISSUE THREAD

**Issue by minozheros** [taigaio/taiga-back#1617]
I installed everything following your guide for the source install at https://docs.taiga.io/setup-production.html#_introduction and the install went without errors, I had to add the www-data user to the taiga group though to get the frontend to work.. 

But if I try to add a project it will add it, but it will not work properly..   the project will eventually be created but the frontend will get stuck at the creation page.. if you reload the whole page, it will be there though.. 

If i try to delete a project it is the same result.. i get this error message.. 

`2021/10/29 18:11:43 [error] 78882#78882: *15 upstream timed out (110: Unknown error) while reading response header from upstream, client: 192.168.1.44, server: taiga.portabledesktop.de, request: "DELETE /api/v1/projects/1 HTTP/2.0", upstream: "http://127.0.0.1:8001/api/v1/projects/1", host: "taiga.portabledesktop.de", referrer: "https://taiga.portabledesktop.de/project/mein-kanban/admin/project-profile/details" `

The project does not get deleted... 

I am not sure if postgres 13 could be the problem.. 
Any help would be appreciated.. 

Regards Klaus

**Comment by bameda** [comment]
Hi, @minozheros 

Just with that information is difficult to know where could be the problem. Try to check the logs (https://docs.taiga.io/setup-production.html#troubleshooting)  to see if you find more information about your problem.

**Comment by gibosky-voetranquilo** [comment]
@minozheros Hi. Do you mind telling how did you installed on raspberry. I'm tryong with Ubuntu Server and can get the taiga to get up. Thanks!

**Comment by minozheros** [comment]
> @minozheros Hi. Do you mind telling how did you installed on raspberry. I'm tryong with Ubuntu Server and can get the taiga to get up. Thanks!

Hi.. i simply followed the info given in the second part about installation from source

https://docs.taiga.io/setup-production.html#_introduction

**Comment by gibosky-voetranquilo** [comment]
@minozheros do you mind sharing your image with installed taiga? Would be extremly helpful for me and others that are getting problems installing it on raspberry pi. Thanks!

**Comment by hadrienlemaire** [comment]
Hi, I have the same issue.

I installed Taiga on a raspberry pi 4 with the official lite distribution and I followed the same instruction as the author. Just like him I can access the website but creation of project get stuck in an infinite loading. When I try to edit or create project/task/user from the admin site I get a `Server Error (500)`. It seems similar to this problem : https://groups.google.com/g/taigaio/c/tbN2O7WViqw/m/4psODLCpBAAJ.

From the different services I have noticed 2 errors. The first one occurs when I start the **taiga-async.service** deamon.

```
févr. 07 22:04:48 raspi celery[20805]: Trying again in 12.00 seconds... (6/100)
févr. 07 22:04:59 raspi celery[20919]: [2022-02-07 21:04:59,421: ERROR/Beat] beat: Connection error: failed to resolve broker hostname. Trying again in 14.0 seconds...
févr. 07 22:05:00 raspi celery[20805]: [2022-02-07 21:05:00,404: ERROR/MainProcess] consumer: Cannot connect to amqp://rabbitmquser:**@rabbitmq:5672/taiga: failed to resolve broker hostname.
févr. 07 22:05:00 raspi celery[20805]: Trying again in 14.00 seconds... (7/100)
févr. 07 22:05:13 raspi celery[20919]: [2022-02-07 21:05:13,488: ERROR/Beat] beat: Connection error: failed to resolve broker hostname. Trying again in 16.0 seconds...
févr. 07 22:05:14 raspi celery[20805]: [2022-02-07 21:05:14,527: ERROR/MainProcess] consumer: Cannot connect to amqp://rabbitmquser:**@rabbitmq:5672/taiga: failed to resolve broker hostname.
févr. 07 22:05:14 raspi celery[20805]: Trying again in 16.00 seconds... (8/100)
févr. 07 22:05:29 raspi celery[20919]: [2022-02-07 21:05:29,542: ERROR/Beat] beat: Connection error: failed to resolve broker hostname. Trying again in 18.0 seconds...
févr. 07 22:05:30 raspi celery[20805]: [2022-02-07 21:05:30,620: ERROR/MainProcess] consumer: Cannot connect to amqp://rabbitmquser:**@rabbitmq:5672/taiga: failed to resolve broker hostname.
févr. 07 22:05:30 raspi celery[20805]: Trying again in 18.00 seconds... (9/100)
```
The second when I get an 500 error in my browser, inside the **taiga.service** deamon.

```
févr. 07 22:05:27 raspi gunicorn[20819]:     backend.emit_event(message=json.dumps(data), routing_key=routing_key, channel=channel)
févr. 07 22:05:27 raspi gunicorn[20819]:   File "/home/taiga/taiga-back/taiga/events/backends/rabbitmq.py", line 47, in emit_event
févr. 07 22:05:27 raspi gunicorn[20819]:     connection.connect()
févr. 07 22:05:27 raspi gunicorn[20819]:   File "/home/taiga/taiga-back/.venv/lib/python3.9/site-packages/amqp/connection.py", line 323, in connect
févr. 07 22:05:27 raspi gunicorn[20819]:     self.transport.connect()
févr. 07 22:05:27 raspi gunicorn[20819]:   File "/home/taiga/taiga-back/.venv/lib/python3.9/site-packages/amqp/transport.py", line 113, in connect
févr. 07 22:05:27 raspi gunicorn[20819]:     self._connect(self.host, self.port, self.connect_timeout)
févr. 07 22:05:27 raspi gunicorn[20819]:   File "/home/taiga/taiga-back/.venv/lib/python3.9/site-packages/amqp/transport.py", line 181, in _connect
févr. 07 22:05:27 raspi gunicorn[20819]:     raise (e
févr. 07 22:05:27 raspi gunicorn[20819]: OSError: failed to resolve broker hostname
```
Nonetheless all services are still running.

Rabbit is running and have been setup following the instruction.
```
$ sudo rabbitmqctl list_user_permissions rabbitmquser
Listing permissions for user "rabbitmquser" ...
vhost	configure	write	read
taiga	.*	.*	.*
```

Here is a snippets of my ./taiga-back/settings/config.py file:
```
#########################################
## TAIGA ASYNC
#########################################
CELERY_ENABLED = os.getenv('CELERY_ENABLED', 'True') == 'True'

from kombu import Queue  # noqa

CELERY_BROKER_URL = "amqp://rabbitmquser:passwd@rabbitmq:5672/taiga"
CELERY_RESULT_BACKEND = None # for a general installation, we don't need to store the results
CELERY_ACCEPT_CONTENT = ['pickle', ]  # Values are 'pickle', 'json', 'msgpack' and 'yaml'
CELERY_TASK_SERIALIZER = "pickle"
CELERY_RESULT_SERIALIZER = "pickle"
CELERY_TIMEZONE = 'Europe/Paris'
CELERY_TASK_DEFAULT_QUEUE = 'tasks'
CELERY_QUEUES = (
    Queue('tasks', routing_key='task.#'),
    Queue('transient', routing_key='transient.#', delivery_mode=1)
)
CELERY_TASK_DEFAULT_EXCHANGE = 'tasks'
CELERY_TASK_DEFAULT_EXCHANGE_TYPE = 'topic'
CELERY_TASK_DEFAULT_ROUTING_KEY = 'task.default'
```

And here is the output of Django if I try to delete a task:
```
[07/Feb/2022 22:02:15] "POST /admin/tasks/task/ HTTP/1.0" 200 3867
ERROR:2022-02-07 22:02:16,563: Internal Server Error: /admin/tasks/task/
Traceback (most recent call last):
  File "/home/taiga/taiga-back/.venv/lib/python3.9/site-packages/amqp/transport.py", line 172, in _connect
    entries = socket.getaddrinfo(
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/taiga/taiga-back/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/taiga/taiga-back/.venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/taiga/taiga-back/.venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/taiga/taiga-back/.venv/lib/python3.9/site-packages/django/contrib/admin/options.py", line 606, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/taiga/taiga-back/.venv/lib/python3.9/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/taiga/taiga-back/.venv/lib/python3.9/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/taiga/taiga-back/.venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "/home/taiga/taiga-back/.venv/lib/python3.9/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/taiga/taiga-back/.venv/lib/python3.9/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/taiga/taiga-back/.venv/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1727, in changelist_view
    response = self.response_action(request, queryset=cl.get_queryset(request))
  File "/home/taiga/taiga-back/.venv/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1397, in response_action
    response = func(self, request, queryset)
  File "/home/taiga/taiga-back/.venv/lib/python3.9/site-packages/django/contrib/admin/actions.py", line 40, in delete_selected
    modeladmin.delete_queryset(request, queryset)
  File "/home/taiga/taiga-back/.venv/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1098, in delete_queryset
    queryset.delete()
  File "/home/taiga/taiga-back/.venv/lib/python3.9/site-packages/django/db/models/query.py", line 711, in delete
    deleted, _rows_count = collector.delete()
  File "/home/taiga/taiga-back/.venv/lib/python3.9/site-packages/django/db/models/deletion.py", line 317, in delete
    signals.post_delete.send(
  File "/home/taiga/taiga-back/.venv/lib/python3.9/site-packages/django/db/transaction.py", line 284, in __exit__
    connection.set_autocommit(True)
  File "/home/taiga/taiga-back/.venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 410, in set_autocommit
    self.run_and_clear_commit_hooks()
  File "/home/taiga/taiga-back/.venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 636, in run_and_clear_commit_hooks
    func()
  File "/home/taiga/taiga-back/taiga/events/events.py", line 35, in backend_emit_event
    backend.emit_event(message=json.dumps(data), routing_key=routing_key, channel=channel)
  File "/home/taiga/taiga-back/taiga/events/backends/rabbitmq.py", line 47, in emit_event
    connection.connect()
  File "/home/taiga/taiga-back/.venv/lib/python3.9/site-packages/amqp/connection.py", line 323, in connect
    self.transport.connect()
  File "/home/taiga/taiga-back/.venv/lib/python3.9/site-packages/amqp/transport.py", line 113, in connect
    self._connect(self.host, self.port, self.connect_timeout)
  File "/home/taiga/taiga-back/.venv/lib/python3.9/site-packages/amqp/transport.py", line 181, in _connect
    raise (e
OSError: failed to resolve broker hostname
[07/Feb/2022 22:02:16] "POST /admin/tasks/task/ HTTP/1.0" 500 27
```

Thanks!

**Comment by hadrienlemaire** [comment]
I had a similar issue, 

I installed Taiga on a raspberry pi 4 with the official lite distribution and I followed the same instruction as the author. Just like him I could access the website but some part of pages were missing and creation of project get stuck in an infinite loading. When I tried to edit or create project/task/user from the admin site I got a `Server Error (500)`. The problem looked similar to [this one](https://groups.google.com/g/taigaio/c/tbN2O7WViqw/m/4psODLCpBAAJ) an my logs were similar to this problem #1248.

The solution, for me, was just to update the host of the rabbit’s service running machine inside the config files. Because rabbit and taiga are set on the same machine I just had to set it to `localhost`. It might seems obvious, but a newbie like me just did not pay attention. A short description of this line in the documentation might be helpful to others. 


In **taiga-events/.env**:
```RABBITMQ_URL="amqp://rabbitmquser:rabbitmqpassword@rabbitmqhost:5672/taiga"```
to
```RABBITMQ_URL="amqp://rabbitmquser:rabbitmqpassword@localhost:5672/taiga"```

And in  in **taiga-back/settings/config.py**:
```
EVENTS_PUSH_BACKEND_OPTIONS = {
    "url": "amqp://rabbitmquser:rabbitmqpassword@rabbitmqhost:5672/taiga"
}
CELERY_BROKER_URL = "amqp://rabbitmquser:rabbitmqpassword@rabbitmq:5672/taiga"
```
to
```
EVENTS_PUSH_BACKEND_OPTIONS = {
    "url": "amqp://rabbitmquser:rabbitmqpassword@localhost:5672/taiga"
}
CELERY_BROKER_URL = "amqp://rabbitmquser:rabbitmqpassword@localhost:5672/taiga"
```

However, after my research I have one question. Is it useful to change the username and password of the rabbitmq user?

Thanks!

**Comment by Xaviju** [comment]
Hi there! 

Do you know that we created [Taiga Community](https://community.taiga.io/c/technical/8) for questions like yours? Please, check there; maybe another user has already asked something similar. If not, create your own. There are people there willing to help, members of the Taiga team members and other users.

To simplify the process, we will systematically close all issues that are general support questions and redirect people to Taiga Community.
