### ISSUE TITLE
Invalid ASCII Jesús Espino's name 

### ISSUE THREAD

**Issue by ravensnowbird** [taigaio/taiga-back#243]
root@cloud-server-09:/home/deployer/taiga-back# python manage.py migrate --noinput
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 345, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 46, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 42, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 94, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/deployer/taiga-back/settings/__init__.py", line 2
SyntaxError: Non-ASCII character '\xc3' in file /home/deployer/taiga-back/settings/__init__.py on line 2, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

This line is on Line 2
# Copyright (C) 2014 Jesús Espino <jespinog@gmail.com>
# Copyright (C) 2014 David Barragán <bameda@dbarragan.com>

**Comment by superalex** [comment]
Hello @ravensnowbird 
It seems you are using python2, out of a virtualenv and with a root user. 

Taiga needs python 3 for working,  if you follow our documentation steps you will see that when creating the virtual env:
```
mkvirtualenv -p /usr/bin/python3.4 taiga
```

Regards,
