### ISSUE TITLE
Gunicorn fail to start

### ISSUE THREAD

**Issue by TiteiKo** [taigaio/taiga-back#282]
Hello,

I've encountered several problems with Taiga today, here's a little history : 

I've updated to the latest stable version, as explained here => http://taigaio.github.io/taiga-doc/dist/setup-production.html#faq-maintain-update . For info, during the process, I've encounter a nice warning : 
```
Your models have changes that are not yet reflected in a migration, and so won't be applied.
Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
```
Being a little bit (too?) cautious, I didn't dare to it.

The we had some issues and looking at the logs I came to this issue : https://github.com/taigaio/taiga-back/issues/272 
Changed the postgresql engine, restarted taiga and...

Gunicorn failed to start

Traceback

```
Traceback (most recent call last):
  File "/usr/local/bin/gunicorn", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 74, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 185, in run
    super(Application, self).run()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 71, in run
    Arbiter(self).run()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 169, in run
    self.manage_workers()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 477, in manage_workers
    self.spawn_workers()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 542, in spawn_workers
    time.sleep(0.1 * random.random())
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 209, in handle_chld
    self.reap_workers()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 459, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
```

But! Reverting the changes on the settings/local.py does not give me back my buggy-taiga

When running python manage.py runserver : 
```
Trying import local.py settings...
Monkey patching...
WARNING: Using backend without django-transaction-hooks support, auto delete files will not work.
Trying import local.py settings...
Monkey patching...
WARNING: Using backend without django-transaction-hooks support, auto delete files will not work.
Performing system checks...

System check identified no issues (0 silenced).
March 17, 2015 - 16:45:16
Django version 1.7.6, using settings 'settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
```
A curl on  http://localhost:8000/api/v1/ does respond

I'm not familiar with the python/django stack and the gunicorn error is really not self explaining, so I'm a little bit lost here...

Any ideas? (and yes, I hope the answer is just "listen when your console tells you to run some commands!")

**Comment by superalex** [comment]
Hello @TiteiKo,

Did you try to set in your local.py the ENGINE to transaction_hooks.backends and execute "python manage.py runserver" again to see the output?

Could you execute again the "Backend application" updating points one by one to check if there is any error?

´´´
cd ~/taiga-back
git checkout stable
workon taiga
git pull
pip install --upgrade -r requirements.txt
python manage.py migrate --noinput
python manage.py collectstatic --noinput
circusctl reload taiga
´´´

If the migrations message is still showing, could you execute the "python manage.py makemigrations" (not the python manage.py migrate) paste here the generated file and then remove it locally?

Regards!,

**Comment by TiteiKo** [comment]
Hello @superalex 

Thanks for taking time to answer to me

So, the message still poped, here's the generated migrations : 

```
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easy_thumbnails', '0002_thumbnaildimensions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='source',
            field=models.ForeignKey(related_name='thumbnails', to='easy_thumbnails.Source'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='thumbnaildimensions',
            name='thumbnail',
            field=models.OneToOneField(related_name='dimensions', to='easy_thumbnails.Thumbnail'),
            preserve_default=True,
        ),
    ]
```

I did some digging yesterday, I think the problem might be with the circus env (thus with the server and not the app), as launching gunicorn outside circus does work (without errors, as the db engine is set to the non django one) but haven't pinpointed the problem yet...

**Comment by superalex** [comment]
You are welcome @TiteiKo,

easy_thumbnails is an external app, you can generate the migration again and migrate the data with "python manage migrate"

Could you show us your circus config file to check what could be happening?

Regards,

**Comment by TiteiKo** [comment]
Ok, migration applied

I added some debugging output to the gunicorn logs : 

```
[watcher:taiga]
working_dir = /home/dev/taiga-back
cmd = gunicorn
args = -w 3 -t 60 --pythonpath=. --debug --log-level debug --preload -b 127.0.0.1:8001 taiga.wsgi
uid = dev
numprocesses = 1
autostart = true
send_hup = true
stdout_stream.class = FileStream
stdout_stream.filename = /home/dev/logs/gunicorn.stdout.log
stdout_stream.max_bytes = 10485760
stdout_stream.backup_count = 4
stderr_stream.class = FileStream
stderr_stream.filename = /home/dev/logs/gunicorn.stderr.log
stderr_stream.max_bytes = 10485760
stderr_stream.backup_count = 4

[env:taiga]
PATH=$PATH:/home/dev/.virtualenvs/taiga/bin
TERM=rxvt-256color
SHELL=/bin/bash
USER=dev
LANG=en_US.UTF-8
HOME=/home/dev
PYTHONPATH=/home/dev/.virtualenvs/taiga/lib/python3.4/site-packages
```

More outspoken gunicorn error : 

```
Traceback (most recent call last):
  File "/usr/local/bin/gunicorn", line 11, in <module>
    sys.exit(run())
  File "/home/dev/.virtualenvs/taiga/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/home/dev/.virtualenvs/taiga/lib/python3.4/site-packages/gunicorn/app/base.py", line 185, in run
    super(Application, self).run()
  File "/home/dev/.virtualenvs/taiga/lib/python3.4/site-packages/gunicorn/app/base.py", line 71, in run
    Arbiter(self).run()
  File "/home/dev/.virtualenvs/taiga/lib/python3.4/site-packages/gunicorn/arbiter.py", line 57, in __init__
    self.setup(app)
  File "/home/dev/.virtualenvs/taiga/lib/python3.4/site-packages/gunicorn/arbiter.py", line 113, in setup
    self.app.wsgi()
  File "/home/dev/.virtualenvs/taiga/lib/python3.4/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/home/dev/.virtualenvs/taiga/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/dev/.virtualenvs/taiga/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/dev/.virtualenvs/taiga/lib/python3.4/site-packages/gunicorn/util.py", line 356, in import_app
    __import__(module)
  File "/home/dev/taiga-back/taiga/__init__.py", line 2
SyntaxError: Non-ASCII character '\xc3' in file /home/dev/taiga-back/taiga/__init__.py on line 2, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
```

It seems like gunicorn tries to use python2 and not python3 :/

**Comment by superalex** [comment]
Exactly, and it should be using python3  

Could you update your circus file to:

```
[env:taiga]
PATH=/home/dev/.virtualenvs/taiga/bin:$PATH
TERM=rxvt-256color
SHELL=/bin/bash
USER=dev
LANG=en_US.UTF-8
HOME=/home/dev
PYTHONPATH=/home/dev/.virtualenvs/taiga/lib/python3.4/site-packages
```

And then:

```
circusctl reloadconfig
circusctl reload taiga
```

**Comment by TiteiKo** [comment]
And it works :)
That was tricky, nice catch

Again, thanks a lot !

**Comment by superalex** [comment]
Great!, 

I updated that in taiga-doc so it doesn't happen more :)
