### ISSUE TITLE
Migrate command not working

### ISSUE THREAD

**Issue by subramanyamVemu** [taigaio/taiga-back#303]
After I clone and run the command migrate I get the following error

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/amtex/management/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/amtex/management/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 303, in execute
    settings.INSTALLED_APPS
  File "/home/amtex/management/env/local/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/home/amtex/management/env/local/lib/python2.7/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/amtex/management/env/local/lib/python2.7/site-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/amtex/management/taiga-back/settings/__init__.py", line 2
SyntaxError: Non-ASCII character '\xc3' in file /home/amtex/management/taiga-back/settings/__init__.py on line 2, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

**Comment by bameda** [comment]
This is because you are using python 2.7 and **Taiga only runs with python 3.4+**

You need to create a env with this version, follow the documentation at http://taigaio.github.io/taiga-doc/dist/

Regards.
