### ISSUE TITLE
Polish chars in user story title.

### ISSUE THREAD

**Issue by kacpersaw** [taigaio/taiga-back#305]
Hi,
When I create user story with polish chars(ą,ę,ć,ś,ź,ó,ł,ż) than I can't assign member to user story.
i.e It assign on the frontend but when I refresh page that assign disappear.

**Comment by superalex** [comment]
Hello @kacpersaw,

I'm trying to reproduce your issue but I can't. Is it failing in your own instance or in tree.taiga.io?. If it's failing in tree.taiga.io, could you please tell us the url of the user story and the user you are trying to assign?

Regards,

**Comment by kacpersaw** [comment]
It's on my own instance

**Comment by superalex** [comment]
Taiga instance is working properly with polish chars, could you check your log files to see if there is any error?. They will be located under ~/logs

**Comment by kacpersaw** [comment]
I don't have access right now. I will check logs in 10 hours.

**Comment by superalex** [comment]
Ok!

**Comment by kacpersaw** [comment]
@superalex 
Okay, I think I found error :)

```
ERROR:2015-04-19 16:40:34,330: Internal Server Error: /api/v1/userstories/7
Traceback (most recent call last):
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/viewsets.py", line 81, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/views.py", line 418, in dispatch
    response = self.handle_exception(exc)
  File "/home/taiga/taiga-back/taiga/base/api/views.py", line 415, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/mixins.py", line 171, in partial_update
    return self.update(request, *args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/transaction.py", line 394, in inner
    return func(*args, **kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/mixins.py", line 166, in update
    self.post_save(self.object, created=False)
  File "/home/taiga/taiga-back/taiga/projects/userstories/api.py", line 97, in post_save
    super().post_save(obj, created)
  File "/home/taiga/taiga-back/taiga/projects/occ/mixins.py", line 81, in post_save
    super().post_save(obj, created)
  File "/home/taiga/taiga-back/taiga/projects/history/mixins.py", line 71, in post_save
    super().post_save(obj, created=created)
  File "/home/taiga/taiga-back/taiga/projects/notifications/mixins.py", line 68, in post_save
    self.send_notifications(obj)
  File "/home/taiga/taiga-back/taiga/projects/notifications/mixins.py", line 65, in send_notifications
    services.send_notifications(obj, history=history)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/transaction.py", line 394, in inner
    return func(*args, **kwargs)
  File "/home/taiga/taiga-back/taiga/projects/notifications/services.py", line 238, in send_notifications
    send_sync_notifications(notification.id)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/transaction.py", line 394, in inner
    return func(*args, **kwargs)
  File "/home/taiga/taiga-back/taiga/projects/notifications/services.py", line 272, in send_sync_notifications
    email.send(user.email, context)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/djmail/template_mail.py", line 150, in send
    return email.send()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/mail/message.py", line 286, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/mail/backends/console.py", line 36, in send_messages
    self.write_message(message)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/mail/backends/console.py", line 23, in write_message
    self.stream.write('%s\n' % msg_data)
UnicodeEncodeError: 'ascii' codec can't encode character '\u0119' in position 588: ordinal not in range(128)
```

Thanks for help!

**Comment by superalex** [comment]
Could you check your locale system settings?

A similar problem was solved here -> https://github.com/taigaio/taiga-back/issues/298#issuecomment-89931569

Another option could be setting LANG in the /etc/init/circus.conf.

Regards,

**Comment by kacpersaw** [comment]
That's helped, thanks ;)

**Comment by superalex** [comment]
Great! :+1:
