### ISSUE TITLE
User story statuses require "is_archived" property in project templates

### ISSUE THREAD

**Issue by artlepool** [taigaio/taiga-back#313]
I created a project in the Taiga UI (v1.6 on-premise deployment), customised it to the way I wanted it (ie. added new states, new roles, etc), and then used the API to create a template from it using [http://taigaio.github.io/taiga-doc/dist/api.html#projects-create-template](http://taigaio.github.io/taiga-doc/dist/api.html#projects-create-template).
The generated template is as per the example given in the API documentation: [http://taigaio.github.io/taiga-doc/dist/api.html#project-templates-create](http://taigaio.github.io/taiga-doc/dist/api.html#project-templates-create)

Then through the UI I tried to create a project using my new template.  I choose the template, click Next, enter a project Name and Description then click the Create button.   
I'm left with a blank screen (with the forest background image) and no error message.
Looking in the Developer Tools in the browser, I see a 
```
{"error": "Server application error"}
```
response from the "projects" api call.

In the gunicorn.stderr.log on the server, I see the following:

```
ERROR:2015-04-24 13:22:53,311: Internal Server Error: /api/v1/projects
Traceback (most recent call last):
  File "/home/taiga/taiga-back/taiga/lib/python3.4/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/viewsets.py", line 81, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/taiga/taiga-back/taiga/lib/python3.4/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/views.py", line 418, in dispatch
    response = self.handle_exception(exc)
  File "/home/taiga/taiga-back/taiga/base/api/views.py", line 415, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/mixins.py", line 71, in create
    self.object = serializer.save(force_insert=True)
  File "/home/taiga/taiga-back/taiga/base/serializers.py", line 155, in save
    self.object = super(serializers.ModelSerializer, self).save(**kwargs)
  File "/home/taiga/taiga-back/taiga/lib/python3.4/site-packages/rest_framework/serializers.py", line 596, in save
    self.save_object(self.object, **kwargs)
  File "/home/taiga/taiga-back/taiga/lib/python3.4/site-packages/rest_framework/serializers.py", line 991, in save_object
    obj.save(**kwargs)
  File "/home/taiga/taiga-back/taiga/projects/models.py", line 211, in save
    super().save(*args, **kwargs)
  File "/home/taiga/taiga-back/taiga/lib/python3.4/site-packages/django/db/models/base.py", line 589, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/taiga/taiga-back/taiga/lib/python3.4/site-packages/django/db/models/base.py", line 626, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/home/taiga/taiga-back/taiga/lib/python3.4/site-packages/django/dispatch/dispatcher.py", line 198, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/taiga/taiga-back/taiga/projects/signals.py", line 79, in project_post_save
    template.apply_to_project(instance)
  File "/home/taiga/taiga-back/taiga/projects/models.py", line 714, in apply_to_project
    is_archived=us_status["is_archived"],
KeyError: 'is_archived'
```

If I add the "is_archived" property manually to the project template, and create this new template in Taiga via the API, I can then create projects using this new template without error (both through the UI and API)

So, it seems that "is_archived" is a required property for user story statuses on project templates when creating new projects based on a template.  Therefore I would say that either the project template generated by the Create Template API call needs to include the "is_archived" property, or "is_archived" should not be mandatory when creating a project from a template.

**Comment by superalex** [comment]
Thank you very much for reporting @artlepool, we will try to solve it as soon as posible!

**Comment by superalex** [comment]
It should be solved here -> https://github.com/taigaio/taiga-back/pull/316
