### ISSUE TITLE
user account creation from invitations fails 

### ISSUE THREAD

**Issue by michaeldye** [taigaio/taiga-back#358]
I am running stable 1.7 and have encountered errors with registering private users. Invitations are sent and the token is written to the membership table, but users can't redeem their invitations b/c of a constraint on the 'project_id' field on the 'timeline_timeline' table:

```
psycopg2.IntegrityError: null value in column "project_id" violates not-null constraint
DETAIL:  Failing row contains (2950, 158, user:158, users.user.create, null, {"user": {"id": 158}}, 3, 2015-06-18 20:54:13.521675+00, 3).

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/taiga-back/taiga/users/models.py", line 164, in save
    super().save(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/db/models/base.py", line 589, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.4/dist-packages/django/db/models/base.py", line 626, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/usr/local/lib/python3.4/dist-packages/django/dispatch/dispatcher.py", line 198, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/taiga-back/taiga/timeline/signals.py", line 132, in create_user_push_to_timeline
    _push_to_timelines(project, user, user, "create")
  File "/taiga-back/taiga/timeline/signals.py", line 46, in _push_to_timelines
    extra_data=extra_data)
  File "/taiga-back/taiga/timeline/signals.py", line 33, in _push_to_timeline
    push_to_timeline(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/celery/local.py", line 167, in <lambda>
    __call__ = lambda x, *a, **kw: x._get_current_object()(*a, **kw)
  File "/usr/local/lib/python3.4/dist-packages/celery/app/task.py", line 420, in __call__
    return self.run(*args, **kwargs)
...
  File "/usr/local/lib/python3.4/dist-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.4/dist-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python3.4/dist-packages/django/utils/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.4/dist-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
```
```
STATEMENT:  INSERT INTO "timeline_timeline" ("content_type_id", "object_id", "namespace", "event_type", "project_id", "data", "data_content_type_id", "created") VALUES (3, 158, 'user:158', 'users.user.create', NULL, '{"user": {"id": 158}}', 3, '2015-06-18 20:54:13.521675+00:00') RETURNING "timeline_timeline"."id"
```

**Comment by superalex** [comment]
Hello @michaeldye 

It sounds like your database isn't synchronized with your models, did you update your instance recently?. Could you try to execute a "python manage.py migrate" from your taiga-back folder?

**Comment by superalex** [comment]
Hello @michaeldye, any more info about this?

**Comment by superalex** [comment]
I'm closing this one and reopen if needed.
