### ISSUE TITLE
Problem with ASCII

### ISSUE THREAD

**Issue by michelwilhelm** [taigaio/taiga-back#376]
When i run "python manage.py migrate --noinput" appears this error on terminal:

"Non-ASCII character '\xc3' in file"

RAW OUTPUT:
```bash
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/michel/.virtualenvs/taiga/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/michel/.virtualenvs/taiga/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    settings.INSTALLED_APPS
  File "/home/michel/.virtualenvs/taiga/local/lib/python2.7/site-packages/django/conf/__init__.py", line 46, in __getattr__
    self._setup(name)
  File "/home/michel/.virtualenvs/taiga/local/lib/python2.7/site-packages/django/conf/__init__.py", line 42, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/michel/.virtualenvs/taiga/local/lib/python2.7/site-packages/django/conf/__init__.py", line 94, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/michel/taiga-back/settings/__init__.py", line 2
SyntaxError: Non-ASCII character '\xc3' in file /home/michel/taiga-back/settings/__init__.py on line 2, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
```
Putting # -*- coding: utf-8 -*- at the top of every file works for me.

**Comment by jespino** [comment]
Hi @michelwilhelm,

You are using python 2.7 and Taiga only runs on python>=3.4.
