### ISSUE TITLE
Celery Import Issue

### ISSUE THREAD

**Issue by amankumarjain** [taigaio/taiga-back#394]
Trying import local.py settings...
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/codersbyte/projects/taiga-back/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/codersbyte/projects/taiga-back/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/home/codersbyte/projects/taiga-back/local/lib/python2.7/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/codersbyte/projects/taiga-back/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/codersbyte/projects/taiga-back/local/lib/python2.7/site-packages/django/apps/config.py", line 116, in create
    mod = import_module(mod_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/codersbyte/projects/taiga-back/taiga/__init__.py", line 17, in <module>
    from . import celery
  File "/home/codersbyte/projects/taiga-back/taiga/celery.py", line 19, in <module>
    from celery import Celery
ImportError: cannot import name Celery

**Comment by bameda** [comment]
I hope your server or virtual machine has at last 756 MB of RAM. If the answer is yes try this:

```
cd taiga-back
workon taiga
pip install -r requirements.txt
```

**Comment by amankumarjain** [comment]
Hey after running server, when i call get request to api/v1 it says no page found. 
I checked routers.py file every thing there is good. neither /admin is working.

**Comment by amankumarjain** [comment]
uckkfeb22260.codersbyte.koding.io:8000/api/v1 THis is url where django taiga-back is running

**Comment by bameda** [comment]
Try with ```uckkfeb22260.codersbyte.koding.io:8000/api/v1/projects```

**Comment by amankumarjain** [comment]
Yeah it works ut a/c to doc /v1/api allow have to work and /admin isnot working too

**Comment by bameda** [comment]
Sorry but I don't understand.

**Comment by amankumarjain** [comment]
Thanks man its working fine.

**Comment by bameda** [comment]
I'm glad :smile:, you are welcome.
