### ISSUE TITLE
relation "projects_userstorycustomattribute" does not exist

### ISSUE THREAD

**Issue by ipedrazas** [taigaio/taiga-back#403]
```
-> Generate sample data
Trying import local.py settings...
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: relation "projects_userstorycustomattribute" does not exist
LINE 1: INSERT INTO "projects_userstorycustomattribute" ("name", "de...
                    ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.4/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.4/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.4/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python3.4/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.4/site-packages/django/db/transaction.py", line 394, in inner
    return func(*args, **kwargs)
  File "/taiga/taiga/projects/management/commands/sample_data.py", line 160, in handle
    order=i)
  File "/usr/local/lib/python3.4/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/django/db/models/query.py", line 372, in create
    obj.save(force_insert=True, using=self.db)
  File "/taiga/taiga/projects/custom_attributes/models.py", line 61, in save
    return super().save(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/django/db/models/base.py", line 589, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.4/site-packages/django/db/models/base.py", line 617, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python3.4/site-packages/django/db/models/base.py", line 698, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python3.4/site-packages/django/db/models/base.py", line 731, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python3.4/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/django/db/models/query.py", line 921, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 921, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.4/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.4/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python3.4/site-packages/django/utils/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.4/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "projects_userstorycustomattribute" does not exist
LINE 1: INSERT INTO "projects_userstorycustomattribute" ("name", "de...
                    ^

-> Rebuilding timeline
Trying import local.py settings...

```

**Comment by superalex** [comment]
Hello @ipedrazas,

It sounds like taiga database isn't synchronized with the models.py files, what were you trying to do when this error happened?, did you execute before a "python manage.py migrate"?

**Comment by bameda** [comment]
According to the output he's regenerating the DB (with the script regenerate.sh).

Try to execute the script manually, 

'''
dropdb taiga
createdb taiga
python manage.py migrate
python manage.py loaddata initial_user --traceback
python manage.py loaddata initial_project_templates --traceback
python manage.py sample_data --traceback
python manage.py rebuild_timeline --purge
'''

Sometimes when you run all commands together we don't see individual errors.

**Comment by ipedrazas** [comment]
Question is, the problem is loading data from the sample data... which it's not needed, but my fear is that the tables have not been created properly.

**Comment by ipedrazas** [comment]
Manual execution of the script fails with the same error:

```
django.db.utils.ProgrammingError: relation "projects_userstorycustomattribute" does not exist
LINE 1: INSERT INTO "projects_userstorycustomattribute" ("name", "de...
```

Outputs in the gist
https://gist.github.com/ipedrazas/07113b7af20ba871274a

**Comment by bameda** [comment]
Ok, ```./manage.py migrate``` doesn't apply all migrations, for example migrations in taiga/projects/custom_attributes/migrations/.

Your migrate:

```
  Apply all migrations: users, notifications, userstorage, auth, contenttypes, history, milestones, references, easy_thumbnails, djmail, sessions, tasks, timeline, userstories, wiki, searches, attachments, votes, admin, projects, issues
```

My migrate:

```
Apply all migrations: bitbucket, custom_attributes, tasks, userstorage, webhooks, auth, github, milestones, references, wiki, admin, history, issues, sessions, userstories, attachments, timeline, notifications, gitlab, user_attributes, searches, contenttypes, users, votes, djmail, feedback, projects, easy_thumbnails
```

What version of taiga-back are you using? ```git describe --tags```

Or maybe you overrrwite the list settings.INSTALLED_APPS.

My INSTALLED_APPS are:

```
python -c 'import os;os.environ.setdefault("DJANGO_SETTINGS_MODULE", "settings");from django.conf import settings; print("\n".join(settings.INSTALLED_APPS))'
```

```
django.contrib.auth
django.contrib.contenttypes
django.contrib.sessions
django.contrib.messages
django.contrib.admin
django.contrib.staticfiles
django.contrib.sitemaps
taiga.base
taiga.base.api
taiga.locale
taiga.events
taiga.front
taiga.users
taiga.userstorage
taiga.projects
taiga.projects.references
taiga.projects.custom_attributes
taiga.projects.history
taiga.projects.notifications
taiga.projects.attachments
taiga.projects.votes
taiga.projects.milestones
taiga.projects.userstories
taiga.projects.tasks
taiga.projects.issues
taiga.projects.wiki
taiga.searches
taiga.timeline
taiga.mdrender
taiga.export_import
taiga.feedback
taiga.stats
taiga.hooks.github
taiga.hooks.gitlab
taiga.hooks.bitbucket
taiga.webhooks
djmail
django_jinja
django_jinja.contrib._humanize
sr
easy_thumbnails
raven.contrib.django.raven_compat
django_transactional_cleanup
```

**Comment by ipedrazas** [comment]
That was it :+1: Totally my bad!

**Comment by bameda** [comment]
:dancer: :dancer: chachi
