### ISSUE TITLE
 No module named '_multiprocessing' in my Taiga dev environment

### ISSUE THREAD

**Issue by artlepool** [taigaio/taiga-back#425]
Hi guys

I'm trying to get my Taiga development environment updated however I'm getting a problem on master that I'm not getting on stable.

If I check out the stable branch of taiga-back, I can run any of the manage.py commands as usual without any problems.

However if I check out master, and run manage.py, I get the following error

```
Trying import local.py settings...
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/chriswilson/taiga-back/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/chriswilson/taiga-back/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/home/chriswilson/taiga-back/taiga/lib/python3.4/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/chriswilson/taiga-back/taiga/lib/python3.4/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/home/chriswilson/taiga-back/taiga/feedback/apps.py", line 31, in ready
    from taiga.urls import urlpatterns
  File "/home/chriswilson/taiga-back/taiga/urls.py", line 21, in <module>
    from .routers import router
  File "/home/chriswilson/taiga-back/taiga/routers.py", line 100, in <module>
    from taiga.searches.api import SearchViewSet
  File "/home/chriswilson/taiga-back/taiga/searches/api.py", line 29, in <module>
    from concurrent import futures
  File "/usr/local/lib/python3.4/concurrent/futures/__init__.py", line 17, in <module>
    from concurrent.futures.process import ProcessPoolExecutor
  File "/usr/local/lib/python3.4/concurrent/futures/process.py", line 55, in <module>
    from multiprocessing.connection import wait
  File "/usr/local/lib/python3.4/multiprocessing/connection.py", line 21, in <module>
    import _multiprocessing
ImportError: No module named '_multiprocessing'
```

I'm running in a newly created virtual environment, and have run ```pip install -r requirements.txt``` and ```pip install --upgrade -r requirements.txt``` after switching from stable branch to master.

The difference between stable and master which causes this seems to be commit ```8b05f20``` on the master branch which introduced the line below into taiga/searches/api.py:
```
from concurrent import futures
```

Any ideas please?
Am I missing a dependency in my requirements.txt file?

thanks!

**Comment by artlepool** [comment]
OK, so I just upgraded my Python version from 3.4.1 to 3.4.3 to see if that helps, and I can now run the manage.py tasks successfully without the _multiprocessing error above.

Has the introduction of the ```futures``` dependency from the ```concurrent``` module introduced a specific dependency on Python 3.4.3?

**Comment by bameda** [comment]
hmmm interesting, it's good to know that. We may have to change this.

**Comment by bameda** [comment]
What SO and kernel are you using??

**Comment by artlepool** [comment]
Output of the ```uname``` command as follows:

```
Linux CentOS 2.6.32-504.8.1.el6.x86_64 #1 SMP Wed Jan 28 21:11:36 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

And ```cat /etc/redhat-release``` is:

```
CentOS release 6.5 (Final)
```
