### ISSUE TITLE
AttributeError: 'UserStoryPermission' object has no attribute 'partial_update_perms'

### ISSUE THREAD

**Issue by maerten** [taigaio/taiga-back#441]
Got this error when sending a PATCH request to /api/v1/userstories/<id>/

**Comment by bameda** [comment]
Could you send us all the trace of the error? and the request too.

**Comment by maerten** [comment]
Trace:

    Internal Server Error: /api/v1/userstories/5
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/site-packages/django/core/handlers/base.py", line 137, in get_response
        response = response.render()
      File "/usr/local/lib/python3.4/site-packages/django/template/response.py", line 103, in render
        self.content = self.rendered_content
      File "/usr/local/taiga/taiga-back/taiga/base/response.py", line 74, in rendered_content
        ret = renderer.render(self.data, media_type, context)
      File "/usr/local/taiga/taiga-back/taiga/base/api/renderers.py", line 608, in render
        context = self.get_context(data, accepted_media_type, renderer_context)
      File "/usr/local/taiga/taiga-back/taiga/base/api/renderers.py", line 559, in get_context
        raw_data_put_form = self.get_raw_data_form(view, "PUT", request)
      File "/usr/local/taiga/taiga-back/taiga/base/api/renderers.py", line 486, in get_raw_data_form
        if not self.show_form_for_method(view, method, request, obj):
      File "/usr/local/taiga/taiga-back/taiga/base/api/renderers.py", line 426, in show_form_for_method
        view.check_permissions(request)
      File "/usr/local/taiga/taiga-back/taiga/base/api/viewsets.py", line 109, in check_permissions
        return super().check_permissions(request, action=action, obj=obj)
      File "/usr/local/taiga/taiga-back/taiga/base/api/views.py", line 304, in check_permissions
        if not permission.check_permissions(action=action, obj=obj):
      File "/usr/local/taiga/taiga-back/taiga/base/api/permissions.py", line 47, in check_permissions
        permset = getattr(self, "{}_perms".format(action))
    AttributeError: 'UserStoryPermission' object has no attribute 'partial_update_perms'

**Comment by maerten** [comment]
I guess it was a PUT, I don't have the original request as I'm debugging why I am getting a 400 BAD REQUEST when using PUT / PATCH.. Just came across this error and thought I'd post it here.

**Comment by superalex** [comment]
Were you doing the request manually or via the web app?, all the modifications are PATCH requests and are working ok using the web app...

**Comment by maerten** [comment]
It was a manual request.

**Comment by bameda** [comment]
Upgrade the code and try it again we fix it at https://github.com/taigaio/taiga-back/commit/132caab8d9d3dc5c2e39458ea56f777de62bfa18

**Comment by maerten** [comment]
I'm currently on the stable branch so upgrade doesn't really work.. Also cherry-picking gives me an error about an empty commit.
Will try to test at a later time, or whenever this is merged into the stable branch.

**Comment by bameda** [comment]
Yep, the commit is in stable https://github.com/taigaio/taiga-back/commit/84de51d9a74abdd71eb0ed478347aa4088ff6daf
