### ISSUE TITLE
project -> export not working

### ISSUE THREAD

**Issue by maerten** [taigaio/taiga-back#466]
Clicking the export button results in an error.

Request is an XHR GET /api/v1/exporter/4
The UserStories are created with the API and may contain special characters or weird encoding. Not sure if that is the cause of the problem though.

Log:

````
ERROR:2015-09-17 20:31:10,287: Internal Server Error: /api/v1/exporter/4
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/taiga/taiga-back/taiga/base/api/viewsets.py", line 81, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/taiga/taiga-back/taiga/base/api/views.py", line 420, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/taiga/taiga-back/taiga/base/api/views.py", line 417, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/taiga/taiga-back/taiga/export_import/api.py", line 73, in retrieve
    default_storage.save(path, content)
  File "/usr/local/lib/python3.4/site-packages/django/core/files/storage.py", line 51, in save
    name = self._save(name, content)
  File "/usr/local/lib/python3.4/site-packages/django/core/files/storage.py", line 227, in _save
    _file.write(chunk)
UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 15006: ordinal not in range(128)
````

**Comment by superalex** [comment]
Hello @maerten Taiga supports UserStories with special chars (you could try exporting from tree.taiga.io and it should work). It seems a problem related to the encoding of your filesystem, could you check this issues:

- https://github.com/taigaio/taiga-back/issues/343 
- https://github.com/taigaio/taiga-back/issues/298

**Comment by maerten** [comment]
Hi @superalex , I have put the LANG en LC_TYPE as suggested in #298, however it didn't resolve the issue. Also I'm running python 3.4 as mentioned in #343.
I think the difference with #298 and #343 is that there it was about decoding filenames, this issue is about writing the UTF8 file contents.

Shouldn't Taiga be able to export UTF8 by default? If the database uses UTF8, so should the exports?

Anyway, as I'm using a Docker image that could be the cause as well, I'm not re-opening the issue.

**Comment by superalex** [comment]
But default Taiga is able to export UTF8, until now all the problems that we had related to encoding has been because of people using python2 or system encoding.

As you say it could be related to the Docker image, could you try using another method for automated installation?, taiga-scripts should be the best option (http://taigaio.github.io/taiga-doc/dist/setup-alternatives.html#setup-taiga-scripts)

Regards!,
