### ISSUE TITLE
Taiga 1.8.0: HTTP error 500 while trying to delete project as admin.

### ISSUE THREAD

**Issue by kamiccolo** [taigaio/taiga-back#468]
Using Admin Panel can't delete projects created by a user. In fact, can't delete users who had created any projects. Server throws back "500, internal server error". I presume, it's a problem with backend, because Python complaining about DB table integrity.

Relevant `gunicorn.stderr.log` entry:
```
ERROR:2015-09-22 13:41:38,605: Internal Server Error: /admin/users/user/
Traceback (most recent call last):
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/backends/__init__.py", line 145, in _commit
    return self.connection.commit()
psycopg2.IntegrityError: insert or update on table "timeline_timeline" violates foreign key constraint "timeline_tim_project_id_525b3b62245de7b0_fk_projects_project_id"
DETAIL:  Key (project_id)=(1) is not present in table "projects_project".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/contrib/admin/options.py", line 583, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/utils/decorators.py", line 105, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/contrib/admin/sites.py", line 206, in inner
    return view(request, *args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/utils/decorators.py", line 105, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/utils/decorators.py", line 25, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/contrib/admin/options.py", line 1527, in changelist_view
    response = self.response_action(request, queryset=cl.get_queryset(request))
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/contrib/admin/options.py", line 1282, in response_action
    response = func(self, request, queryset)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/contrib/admin/actions.py", line 49, in delete_selected
    queryset.delete()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/models/query.py", line 557, in delete
    collector.delete()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/models/deletion.py", line 284, in delete
    sender=model, instance=obj, using=self.using
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/transaction.py", line 339, in __exit__
    connection.commit()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/transaction_hooks/mixin.py", line 43, in commit
    super(TransactionHooksDatabaseWrapperMixin, self).commit(*a, **kw)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/backends/__init__.py", line 176, in commit
    self._commit()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/backends/__init__.py", line 145, in _commit
    return self.connection.commit()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/utils/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/backends/__init__.py", line 145, in _commit
    return self.connection.commit()
django.db.utils.IntegrityError: insert or update on table "timeline_timeline" violates foreign key constraint "timeline_tim_project_id_525b3b62245de7b0_fk_projects_project_id"
DETAIL:  Key (project_id)=(1) is not present in table "projects_project".
```

**Comment by superalex** [comment]
Hello @kamiccolo,

It looks like a bug related to the user memberships not being properly removed before removing the timeline. As a temporary workaround you should first remove in the django admin (Projects -> memberships) the memberships associated to the user.

Regards!,

**Comment by kamiccolo** [comment]
Thanks, @superalex :}

**Comment by superalex** [comment]
You are welcome! ;)

**Comment by NikosAlexandris** [comment]
I confirm that removing the membership of a deleted user, allows then to remove a deleted project from the data base.

**Comment by superalex** [comment]
Thanks @NikosAlexandris !
