### ISSUE TITLE
[Q] Unable to fall back to normal authentication

### ISSUE THREAD

**Issue by ZheniaSteger** [taigaio/taiga-back#47]
Hello - I am having an issue after the latest update. 

I am using the contrib LDAP module for users to log in to Taiga.
It seems to be failing to fall back to normal authentication if LDAP fails. 

The error log:
LDAP login is invalid.
ERROR:2021-08-31 17:29:03,148: Internal Server Error: /api/v1/auth
Traceback (most recent call last):
  File "/opt/venv/lib/python3.7/site-packages/taiga_contrib_ldap_auth_ext/services.py", line 58, in ldap_login_func
    username, email, full_name = connector.login(login = login_input, password = password_input)
  File "/opt/venv/lib/python3.7/site-packages/taiga_contrib_ldap_auth_ext/connector.py", line 139, in login
    raise LDAPUserLoginError({"error_message": "LDAP login is invalid."})
taiga_contrib_ldap_auth_ext.connector.LDAPUserLoginError: {'error_message': 'LDAP login is invalid.'}
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/taiga-back/taiga/base/api/viewsets.py", line 95, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/venv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/taiga-back/taiga/base/api/views.py", line 449, in dispatch
    response = self.handle_exception(exc)
  File "/taiga-back/taiga/base/api/views.py", line 447, in dispatch
    response = handler(request, *args, **kwargs)
  File "/taiga-back/taiga/auth/api.py", line 77, in create
    data = auth_plugins[login_type]['login_func'](request)
  File "/opt/venv/lib/python3.7/site-packages/taiga_contrib_ldap_auth_ext/services.py", line 66, in ldap_login_func
    return get_auth_plugins()[FALLBACK]["login_func"](request)
KeyError: 'normal'

**Comment by h44z** [comment]
Same issue, using the latest docker images.

**Comment by h44z** [comment]
any news on this? this issue is actually a bug and not a question

**Comment by yamila-moreno** [comment]
Hi there!

Do you know that we have [Taiga Community](https://community.taiga.io/) for questions? Please, check there; maybe another user has already ask something similar. If not, create your own. There are people there willing to help, members of the Taiga team members and other users.

To simplify  the process, we will systematically close all issues that are general support questions and redirect people to Taiga Community.

Taiga Team
