### ISSUE TITLE
Matching query does not exist when importing sample_data

### ISSUE THREAD

**Issue by queeno** [taigaio/taiga-back#478]
Hi there

I am attempting to run the following command to import sample_data into a newly created taiga database:

```bash
python manage.py sample_data
```

As soon as I do that, I notice that my `celery.stderr.log` starts spamming errors like this:

```
[2015-10-07 11:55:31,430: ERROR/MainProcess] Task taiga.timeline.service.push_to_timeline[3dd65d5f-2512-4475-b755-bf2767394b74] raised unexpected: DoesNotExist('UserStory matching query does not exist.',)
Traceback (most recent call last):
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/taiga/taiga-back/taiga/timeline/service.py", line 85, in push_to_timeline
    _add_to_objects_timeline(objects, instance, event_type, created_datetime, namespace, extra_data)
  File "/home/taiga/taiga-back/taiga/timeline/service.py", line 77, in _add_to_objects_timeline
    _add_to_object_timeline(obj, instance, event_type, created_datetime, namespace, extra_data)
  File "/home/taiga/taiga-back/taiga/timeline/service.py", line 69, in _add_to_object_timeline
    data=impl(instance, extra_data=extra_data),
  File "/home/taiga/taiga-back/taiga/timeline/service.py", line 175, in _wrapper
    return fn(*args, **kwargs)
  File "/home/taiga/taiga-back/taiga/timeline/service.py", line 175, in _wrapper
    return fn(*args, **kwargs)
  File "/home/taiga/taiga-back/taiga/timeline/service.py", line 175, in _wrapper
    return fn(*args, **kwargs)
  File "/home/taiga/taiga-back/taiga/timeline/timeline_implementations.py", line 80, in task_timeline
    if instance.user_story:
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/models/fields/related.py", line 572, in __get__
    rel_obj = qs.get()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/models/query.py", line 357, in get
    self.model._meta.object_name)
taiga.projects.userstories.models.DoesNotExist: UserStory matching query does not exist.
```

Have you got any suggestions what may cause this issue?

Thanks very much for your help!

**Comment by bameda** [comment]
Is your data base empty??? Why don't use ```sh ./regenerate.sh```?

**Comment by queeno** [comment]
@bameda Thanks for your quick response.

My DB is initialised with basic data as described in the [taiga production installation guide](http://taigaio.github.io/taiga-doc/dist/setup-production.html).

I have now tried to regenerate the db using the `regenerate.sh` script, but during the execution of `python manage.py sample_data --traceback` step, I can see the same errors being spammed in `celery.stderr.log`.

I initially noticed this issue when I was browsing the project examples that get populated by the sample_data script. No matter which project, when I click on the 'backlog' icon, the application throws a 404 following my browser's HTTP request:

```
GET http://taiga.dnaops.co.uk/api/v1/userstories/filters_data?milestone=null&project=1 404 (NOT FOUND)
```

**Comment by bameda** [comment]
```sample_data``` is for empty databases only.

If your DB is initialized try to regenerate the timeline entries of your current dates.

```
python manage.py rebuild_timeline --purge
```

**Comment by queeno** [comment]
Thanks @bameda 

I've recreated the database and run the following commands:

```bash
pip install -r requirements.txt
python manage.py migrate --noinput
python manage.py loaddata initial_user
python manage.py loaddata initial_project_templates
python manage.py loaddata initial_role
python manage.py sample_data
```

and - after recreating once again the database -

```bash
pip install -r requirements.txt
python manage.py migrate --noinput
python manage.py loaddata initial_user
python manage.py loaddata initial_project_templates
python manage.py loaddata initial_role
python manage.py rebuild_timeline --purge
python manage.py sample_data
```

In both cases, I can still see many errors spammed in celery.stderr.log, for example:

```
[2015-10-07 13:23:48,539: ERROR/MainProcess] Task taiga.timeline.service.push_to_timeline[b93f87eb-fe4a-421e-8c0b-b2d562cfdd68] raised unexpected: IntegrityError('insert or update on table "timeline_timeline" violates foreign key constraint "timeline_tim_project_id_3158e514615e4a0c_fk_projects_project_id"\nDETAIL:  Key (project_id)=(6) is not present in table "projects_project".\n',)
Traceback (most recent call last):
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/taiga/taiga-back/taiga/timeline/service.py", line 83, in push_to_timeline
    _add_to_object_timeline(objects, instance, event_type, created_datetime, namespace, extra_data)
  File "/home/taiga/taiga-back/taiga/timeline/service.py", line 71, in _add_to_object_timeline
    created=created_datetime,
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/models/query.py", line 372, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/models/base.py", line 589, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/models/base.py", line 617, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/transaction.py", line 339, in __exit__
    connection.commit()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/transaction_hooks/mixin.py", line 43, in commit
    super(TransactionHooksDatabaseWrapperMixin, self).commit(*a, **kw)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/backends/__init__.py", line 176, in commit
    self._commit()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/backends/__init__.py", line 145, in _commit
    return self.connection.commit()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/utils/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/backends/__init__.py", line 145, in _commit
    return self.connection.commit()
django.db.utils.IntegrityError: insert or update on table "timeline_timeline" violates foreign key constraint "timeline_tim_project_id_3158e514615e4a0c_fk_projects_project_id"
DETAIL:  Key (project_id)=(6) is not present in table "projects_project".
```

**Comment by bameda** [comment]
```
IntegrityError: insert or update on table "timeline_timeline" violates foreign key constraint
```

Are you remove the db and create it again?

Run this:
```
dropdb taiga
```

and then

```
sh ./regenerate.sh
```

**Comment by queeno** [comment]
This is exactly what I'm doing.

Also the `regenerate.sh` script contains a line to drop the db before recreating it.

**Comment by bameda** [comment]
In you previows comment you don't say nothing about deleting the db.

And yes, regenerate.sh delete the db  but I wanted to be sure you deleted the db and there was no errors.

This hasn't happened to anyone before.

**Comment by queeno** [comment]
I have reprovisioned my taiga box multiple time since then and the issue hasn't occurred again.

I am guessing it was due to some inconsistency within postgres.

I am going to close this issue for now.
