### ISSUE TITLE
Email Templates Not Being Created

### ISSUE THREAD

**Issue by JTWorks** [taigaio/taiga-back#484]
When trying to do a bulk_create or anything dealing with emails I get errors such as

```
Trying import local.py settings...
Template 'emails/membership_notification-body-html.html' does not exists.
Raven is not configured (logging is disabled). Please see the documentation for more information.
ERROR:2015-10-14 13:26:32,192: Internal Server Error: /api/v1/memberships/bulk_create
Traceback (most recent call last):
  File "/opt/taiga/back/taiga-py/lib/python3.4/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/taiga/back/taiga/base/api/viewsets.py", line 81, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/taiga/back/taiga-py/lib/python3.4/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/taiga/back/taiga/base/api/views.py", line 420, in dispatch
    response = self.handle_exception(exc)
  File "/opt/taiga/back/taiga/base/api/views.py", line 417, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/taiga/back/taiga/projects/api.py", line 457, in bulk_create
    precall=self.pre_save)
  File "/opt/taiga/back/taiga/projects/services/members.py", line 31, in create_members_in_bulk
    db.save_in_bulk(members, callback, precall)
  File "/opt/taiga/back/taiga-py/lib/python3.4/site-packages/django/db/transaction.py", line 394, in inner
    return func(*args, **kwargs)
  File "/opt/taiga/back/taiga/base/utils/db.py", line 74, in save_in_bulk
    callback(instance, created=created)
  File "/opt/taiga/back/taiga/projects/api.py", line 492, in post_save
    services.send_invitation(invitation=object)
  File "/opt/taiga/back/taiga/projects/services/invitations.py", line 12, in send_invitation
    email = template(invitation.user, {"membership": invitation})
  File "/opt/taiga/back/taiga-py/lib/python3.4/site-packages/djmail/template_mail.py", line 160, in _dynamic_email_generator
    email_instance = template_email.make_email_object(to, context)
  File "/opt/taiga/back/taiga-py/lib/python3.4/site-packages/djmail/template_mail.py", line 97, in make_email_object
    body_html = self._render_message_body_as_html(context)
  File "/opt/taiga/back/taiga-py/lib/python3.4/site-packages/djmail/template_mail.py", line 133, in _render_message_body_as_html
    return premailer.transform(html)
  File "/opt/taiga/back/taiga-py/lib/python3.4/site-packages/premailer/premailer.py", line 560, in transform
    return Premailer(html, base_url=base_url).transform()
  File "/opt/taiga/back/taiga-py/lib/python3.4/site-packages/premailer/premailer.py", line 291, in transform
    stripped = self.html.strip()
AttributeError: 'NoneType' object has no attribute 'strip'
```

**Comment by bameda** [comment]
> Template 'emails/membership_notification-body-html.html' does not exists.

This file must be ```.jinja``` instead ```.html```. It is in ```taiga-back/taiga/projects/templates/emails/membership_notification-body-html.jinja```

What branch of taiga-back are you using?
Have you made any change in ```taiga-back/settings.common.py```?
What's in your file ```taiga-back/settings.local.py```?

Try to make ```git status``` to check if there is some change in any file.

**Comment by JTWorks** [comment]
I misconfigured something in common.py! Thanks for the quick reply!!

**Comment by bameda** [comment]
You are welcome.

Don't touch ```common.py```, overwrite any settings in ```locale.py```
