### ISSUE TITLE
saving error in some stories

### ISSUE THREAD

**Issue by segler-alex** [taigaio/taiga-back#507]
hi, i am using stable branch. i updated yesterday and everything seemed fine but today a problem emerged with one of our projects in taiga.  as far as i can find out it is only one projects out of 3 we do with taiga. and only some tasks. they cannot be saved because umba lumpas are complaining.
i looked at the logs and found this everytime a save could not be done:

```
ERROR:2015-11-03 09:34:43,065: Internal Server Error: /api/v1/userstories
Traceback (most recent call last):
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/viewsets.py", line 81, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/views.py", line 420, in dispatch
    response = self.handle_exception(exc)
  File "/home/taiga/taiga-back/taiga/base/api/views.py", line 417, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/lib/python3.4/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/home/taiga/taiga-back/taiga/projects/userstories/api.py", line 248, in create
    response = super().create(*args, **kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/mixins.py", line 73, in create
    self.post_save(self.object, created=True)
  File "/home/taiga/taiga-back/taiga/projects/userstories/api.py", line 150, in post_save
    super().post_save(obj, created)
  File "/home/taiga/taiga-back/taiga/projects/occ/mixins.py", line 83, in post_save
    super().post_save(obj, created)
  File "/home/taiga/taiga-back/taiga/projects/history/mixins.py", line 72, in post_save
    self.persist_history_snapshot(obj=obj)
  File "/home/taiga/taiga-back/taiga/projects/history/mixins.py", line 68, in persist_history_snapshot
    self.__last_history = take_snapshot(sobj, comment=comment, user=user, delete=delete)
  File "/usr/lib/python3.4/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/home/taiga/taiga-back/taiga/projects/history/services.py", line 335, in take_snapshot
    return entry_model.objects.create(**kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/models/query.py", line 348, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/models/base.py", line 771, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/dispatch/dispatcher.py", line 201, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/taiga_contrib_slack/signal_handlers.py", line 62, in on_new_history_entry
    task(*args)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/celery/local.py", line 188, in __call__
    return self._get_current_object()(*a, **kw)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/celery/app/task.py", line 420, in __call__
    return self.run(*args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/taiga_contrib_slack/tasks.py", line 271, in create_slackhook
    "text": template.render(context),
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django_jinja/backend.py", line 64, in render
    return self.template.render(context)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/jinja2/environment.py", line 984, in render
    vars = dict(*args, **kwargs)
ValueError: dictionary update sequence element #1 has length 3; 2 is required
```

can i give you any more help fixing this?
i updated the backend again today, because i saw you added a new commit in stable branch. but it did not fix it.

**Comment by bameda** [comment]
have you update contrib plugins too?

**Comment by segler-alex** [comment]
thanks i will look at it,
i have one contrib plugin, which is slack. and only this project is using it. how would you update slack plugin? i installed it with
   pip install taiga-contrib-slack
i just tried updating it with same command and it only did uninstall django 1.8.5 and installed 1.7.8 again...

**Comment by superalex** [comment]
Hello @segler-alex 

Try the following:

From taiga-back:
```
pip install --upgrade taiga-contrib-slack
python manage.py migrate
```

From taiga-front:
```
cd dist/js
  wget "https://raw.githubusercontent.com/taigaio/taiga-contrib-slack/$(pip show taiga-contrib-slack | awk '/^Version: /{print $2}')/front/dist/slack.js"
```

**Comment by segler-alex** [comment]
thank you very much!
this fixed my problem. everything is working again now. Thank you for you fast support!

**Comment by superalex** [comment]
Great!, you are welcome! ;)
