### ISSUE TITLE
Syntax error when updating (python manage.py migrate  --noinput)

### ISSUE THREAD

**Issue by azorpax** [taigaio/taiga-back#508]
(taiga)bstc@taiga:~/taiga-back$ python manage.py migrate --noinput
Trying import local.py settings...
System check identified some issues:

WARNINGS:
?: (1_8.W001) The standalone TEMPLATE_* settings were deprecated in Django 1.8 and the TEMPLATES dictionary takes precedence. You must put the values of the following settings into your default TEMPLATES dict: TEMPLATE_DEBUG.
Raven is not configured (logging is disabled). Please see the documentation for more information.
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/bstc/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "/home/bstc/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 343, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/bstc/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/bstc/.virtualenvs/taiga/lib/python3.4/site-packages/raven/contrib/django/management/__init__.py", line 41, in new_execute
    return original_func(self, *args, **kwargs)
  File "/home/bstc/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/home/bstc/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/commands/migrate.py", line 93, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/home/bstc/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/migrations/executor.py", line 19, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/home/bstc/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/migrations/loader.py", line 47, in __init__
    self.build_graph()
  File "/home/bstc/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/migrations/loader.py", line 176, in build_graph
    self.load_disk()
  File "/home/bstc/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/migrations/loader.py", line 102, in load_disk
    migration_module = import_module("%s.%s" % (module_name, migration_name))
  File "/home/bstc/.virtualenvs/taiga/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2231, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2203, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1444, in exec_module
  File "<frozen importlib._bootstrap>", line 1549, in get_code
  File "<frozen importlib._bootstrap>", line 1509, in source_to_code
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/bstc/taiga-back/taiga/projects/notifications/migrations/0006_auto_20151103_0954.py", line 17
    field=models.SmallIntegerField(choices=[(<NotifyLevel.involved: 1>, 'Involved'), (<NotifyLevel.all: 2>, 'All'), (<NotifyLevel.none: 3>, 'None')]),
                                             ^
SyntaxError: invalid syntax

**Comment by superalex** [comment]
Hello @azorpax did you update the requirements before executing the migrations? Did you follow the instructions at http://taigaio.github.io/taiga-doc/dist/setup-faqs.html#faq-maintain-update for updating?

**Comment by azorpax** [comment]
Hi @superalex! 
Yes I followed that instructions. line by line.

**Comment by superalex** [comment]
@bameda is working on it right now, it seems django generated an invalid migration file, we'll fix it as soon as possible.

**Comment by bameda** [comment]
Fixed in master and stable 

https://github.com/taigaio/taiga-back/commit/b7a752221f6cce9da3e2e7d9a684387bbfae9581

Thanks for report

**Comment by Shishir20** [comment]
Hi @superalex 
I'm facing similar issue, can you tell what it might be regarding.
```javascript
```
Trying import local.py settings...
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 195, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 39, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1467, in exec_module
  File "<frozen importlib._bootstrap>", line 1572, in get_code
  File "<frozen importlib._bootstrap>", line 1532, in source_to_code
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/taiga/taiga-back/taiga/export_import/management/commands/load_dump.py", line 24
    from taiga.export_import.import services
                                  ^
SyntaxError: invalid syntax
```

```

**Comment by superalex** [comment]
Hello @Shishir20 there was an error in the last version of the load_dump.py, I've just updated it, could you update your taiga-back version and try again?

**Comment by Shishir20** [comment]
Thank You! I solved the issue.

But I'm a lot of other issues too. 

1. Not able to import project. It says I'll get a mail once done. As I have not configured SMTP yet I don't get any email and project is not getting added.

2. Currently, I have uploaded projects as json using` python manage.py load_dum `. Its showing up as one of my project but when I try to open it spinner appears and nothing else.


Any clue??

**Comment by superalex** [comment]
Hello @Shishir20 if you don't have an smtp configured use taiga in synchronous mode (don't use celery/events), that way the import/export actions won't involve emails (but it will be slower)

What user are you using for accessing the imported projects?

**Comment by Shishir20** [comment]
@superalex same user who created the project.

**Comment by superalex** [comment]
But is it the admin one?

**Comment by Shishir20** [comment]
@superalex Yup

**Comment by superalex** [comment]
I'm sorry, it's a known issue, timeline doesn't work properly for admin user :(

Could you try with a different useR?

**Comment by Shishir20** [comment]
@superalex 
Thanks to you all previous issues are resolved!

I'm facing a new issue:
Most of the POST calls are returning with 500: Internal Server Error.

Any idea what might be going wrong? Or what shall I check for?

**Comment by superalex** [comment]
Hello @Shishir20 if disabling asynchronous tasks make those messages disappear it will be probably related to the rabbitmq connection.

**Comment by Shishir20** [comment]
Hi @superalex   I'm having real trouble with this error. Can you please help.
Here is the link eith the error : https://groups.google.com/forum/#!topic/taigaio/syJUo-bofOg

**Comment by superalex** [comment]
@Shishir20 ,  @bameda answered on the email list ;)

**Comment by kiwenowo** [comment]
@superalex  I don't know how to solve this problem, could you help me?
(ll-env) C:\Users\dell2\Desktop\learning_log>python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\dell2\Desktop\learning_log\ll-env\lib\site-packages\django\core\management\__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "C:\Users\dell2\Desktop\learning_log\ll-env\lib\site-packages\django\core\management\__init__.py", line 337, in execute
    django.setup()
  File "C:\Users\dell2\Desktop\learning_log\ll-env\lib\site-packages\django\__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\dell2\Desktop\learning_log\ll-env\lib\site-packages\django\apps\registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\dell2\Desktop\learning_log\ll-env\lib\site-packages\django\apps\config.py", line 94, in create
    module = import_module(entry)
  File "E:\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\dell2\Desktop\learning_log\ll-env\lib\site-packages\django\contrib\admin\__init__.py", line 4, in <module>
    from django.contrib.admin.filters import (
  File "C:\Users\dell2\Desktop\learning_log\ll-env\lib\site-packages\django\contrib\admin\filters.py", line 10, in <module>
    from django.contrib.admin.options import IncorrectLookupParameters
  File "C:\Users\dell2\Desktop\learning_log\ll-env\lib\site-packages\django\contrib\admin\options.py", line 12, in <module>
    from django.contrib.admin import helpers, widgets
  File "C:\Users\dell2\Desktop\learning_log\ll-env\lib\site-packages\django\contrib\admin\widgets.py", line 151
    '%s=%s' % (k, v) for k, v in params.items(),
    ^
SyntaxError: Generator expression must be parenthesized

**Comment by alexhermida** [comment]
@kiwenowo which version of python are you using? You must use Python 3.5 although it works also for development in Python 3.6. Currently taiga-back it's Django 1.11 and it's not compatible with Python 3.7

**Comment by kiwenowo** [comment]
@alexhermida thank you! what I use is python 3.7, so could I upgrade the Django to solve it?

**Comment by alexhermida** [comment]
@kiwenowo currently taiga-back has strong dependencies with Django 1.11. You must use python 3.5-3.6.

**Comment by kiwenowo** [comment]
@alexhermida  Thank for your advice! I have solved this problem:)

**Comment by kiwenowo** [comment]
@alexhermida thanks for your advice! I have solved this problem:)

**Comment by Prerna2589** [comment]
@kiwenowo  how did u solved this issue. I am also facing the same. Can you guide me for the same.
