### ISSUE TITLE
Migrate failed with the below log: relation "djmail_message" already exists

### ISSUE THREAD

**Issue by fish-ball** [taigaio/taiga-back#513]
I've just try to upgrade taiga to 1.9.0, when I do the instructions mentioned here: <http://taigaio.github.io/taiga-doc/dist/setup-faqs.html#faq-maintain-update>

The below error log occurred when I migrate the database.

```
(taiga)taiga@vps3:~/taiga-back$ python manage.py migrate --noinput
Trying import local.py settings...
Operations to perform:
  Synchronize unmigrated apps: django_jinja, django_transactional_cleanup, raven_contrib_django, sr, export_import, messages, events, front, staticfiles, searches, base, _humanize, stats, sitemaps, api, mdrender, locale
  Apply all migrations: likes, webhooks, admin, attachments, sessions, tasks, wiki, timeline, easy_thumbnails, references, gitlab, bitbucket, userstorage, external_apps, custom_attributes, djmail, votes, auth, history, users, projects, github, userstories, issues, feedback, milestones, contenttypes, notifications
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying djmail.0001_initial...Raven is not configured (logging is disabled). Please see the documentation for more information.
Traceback (most recent call last):
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
psycopg2.ProgrammingError: relation "djmail_message" already exists


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 343, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/raven/contrib/django/management/__init__.py", line 41, in new_execute
    return original_func(self, *args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/commands/migrate.py", line 222, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/migrations/executor.py", line 148, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/migrations/operations/models.py", line 59, in database_forwards
    schema_editor.create_model(model)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/backends/base/schema.py", line 286, in create_model
    self.execute(sql, params or None)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/backends/base/schema.py", line 111, in execute
    cursor.execute(sql, params)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/utils/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: relation "djmail_message" already exists
```

**Comment by superalex** [comment]
Hello @fish-ball 

That error is a bit strange, did you check if you received any error when executing the command "pip install --upgrade -r requirements.txt"?, could you please repeat the backend steps?.

Just one more question, what was your previous version?

**Comment by fish-ball** [comment]
@superalex Thank you, I'm upgrading from version 1.8.0, and have been upgraded many times. Initially using fron as early as 1.6.0.

So in the later upgrading, the migration seemed has some problem, but I fixed them then.

But this time I have no idea how to fix it.

**Comment by fish-ball** [comment]
I've rolled back the backup tp 1.8.0, then export all the projects manually, then clear and regenerates the database, import them then, the problem is solved

**Comment by DoubleMalt** [comment]
I just updated my Docker installation of Taiga and get the same error. The export/import workaround is not an option. How can I fix this?

**Comment by superalex** [comment]
@DoubleMalt I think your situation is a bit different, could you check if this is your problem? -> https://github.com/taigaio/taiga-back/issues/519

**Comment by DoubleMalt** [comment]
No bc. in the logs of my taiga-back container I see exactly "relation "djmail_message" already exists"

**Comment by superalex** [comment]
@DoubleMalt could you execute this to check that you are in a 1.9 release
```
git pull
git describe --always --tag
python migrate --list
```

**Comment by bameda** [comment]
I fix the last command:

```
git pull
git describe --always --tag
python manage.py migrate --list
```

**Comment by DoubleMalt** [comment]
The container is on commit 768dfeb1731be791595e20e732f449e6ea9820ee

**Comment by superalex** [comment]
Could you please execute those commands (with the @bameda correction) and show us the result?

**Comment by DoubleMalt** [comment]
http://pastebin.com/96BeUwXv

**Comment by superalex** [comment]
Thanks @DoubleMalt it's strange that it's marking djmail as not migrated. 

If you execute a 
```
pip show djmail
```

Is it showing the correct 0.11.0 version?

If that's ok I can't imagine why django thinks that initial migration 0001 wasn't applied (if the djmail tables exist), you could also try faking that migration with something like:

```
python manage.py migrate djmail --fake-initial
```
If it works a "python manage.py migrate djmail --list" should say the migration is applied

**Comment by DoubleMalt** [comment]
The surgery worked, I have my Taiga back!

Thx for the support! :+1:

**Comment by superalex** [comment]
Great!, I still don't really know why django thought that migration wasn't applied but I'm happy the surgery worked! :dancer:
