### ISSUE TITLE
Upgrading to Taiga 1.9: relation "likes_likes" does not exist

### ISSUE THREAD

**Issue by queeno** [taigaio/taiga-back#519]
Hi there!

I have an issue running Taiga 1.9 on my local infrastructure and hope you can help me with this.

I am running Tiaga 1.9 within docker using my own dockerfile [queeno/docker-taiga](https://github.com/queeno/docker-taiga), postgres as database and nginx as webserver.

This configuration works well with pre1.9 taiga (specifically before this commit: 3fc725c0)

I have also reproduced the issue on a clean Taiga 1.9 installation with a fresh DB.

After upgrading to Taiga 1.9, I noticed that my projects aren't displayed at all on my home page (after successfully logging in).

Using Chrome's debugging tools, I realised that the server responds 500 to HTTP GET requests to the following endpoint: `http://192.168.33.10:8000/api/v1/projects?member=4&order_by=memberships__user_order`.

Back on the server, the taiga-back logs seem to hint the `likes_like` table is missing from my DB:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/taiga-back/taiga/base/api/viewsets.py", line 81, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/taiga-back/taiga/base/api/views.py", line 420, in dispatch
    response = self.handle_exception(exc)
  File "/taiga-back/taiga/base/api/views.py", line 417, in dispatch
    response = handler(request, *args, **kwargs)
  File "/taiga-back/taiga/base/api/mixins.py", line 113, in list
    return response.Ok(serializer.data)
  File "/taiga-back/taiga/base/api/serializers.py", line 589, in data
    self._data = [self.to_native(item) for item in obj]
  File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 162, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/usr/local/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.5/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python3.5/site-packages/django/utils/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "likes_likes" does not exist
LINE 3:                   FROM likes_likes
```

Inspecting the postgres taiga DB, it turns out the likes_likes table is indeed missing:

```
taiga=# \dt
                                List of relations
 Schema |                          Name                           | Type  | Owner
--------+---------------------------------------------------------+-------+-------
 public | attachments_attachment                                  | table | taiga
 public | auth_group                                              | table | taiga
 public | auth_group_permissions                                  | table | taiga
 public | auth_permission                                         | table | taiga
 public | custom_attributes_issuecustomattribute                  | table | taiga
 public | custom_attributes_issuecustomattributesvalues           | table | taiga
 public | custom_attributes_taskcustomattribute                   | table | taiga
 public | custom_attributes_taskcustomattributesvalues            | table | taiga
 public | custom_attributes_userstorycustomattribute              | table | taiga
 public | custom_attributes_userstorycustomattributesvalues       | table | taiga
 public | django_admin_log                                        | table | taiga
 public | django_content_type                                     | table | taiga
 public | django_migrations                                       | table | taiga
 public | django_session                                          | table | taiga
 public | djmail_message                                          | table | taiga
 public | easy_thumbnails_source                                  | table | taiga
 public | easy_thumbnails_thumbnail                               | table | taiga
 public | easy_thumbnails_thumbnaildimensions                     | table | taiga
 public | feedback_feedbackentry                                  | table | taiga
 public | history_historyentry                                    | table | taiga
a       | issues_issue                                            | table | taig--More--
 public | milestones_milestone                                    | table | taiga
 public | notifications_historychangenotification                 | table | taiga
 public | notifications_historychangenotification_history_entries | table | taiga
 public | notifications_historychangenotification_notify_users    | table | taiga
 public | notifications_notifypolicy                              | table | taiga
 public | notifications_watched                                   | table | taiga
 public | projects_issuestatus                                    | table | taiga
 public | projects_issuetype                                      | table | taiga
 public | projects_membership                                     | table | taiga
 public | projects_points                                         | table | taiga
 public | projects_priority                                       | table | taiga
 public | projects_project                                        | table | taiga
 public | projects_projectmodulesconfig                           | table | taiga
 public | projects_projecttemplate                                | table | taiga
 public | projects_severity                                       | table | taiga
 public | projects_taskstatus                                     | table | taiga
 public | projects_userstorystatus                                | table | taiga
 public | references_reference                                    | table | taiga
 public | tasks_task                                              | table | taiga
 public | timeline_timeline                                       | table | taiga
 public | users_authdata                                          | table | taiga
 public | users_role                                              | table | taiga
a       | users_user                                              | table | taig--More--
 public | userstorage_storageentry                                | table | taiga
 public | userstories_rolepoints                                  | table | taiga
 public | userstories_userstory                                   | table | taiga
 public | votes_vote                                              | table | taiga
 public | votes_votes                                             | table | taiga
 public | webhooks_webhook                                        | table | taiga
 public | webhooks_webhooklog                                     | table | taiga
 public | wiki_wikilink                                           | table | taiga
 public | wiki_wikipage                                           | table | taiga
(53 rows)
```
`python manage.py makemigrations` generates some sql migrations for the Like and Likes models:

```
root@d0eff1d0e6b1:/taiga-back# python manage.py makemigrations
Trying import local.py settings...
Migrations for 'projects':
  0028_auto_20151110_1135.py:
    - Create model Like
    - Create model Likes
    - Alter unique_together for likes (1 constraint(s))
    - Alter unique_together for like (1 constraint(s))
root@d0eff1d0e6b1:/taiga-back#
```

However when running `python manage.py migrate` only the following couple of tables are generated:

```
 public | projects_like                                           | table | taiga
 public | projects_likes                                          | table | taiga
```

`python manage.py makemigrations` generates `0028_auto_20151110_1135.py` in my local [taiga/projects/migrations](https://github.com/taigaio/taiga-back/tree/master/taiga/projects/migrations), which is missing from the upstream taiga-back repo.

Could you please clarify why the likes_like table doesn't get created automatically by the migration script? Am I indadvertedly introducing inconsistency in my db somewhere?

Thanks for your help!

**Comment by superalex** [comment]
Hello @queeno what process did you follow for updating to the 1.9 version?. It sounds like your database schema isn't properly synchronized with the models/migrations, creating your own new migrations (if didn't modify the code) shouldn't be necessary and could introduce inconsistencies in your bd. 

I think you could try to undo the migration you manually created (migrating projects to 0027 and removing the 0028 file) and check what's the output of:

```
python manage.py migrate --list likes
```

If your taiga-back was correctly updated to 1.9 the result should be:
```
likes
 [X] 0001_initial
```

Regards,

**Comment by queeno** [comment]
Hi @superalex 

Thanks for your help!

I built a new container with Taiga 1.9 and replaced the old one. The only change I made was checking out version taiga-back and taiga-front-dist at version 1.9.
After starting the new container, I ran the following command:

```
docker exec taiga bash -c 'python manage.py migrate'
```

I have also provisioned a vagrant box with Taiga 1.9 and a fresh DB, I have run the `regenerate.sh` script but unfortunately, the result of `python manage.py migrate --list likes` doesn't show any migrations for likes.

```
root@680f2df4f497:/taiga-back# python manage.py migrate --list likes
Trying import local.py settings...
Raven is not configured (logging is disabled). Please see the documentation for more information.
CommandError: No migrations present for: likes
root@680f2df4f497:/taiga-back#
```

My vagrant box's `taiga-back/taiga/projects/migrations` doesn't contain any 0028 file.

**Comment by superalex** [comment]
Hello @queeno 

If you generated the migration 0028_auto_20151110_1135, could you check where it was generated?

About the likes migration not present...could you check if you are really in the 1.9 release?:

```
git describe --always --tag
```

Should give you a result similar to
```
1.9.0-27-g1c38494
```

**Comment by queeno** [comment]
Hi @superalex 

0028_auto_20151110_1135 was generated in taiga-back/taiga/project/migrations. This is its content:

```
root@680f2df4f497:/taiga-back/taiga/projects/migrations# cat 0028_auto_20151111_1225.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0027_auto_20150916_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(serialize=False, auto_created=True, primary_key=True, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('content_type', models.ForeignKey(to='contenttypes.ContentType')),
                ('user', models.ForeignKey(related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name_plural': 'Likes',
                'verbose_name': 'Like',
            },
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(serialize=False, auto_created=True, primary_key=True, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('count', models.PositiveIntegerField(verbose_name='count', default=0)),
                ('content_type', models.ForeignKey(to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name_plural': 'Likes',
                'verbose_name': 'Likes',
            },
        ),
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together=set([('content_type', 'object_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set([('content_type', 'object_id', 'user')]),
        ),
    ]
root@680f2df4f497:/taiga-back/taiga/projects/migrations#
```

This is the output of `git describe`:
```
root@680f2df4f497:/taiga-back# git describe --always --tag
1.9.0-27-g1c38494
root@680f2df4f497:/taiga-back#
```

Hope this helps!

**Comment by superalex** [comment]
Could you execute an extra pull to check if everything is ok?
```
git pull
```

And the output of
```
ls taiga/projects/likes/migrations/
```

A git status says something?
```
git status
```

**Comment by queeno** [comment]
```
root@680f2df4f497:/taiga-back/taiga/projects/migrations# git pull
git Already up-to-date.
root@680f2df4f497:/taiga-back/taiga/projects/migrations# git status
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	0028_auto_20151111_1225.py

nothing added to commit but untracked files present (use "git add" to track)
root@680f2df4f497:/taiga-back/taiga/projects/migrations# ls -l
total 132
-rw-r--r-- 1 root root  6614 Nov 11 12:06 0001_initial.py
-rw-r--r-- 1 root root 13681 Nov 11 12:06 0002_auto_20140903_0920.py
-rw-r--r-- 1 root root   988 Nov 11 12:06 0003_auto_20140913_1710.py
-rw-r--r-- 1 root root   424 Nov 11 12:06 0004_auto_20141002_2337.py
-rw-r--r-- 1 root root   501 Nov 11 12:06 0005_membership_invitation_extra_text.py
-rw-r--r-- 1 root root   742 Nov 11 12:06 0006_auto_20141029_1040.py
-rw-r--r-- 1 root root   955 Nov 11 12:06 0007_auto_20141024_1011.py
-rw-r--r-- 1 root root  2258 Nov 11 12:06 0008_auto_20141024_1012.py
-rw-r--r-- 1 root root  1306 Nov 11 12:06 0009_auto_20141024_1037.py
-rw-r--r-- 1 root root   526 Nov 11 12:06 0010_project_modules_config.py
-rw-r--r-- 1 root root  1109 Nov 11 12:06 0011_auto_20141028_2057.py
-rw-r--r-- 1 root root   868 Nov 11 12:06 0012_auto_20141210_1009.py
-rw-r--r-- 1 root root   999 Nov 11 12:06 0013_auto_20141210_1040.py
-rw-r--r-- 1 root root   481 Nov 11 12:06 0014_userstorystatus_is_archived.py
-rw-r--r-- 1 root root   863 Nov 11 12:06 0015_auto_20141230_1212.py
-rw-r--r-- 1 root root  1630 Nov 11 12:06 0016_fix_json_field_not_null.py
-rw-r--r-- 1 root root   705 Nov 11 12:06 0017_fix_is_private_for_projects.py
-rw-r--r-- 1 root root  1055 Nov 11 12:06 0018_auto_20150219_1606.py
-rw-r--r-- 1 root root  1481 Nov 11 12:06 0019_auto_20150311_0821.py
-rw-r--r-- 1 root root   474 Nov 11 12:06 0020_membership_user_order.py
-rw-r--r-- 1 root root  1214 Nov 11 12:06 0021_auto_20150504_1524.py
-rw-r--r-- 1 root root  1338 Nov 11 12:06 0022_auto_20150701_0924.py
-rw-r--r-- 1 root root   812 Nov 11 12:06 0023_auto_20150721_1511.py
-rw-r--r-- 1 root root  1673 Nov 11 12:06 0024_auto_20150810_1247.py
-rw-r--r-- 1 root root  1449 Nov 11 12:06 0025_auto_20150901_1600.py
-rw-r--r-- 1 root root   825 Nov 11 12:06 0026_auto_20150911_1237.py
-rw-r--r-- 1 root root   741 Nov 11 12:06 0027_auto_20150916_1302.py
-rw-r--r-- 1 root root  1994 Nov 11 12:25 0028_auto_20151111_1225.py
-rw-r--r-- 1 root root     0 Nov 11 12:06 __init__.py
drwxr-xr-x 2 root root  4096 Nov 11 12:25 __pycache__
root@680f2df4f497:/taiga-back/taiga/projects/migrations#
```

**Comment by superalex** [comment]
@queeno you are on branch master, our master branch isn't production ready, you should use stable always (both for taiga-back and taiga-front), could you please checkout to that branches and try again?

**Comment by queeno** [comment]
Apologies, @superalex. That was just me experimenting.

I have rebuilt my container using the stable branch. Unfortunately very little has changed:

```
root@85ce07612bfb:/taiga-back/taiga/projects/migrations# git pull
Already up-to-date.
root@85ce07612bfb:/taiga-back/taiga/projects/migrations# git status
On branch stable
Your branch is up-to-date with 'origin/stable'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	0028_auto_20151111_1456.py

nothing added to commit but untracked files present (use "git add" to track)
root@85ce07612bfb:/taiga-back/taiga/projects/migrations# ls -l
total 132
-rw-r--r-- 1 root root  6614 Nov 11 14:49 0001_initial.py
-rw-r--r-- 1 root root 13681 Nov 11 14:49 0002_auto_20140903_0920.py
-rw-r--r-- 1 root root   988 Nov 11 14:49 0003_auto_20140913_1710.py
-rw-r--r-- 1 root root   424 Nov 11 14:49 0004_auto_20141002_2337.py
-rw-r--r-- 1 root root   501 Nov 11 14:49 0005_membership_invitation_extra_text.py
-rw-r--r-- 1 root root   742 Nov 11 14:49 0006_auto_20141029_1040.py
-rw-r--r-- 1 root root   955 Nov 11 14:49 0007_auto_20141024_1011.py
-rw-r--r-- 1 root root  2258 Nov 11 14:49 0008_auto_20141024_1012.py
-rw-r--r-- 1 root root  1306 Nov 11 14:49 0009_auto_20141024_1037.py
-rw-r--r-- 1 root root   526 Nov 11 14:49 0010_project_modules_config.py
-rw-r--r-- 1 root root  1109 Nov 11 14:49 0011_auto_20141028_2057.py
-rw-r--r-- 1 root root   868 Nov 11 14:49 0012_auto_20141210_1009.py
-rw-r--r-- 1 root root   999 Nov 11 14:49 0013_auto_20141210_1040.py
-rw-r--r-- 1 root root   481 Nov 11 14:49 0014_userstorystatus_is_archived.py
-rw-r--r-- 1 root root   863 Nov 11 14:49 0015_auto_20141230_1212.py
-rw-r--r-- 1 root root  1630 Nov 11 14:49 0016_fix_json_field_not_null.py
-rw-r--r-- 1 root root   705 Nov 11 14:49 0017_fix_is_private_for_projects.py
-rw-r--r-- 1 root root  1055 Nov 11 14:49 0018_auto_20150219_1606.py
-rw-r--r-- 1 root root  1481 Nov 11 14:49 0019_auto_20150311_0821.py
-rw-r--r-- 1 root root   474 Nov 11 14:49 0020_membership_user_order.py
-rw-r--r-- 1 root root  1214 Nov 11 14:49 0021_auto_20150504_1524.py
-rw-r--r-- 1 root root  1338 Nov 11 14:49 0022_auto_20150701_0924.py
-rw-r--r-- 1 root root   812 Nov 11 14:49 0023_auto_20150721_1511.py
-rw-r--r-- 1 root root  1673 Nov 11 14:49 0024_auto_20150810_1247.py
-rw-r--r-- 1 root root  1449 Nov 11 14:49 0025_auto_20150901_1600.py
-rw-r--r-- 1 root root   825 Nov 11 14:49 0026_auto_20150911_1237.py
-rw-r--r-- 1 root root   741 Nov 11 14:49 0027_auto_20150916_1302.py
-rw-r--r-- 1 root root  1994 Nov 11 14:56 0028_auto_20151111_1456.py
-rw-r--r-- 1 root root     0 Nov 11 14:49 __init__.py
drwxr-xr-x 2 root root  4096 Nov 11 14:56 __pycache__
root@85ce07612bfb:/taiga-back/taiga/projects/migrations#
```

```
root@85ce07612bfb:/taiga-back# python manage.py makemigrations
Trying import local.py settings...
Migrations for 'projects':
  0028_auto_20151111_1456.py:
    - Create model Like
    - Create model Likes
    - Alter unique_together for likes (1 constraint(s))
    - Alter unique_together for like (1 constraint(s))
root@85ce07612bfb:/taiga-back# python manage.py migrate
Trying import local.py settings...
Operations to perform:
  Synchronize unmigrated apps: mdrender, export_import, sr, raven_contrib_django, staticfiles, front, api, base, searches, locale, stats, _humanize, messages, django_transactional_cleanup, sitemaps, django_jinja, events
  Apply all migrations: userstorage, attachments, custom_attributes, tasks, history, admin, bitbucket, djmail, github, milestones, users, auth, projects, sessions, feedback, timeline, issues, userstories, notifications, votes, webhooks, gitlab, contenttypes, easy_thumbnails, references, wiki
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying projects.0028_auto_20151111_1456... OK
root@85ce07612bfb:/taiga-back# python manage.py migrate --list like
Trying import local.py settings...
Raven is not configured (logging is disabled). Please see the documentation for more information.
CommandError: No migrations present for: like
root@85ce07612bfb:/taiga-back#
```

```
root@85ce07612bfb:/taiga-back/taiga/projects/migrations# cat 0028_auto_20151111_1456.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0027_auto_20150916_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', auto_created=True, serialize=False)),
                ('object_id', models.PositiveIntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('content_type', models.ForeignKey(to='contenttypes.ContentType')),
                ('user', models.ForeignKey(related_name='likes', verbose_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'Likes',
            },
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', auto_created=True, serialize=False)),
                ('object_id', models.PositiveIntegerField()),
                ('count', models.PositiveIntegerField(verbose_name='count', default=0)),
                ('content_type', models.ForeignKey(to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Likes',
                'verbose_name_plural': 'Likes',
            },
        ),
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together=set([('content_type', 'object_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set([('content_type', 'object_id', 'user')]),
        ),
    ]
root@85ce07612bfb:/taiga-back/taiga/projects/migrations#
```

**Comment by superalex** [comment]
That's really strange...if you clone again the repo in another path, could you check if the likes migration file doesn't exist on that new folder neither?

**Comment by queeno** [comment]
Strangely enough, if I clone taiga-back to a new location and switch to the stable branch:

```
root@85ce07612bfb:/tmp/taiga-back# python manage.py migrate --list like
Trying import local.py settings...
Raven is not configured (logging is disabled). Please see the documentation for more information.
CommandError: No migrations present for: like
root@85ce07612bfb:/tmp/taiga-back# python manage.py migrate
Trying import local.py settings...
Operations to perform:
  Synchronize unmigrated apps: _humanize, django_transactional_cleanup, sr, export_import, api, raven_contrib_django, stats, events, locale, sitemaps, front, django_jinja, staticfiles, base, mdrender, searches, messages
  Apply all migrations: milestones, references, votes, external_apps, feedback, easy_thumbnails, notifications, timeline, sessions, userstories, attachments, djmail, auth, custom_attributes, bitbucket, github, projects, likes, userstorage, gitlab, admin, users, wiki, tasks, contenttypes, webhooks, issues, history
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying external_apps.0001_initial... OK
  Applying likes.0001_initial... OK
The following content types are stale and need to be deleted:

    projects | likes
    projects | like

Any objects related to these content types by a foreign key will also
be deleted. Are you sure you want to delete these content types?
If you're unsure, answer 'no'.

    Type 'yes' to continue, or 'no' to cancel: yes
root@85ce07612bfb:/tmp/taiga-back# python manage.py makemigrations
Trying import local.py settings...
No changes detected
root@85ce07612bfb:/tmp/taiga-back# python manage.py migrate --list like
Trying import local.py settings...
Raven is not configured (logging is disabled). Please see the documentation for more information.
CommandError: No migrations present for: like
root@85ce07612bfb:/tmp/taiga-back# python manage.py migrate
Trying import local.py settings...
Operations to perform:
  Synchronize unmigrated apps: sitemaps, api, mdrender, raven_contrib_django, django_jinja, django_transactional_cleanup, searches, messages, stats, _humanize, staticfiles, export_import, sr, base, events, front, locale
  Apply all migrations: userstorage, custom_attributes, likes, projects, auth, milestones, timeline, references, history, issues, github, gitlab, feedback, votes, attachments, bitbucket, sessions, admin, djmail, wiki, notifications, tasks, easy_thumbnails, userstories, contenttypes, external_apps, webhooks, users
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  No migrations to apply.
root@85ce07612bfb:/tmp/taiga-back# python manage.py migrate --list like
Trying import local.py settings...
Raven is not configured (logging is disabled). Please see the documentation for more information.
CommandError: No migrations present for: like
root@85ce07612bfb:/tmp/taiga-back#
```

**Comment by queeno** [comment]
And 0028 is not there either:
```
root@85ce07612bfb:/tmp/taiga-back/taiga/projects/migrations# ls -l
total 128
-rw-r--r-- 1 root root  6614 Nov 11 15:06 0001_initial.py
-rw-r--r-- 1 root root 13681 Nov 11 15:06 0002_auto_20140903_0920.py
-rw-r--r-- 1 root root   988 Nov 11 15:06 0003_auto_20140913_1710.py
-rw-r--r-- 1 root root   424 Nov 11 15:06 0004_auto_20141002_2337.py
-rw-r--r-- 1 root root   501 Nov 11 15:06 0005_membership_invitation_extra_text.py
-rw-r--r-- 1 root root   742 Nov 11 15:06 0006_auto_20141029_1040.py
-rw-r--r-- 1 root root   955 Nov 11 15:06 0007_auto_20141024_1011.py
-rw-r--r-- 1 root root  2258 Nov 11 15:06 0008_auto_20141024_1012.py
-rw-r--r-- 1 root root  1306 Nov 11 15:06 0009_auto_20141024_1037.py
-rw-r--r-- 1 root root   526 Nov 11 15:06 0010_project_modules_config.py
-rw-r--r-- 1 root root  1109 Nov 11 15:06 0011_auto_20141028_2057.py
-rw-r--r-- 1 root root   868 Nov 11 15:06 0012_auto_20141210_1009.py
-rw-r--r-- 1 root root   999 Nov 11 15:06 0013_auto_20141210_1040.py
-rw-r--r-- 1 root root   481 Nov 11 15:06 0014_userstorystatus_is_archived.py
-rw-r--r-- 1 root root   863 Nov 11 15:06 0015_auto_20141230_1212.py
-rw-r--r-- 1 root root  1630 Nov 11 15:06 0016_fix_json_field_not_null.py
-rw-r--r-- 1 root root   705 Nov 11 15:06 0017_fix_is_private_for_projects.py
-rw-r--r-- 1 root root  1055 Nov 11 15:06 0018_auto_20150219_1606.py
-rw-r--r-- 1 root root  1481 Nov 11 15:06 0019_auto_20150311_0821.py
-rw-r--r-- 1 root root   474 Nov 11 15:06 0020_membership_user_order.py
-rw-r--r-- 1 root root  1214 Nov 11 15:06 0021_auto_20150504_1524.py
-rw-r--r-- 1 root root  1338 Nov 11 15:06 0022_auto_20150701_0924.py
-rw-r--r-- 1 root root   812 Nov 11 15:06 0023_auto_20150721_1511.py
-rw-r--r-- 1 root root  1673 Nov 11 15:06 0024_auto_20150810_1247.py
-rw-r--r-- 1 root root  1449 Nov 11 15:06 0025_auto_20150901_1600.py
-rw-r--r-- 1 root root   825 Nov 11 15:06 0026_auto_20150911_1237.py
-rw-r--r-- 1 root root   741 Nov 11 15:06 0027_auto_20150916_1302.py
-rw-r--r-- 1 root root     0 Nov 11 15:06 __init__.py
drwxr-xr-x 2 root root  4096 Nov 11 15:06 __pycache__
root@85ce07612bfb:/tmp/taiga-back/taiga/projects/migrations#
```

**Comment by queeno** [comment]
And I can see now the like_likes and likes_likes tables in my postgres db!

```
 public | likes_like                                              | table | taiga
 public | likes_likes                                             | table | taiga
```

I can only assume there is something wrong with my [local.py](https://github.com/queeno/docker-taiga/blob/master/assets/config/docker-settings.py) file

**Comment by queeno** [comment]
I was indeed missing `taiga.projects.like` in INSTALLED_APPS within my local.py file.

Now my taiga 1.9 deployment works almost fine. Thanks @superalex !

The only error I see in the browser console is this failed GET request:

```
GET http://192.168.33.10:8000/api/v1/user-storage/joyride 404 (NOT FOUND)
```

Does it ring any bell to you?

**Comment by superalex** [comment]
Great @queeno we should have checked your local.py before :)

About your 404 API error, I think it happens because your user didn't skip or complete the joyride, could you check if it stops happening when you complete it?

**Comment by queeno** [comment]
Hey @superalex 

Not sure how to complete a joyride (I couldn't find anything in the docs either) however I messed around with my user profile and now it doesn't happen anymore.

Thanks very much for your time and help!

**Comment by superalex** [comment]
You are welcome!,


Joyrides it's just the new help for onboarding users that appears the first time you use taiga, if you click on "skip" it doesn't appear again :)

**Comment by queeno** [comment]
Oh I see! Yep it's quite a nice feature :+1: 
Thanks @superalex 

I have a last, totally unrelated question for you. I'm going behave well and open a new thread for that!
