### ISSUE TITLE
can't do python migrate

### ISSUE THREAD

**Issue by ASMfreaK** [taigaio/taiga-back#520]
Hello and thank you for the great project!
I'm tring to install Taiga on my server.
I'm using (production guide)[https://taigaio.github.io/taiga-doc/dist/setup-production.html] from taiga docs.
My server is running under Debian 7 wheezy with custom-built python3.4.
After setting up venv and pip installing requirements, i tried running 
`python3.4 manage.py migrate --noinput`
It ran for a bit and gave me this strange traceback:
```
(taiga) user@server:/path/to/taiga-back# python3.4 manage.py migrate
Trying import local.py settings...
Trying import development.py settings...
Traceback (most recent call last):
  File "/usr/share/pyservers/taiga-back/taiga/lib/python3.4/site-packages/django/apps/config.py", line 114, in create
    cls = getattr(mod, cls_name)
AttributeError: 'module' object has no attribute 'base'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/share/pyservers/taiga-back/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "/usr/share/pyservers/taiga-back/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 325, in execute
    django.setup()
  File "/usr/share/pyservers/taiga-back/taiga/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/share/pyservers/taiga-back/taiga/lib/python3.4/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/share/pyservers/taiga-back/taiga/lib/python3.4/site-packages/django/apps/config.py", line 119, in create
    import_module(entry)
  File "/usr/local/opt/python-3.4.1/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2224, in _find_and_load_unlocked
ImportError: No module named 'taiga.base'
```

What did I do wrong?

**Comment by superalex** [comment]
Are you sure there were no errors when installing the requirements?, could you please install them again and check the output to see if there are any errors?

**Comment by ASMfreaK** [comment]
here the output from `pip install --upgrade -r requirements.txt`
```
Requirement already up-to-date: future in ./taiga/lib/python3.4/site-packages (from pyjwkest==1.0.7->-r requirements.txt (line 34))
Requirement already up-to-date: anyjson>=0.3.3 in ./taiga/lib/python3.4/site-packages (from kombu<3.1,>=3.0.29->celery==3.1.19->-r requirements.txt (line 23))
Installing collected packages: Django, Pillow, Markdown, easy-thumbnails, django-ipware, django-pglocks
  Found existing installation: Django 1.8.5
    Uninstalling Django-1.8.5:
      Successfully uninstalled Django-1.8.5
  Found existing installation: Pillow 3.0.0
    Uninstalling Pillow-3.0.0:
      Successfully uninstalled Pillow-3.0.0
  Running setup.py install for Pillow
  Found existing installation: Markdown 2.6.3
    Uninstalling Markdown-2.6.3:
      Successfully uninstalled Markdown-2.6.3
  Running setup.py install for Markdown
  Found existing installation: easy-thumbnails 2.2
    Uninstalling easy-thumbnails-2.2:
      Successfully uninstalled easy-thumbnails-2.2
  Found existing installation: django-ipware 1.1.1
    Uninstalling django-ipware-1.1.1:
      Successfully uninstalled django-ipware-1.1.1
  Running setup.py install for django-ipware
  Found existing installation: django-pglocks 1.0.2
    Uninstalling django-pglocks-1.0.2:
      Successfully uninstalled django-pglocks-1.0.2
  Running setup.py install for django-pglocks
Successfully installed Django-1.8.6 Markdown-2.6.4 Pillow-2.9.0 django-ipware-1.1.2 django-pglocks-1.0.2 easy-thumbnails-2.2.1
```

As you can see - there are no errors. If it will help I'll restart installation from scratch and provide all the outputs.

**Comment by superalex** [comment]
I think restarting the installation could help, I really don't know what can be happening and if it can be related to using a custom-built for python3.4

**Comment by ASMfreaK** [comment]
I'll try reinstalling, but can you give an advice in process? 
I'm installing Taiga on Debian 7, which has only Python 3.2. What is the best way - in your opinion - to install Python 3.4 in it?

**Comment by superalex** [comment]
Sorry but I personally have no suggestions for it (I have no experience building custom python for debian) :(

**Comment by bameda** [comment]
You can try to use jessie;a packages or Ubuntu PPA like in http://unix.stackexchange.com/questions/188741/install-newer-older-versions-of-python-on-debian to install python 3.4 or 3.5, but the best solution is to use Ubuntu 14.04 which is the distro we use and on which runs our instance.

Note that Debian 7 was published in 2013.

**Comment by ASMfreaK** [comment]
I've built python 3.4.1 and installed it into `/usr/local/opt/python-3.4.1`. 
I'm creating venv in `taiga-back` by using
```
/usr/local/opt/python-3.4.1/bin/pyvenv taiga
source taiga/bin/activate
pip install -r requirements.txt
```
`pip` happily reports:
```
Successfully installed Django-1.8.6 Markdown-2.6.4 MarkupSafe-0.23 Pillow-2.9.0 Unidecode-0.4.18 amqp-1.4.7 anyjson-0.3.3 billiard-3.3.0
.21 bleach-1.4.2 celery-3.1.19 cssselect-0.9.1 cssutils-1.0.1 diff-match-patch-20121119 django-ipware-1.1.2 django-jinja-1.4.1 django-pg
json-0.3.1 django-pglocks-1.0.2 django-picklefield-0.3.2 django-sampledatahelper-0.3 django-sites-0.8 django-sr-0.0.4 django-transaction
-hooks-0.2 django-transactional-cleanup-0.1.15 djmail-0.11.0 djorm-pgarray-1.2 easy-thumbnails-2.2.1 fn-0.4.3 future-0.15.2 gunicorn-19.
3.0 html5lib-0.9999999 jinja2-2.8 kombu-3.0.29 lxml-3.5.0b1 premailer-2.9.6 psycopg2-2.6.1 pycrypto-2.6.1 pygments-2.0.2 pyjwkest-1.0.7
pytz-2015.7 raven-5.8.1 redis-2.10.3 requests-2.8.1 sampledata-0.3.7 six-1.10.0
```
But now `python manage.py migrate --noinput` reports the following:
```
rying import local.py settings...
Trying import development.py settings...
Raven is not configured (logging is disabled). Please see the documentation for more information.
Traceback (most recent call last):
  File "/usr/share/pyservers/taiga-back/taiga/lib/python3.4/site-packages/django/db/backends/base/base.py", line 130, in ensure_connecti
on
    self.connect()
  File "/usr/share/pyservers/taiga-back/taiga/lib/python3.4/site-packages/transaction_hooks/mixin.py", line 75, in connect
    super(TransactionHooksDatabaseWrapperMixin, self).connect(*a, **kw)
  File "/usr/share/pyservers/taiga-back/taiga/lib/python3.4/site-packages/django/db/backends/base/base.py", line 119, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/share/pyservers/taiga-back/taiga/lib/python3.4/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 176, in
get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/share/pyservers/taiga-back/taiga/lib/python3.4/site-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
psycopg2.OperationalError: FATAL:  role "root" does not exist
```
This was caused by doing everything under `root` user. I created `taiga` user and `python manage.py migrate --noinput` worked like a charm. Maybe you should add some words about creating a new user for Taiga in [production setup tutorial](https://taigaio.github.io/taiga-doc/dist/setup-production.html)? I hope I won't have any other problems with installation. Thank you for your help.

**Comment by superalex** [comment]
So it's finally working? :+1: 

We already had some words explicit about non using root -> https://taigaio.github.io/taiga-doc/dist/setup-production.html#_before_starting ...

**Comment by ASMfreaK** [comment]
It will work, but I will reinstall everything on my server just to get it clean. Thanks again for your help.

**Comment by superalex** [comment]
You are welcome! :+1:

**Comment by sivasai519** [comment]
Hello, 
I getting this error 
Trying import local.py settings...
Trying import development.py settings...
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: permission denied for relation django_migrations


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 83, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/loader.py", line 52, in __init__
    self.build_graph()
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/loader.py", line 203, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 66, in applied_migrations
    return set(tuple(x) for x in self.migration_qs.values_list("app", "name"))
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 256, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 1087, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 125, in __iter__
    for row in compiler.results_iter():
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 789, in results_iter
    results = self.execute_sql(MULTI)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 835, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: permission denied for relation django_migrations

could you suggest me any solution

**Comment by jespino** [comment]
@sivasai519 This is related to your permissions in your postgresql database.

**Comment by sivasai519** [comment]
I given permission to the database.

**Comment by jespino** [comment]
Sorry, but is what python says. You are trying to execute something that involve the django_migrations table, and you haven't permissions to do the action. Actually, looks like a read. Can you try to login into the database with the same credentials and try to execute `SELECT * FROM django_migrations;`?
