### ISSUE TITLE
Comments make python scripts bugging

### ISSUE THREAD

**Issue by Exaltia** [taigaio/taiga-back#527]
Hello,
I am in the process of installing taiga with following this procedure : http://taigaio.github.io/taiga-doc/dist/setup-production.html
There is a big problem in files encoding when getting the files from github.
Ubuntu version 14.04.03LTS

exaltia@Mattermost:~/taiga-back$ locale -a
C
C.UTF-8
en_US.utf8
fr_FR.utf8
POSIX
(Yes it's on the same Virtual machine as mattermost)
Linux Mattermost 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Content of /etc/python3/debian_config:
[DEFAULT]
byte-compile = standard

System was updated just before starting to follow your procedure

Here is a copy paste on 3 trys.
On each following trys i deleted all the comments on the .py problematic file to see the next step

exaltia@Mattermost:~/taiga-back$ python manage.py migrate --noinput
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 303, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/exaltia/taiga-back/settings/__init__.py", line 2
SyntaxError: Non-ASCII character '\xc3' in file /home/exaltia/taiga-back/settings/__init__.py on line 2, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
exaltia@Mattermost:~/taiga-back$ vi /home/exaltia/taiga-back/settings/__init__.py
exaltia@Mattermost:~/taiga-back$ cp /home/exaltia/taiga-back/settings/__init__.py  /home/exaltia/taiga-back/settings/__init__.pybackup
exaltia@Mattermost:~/taiga-back$ vi /home/exaltia/taiga-back/settings/__init__.py
exaltia@Mattermost:~/taiga-back$ python manage.py migrate --noinput
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 303, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/exaltia/taiga-back/settings/__init__.py", line 4, in <module>
    from .celery import *
  File "/home/exaltia/taiga-back/settings/celery.py", line 2
SyntaxError: Non-ASCII character '\xc3' in file /home/exaltia/taiga-back/settings/celery.py on line 2, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
exaltia@Mattermost:~/taiga-back$ vi /home/exaltia/taiga-back/settings/celery.py
exaltia@Mattermost:~/taiga-back$ python manage.py migrate --noinput
Trying import local.py settings...
Trying import development.py settings...
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 303, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/exaltia/taiga-back/settings/__init__.py", line 11, in <module>
    from .development import *
  File "/home/exaltia/taiga-back/settings/development.py", line 2
SyntaxError: Non-ASCII character '\xc3' in file /home/exaltia/taiga-back/settings/development.py on line 2, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

**Comment by bameda** [comment]
You are using python 2.7 instead python 3

exaltia@Mattermost:~/taiga-back$ python manage.py migrate --noinput
Traceback (most recent call last):
File "manage.py", line 10, in 
execute_from_command_line(sys.argv)
File "/usr/local/lib/**python2.7**/dist-packages/django/core/management/init.py", line 354, in execute_from_command_line
utility.execute()

Create o access to the taiga virtualenv to works with python3

**Comment by Exaltia** [comment]
Awwww... sorry for such a basic mistake... 
Thanks for the hint. You can close it again

**Comment by bameda** [comment]
You are welcome.

Don't worry :-), it can happen to anyone.


Regards
