### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by ruthio** [taigaio/taiga-back#538]
```
[01/Dec/2015 03:10:37] "POST /api/v1/memberships/bulk_create HTTP/1.0" 500 27
ERROR:2015-12-01 03:14:37,593: Internal Server Error: /api/v1/memberships/bulk_create
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/src/taiga-back/taiga/base/api/viewsets.py", line 81, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/src/taiga-back/taiga/base/api/views.py", line 420, in dispatch
    response = self.handle_exception(exc)
  File "/usr/src/taiga-back/taiga/base/api/views.py", line 417, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/src/taiga-back/taiga/projects/api.py", line 463, in bulk_create
    precall=self.pre_save)
  File "/usr/src/taiga-back/taiga/projects/services/members.py", line 31, in create_members_in_bulk
    db.save_in_bulk(members, callback, precall)
  File "/usr/local/lib/python3.5/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/usr/src/taiga-back/taiga/base/utils/db.py", line 93, in save_in_bulk
    callback(instance, created=created)
  File "/usr/src/taiga-back/taiga/projects/api.py", line 498, in post_save
    services.send_invitation(invitation=object)
  File "/usr/src/taiga-back/taiga/projects/services/invitations.py", line 16, in send_invitation
    email.send()
  File "/usr/local/lib/python3.5/site-packages/django/core/mail/message.py", line 303, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/usr/local/lib/python3.5/site-packages/django/core/mail/backends/console.py", line 36, in send_messages
    self.write_message(message)
  File "/usr/local/lib/python3.5/site-packages/django/core/mail/backends/console.py", line 23, in write_message
    self.stream.write('%s\n' % msg_data)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 536-537: ordinal not in range(128)
10.20.96.145 - - [01/Dec/2015:03:14:37 +0000] "POST /api/v1/memberships/bulk_create HTTP/1.1" 500 38 "http://10.20.102.38:8081/project/wotefa-jian-wang-3-2015/admin/memberships" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0" "-"
```

**Comment by superalex** [comment]
Hello @ruthio 

It seems that you are not using virtualenv in your taiga instance, is it possible?, our instructions include how to configure it, did you follow them?

The encode/decode error sounds like a problem with your python or environment variables. Could you please check the info in these other two issues?:

https://github.com/taigaio/taiga-back/issues/298
https://github.com/taigaio/taiga-back/issues/297

Regards,

**Comment by yomguy** [comment]
I add the same error until I set the good language against the OS env one and also setup the django settings explicitely with this:
```
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = False
EMAIL_HOST = 'localhost'
EMAIL_PORT = 25
DEFAULT_FROM_EMAIL = 'foo@bar.com'
```

**Comment by bameda** [comment]
@yomguy 
Check if you are using UTF-8

```
locale  
```

And try to add in the taiga user .bashrc 

```bash
export LANG=en_US.UTF-8
export LC_TYPE=en_US.UTF-8
```

**Comment by yomguy** [comment]
yes, that's what I've done for another language ;)
thanks
