### ISSUE TITLE
psycopg2.OperationalError: FATAL:  role "admin" does not exist

### ISSUE THREAD

**Issue by allan-simon** [taigaio/taiga-back#544]
Hello I'm trying to deploy an instance from stable branch and when i try to create the database 

```
python manage.py migrate --noinput
```

I got 

```
Trying import local.py settings...
Trying import development.py settings...
Raven is not configured (logging is disabled). Please see the documentation for more information.
Traceback (most recent call last):
  File "/home/admin/taiga-back/taiga/lib/python3.4/site-packages/django/db/backends/base/base.py", line 130, in ensure_connection
    self.connect()
  File "/home/admin/taiga-back/taiga/lib/python3.4/site-packages/transaction_hooks/mixin.py", line 75, in connect
    super(TransactionHooksDatabaseWrapperMixin, self).connect(*a, **kw)
  File "/home/admin/taiga-back/taiga/lib/python3.4/site-packages/django/db/backends/base/base.py", line 119, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/admin/taiga-back/taiga/lib/python3.4/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 176, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/admin/taiga-back/taiga/lib/python3.4/site-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
psycopg2.OperationalError: FATAL:  role "admin" does not exist


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/admin/taiga-back/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/admin/taiga-back/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/admin/taiga-back/taiga/lib/python3.4/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/admin/taiga-back/taiga/lib/python3.4/site-packages/raven/contrib/django/management/__init__.py", line 41, in new_execute
    return original_func(self, *args, **kwargs)
  File "/home/admin/taiga-back/taiga/lib/python3.4/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/home/admin/taiga-back/taiga/lib/python3.4/site-packages/django/core/management/commands/migrate.py", line 93, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/home/admin/taiga-back/taiga/lib/python3.4/site-packages/django/db/migrations/executor.py", line 19, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/home/admin/taiga-back/taiga/lib/python3.4/site-packages/django/db/migrations/loader.py", line 47, in __init__
    self.build_graph()
  File "/home/admin/taiga-back/taiga/lib/python3.4/site-packages/django/db/migrations/loader.py", line 188, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/home/admin/taiga-back/taiga/lib/python3.4/site-packages/django/db/migrations/recorder.py", line 59, in applied_migrations
    self.ensure_schema()
  File "/home/admin/taiga-back/taiga/lib/python3.4/site-packages/django/db/migrations/recorder.py", line 49, in ensure_schema
    if self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor()):
  File "/home/admin/taiga-back/taiga/lib/python3.4/site-packages/django/db/backends/base/base.py", line 162, in cursor
    cursor = self.make_debug_cursor(self._cursor())
  File "/home/admin/taiga-back/taiga/lib/python3.4/site-packages/django/db/backends/base/base.py", line 135, in _cursor
    self.ensure_connection()
  File "/home/admin/taiga-back/taiga/lib/python3.4/site-packages/django/db/backends/base/base.py", line 130, in ensure_connection
    self.connect()
  File "/home/admin/taiga-back/taiga/lib/python3.4/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/admin/taiga-back/taiga/lib/python3.4/site-packages/django/utils/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "/home/admin/taiga-back/taiga/lib/python3.4/site-packages/django/db/backends/base/base.py", line 130, in ensure_connection
    self.connect()
  File "/home/admin/taiga-back/taiga/lib/python3.4/site-packages/transaction_hooks/mixin.py", line 75, in connect
    super(TransactionHooksDatabaseWrapperMixin, self).connect(*a, **kw)
  File "/home/admin/taiga-back/taiga/lib/python3.4/site-packages/django/db/backends/base/base.py", line 119, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/admin/taiga-back/taiga/lib/python3.4/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 176, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/admin/taiga-back/taiga/lib/python3.4/site-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
django.db.utils.OperationalError: FATAL:  role "admin" does not exist
```

**Comment by allan-simon** [comment]
my bad,  I needed to replace "taiga" by my own username in 

```
sudo -u postgres createuser taiga
sudo -u postgres createdb taiga -O taiga
```

sorry for the noise

**Comment by superalex** [comment]
Don't worry! :+1:

**Comment by el3ctron** [comment]
this post was util for me! thanks!

**Comment by allan-simon** [comment]
@el3ctron  happy to hear that, that's why I usually don't hesitate to put the problem i encounter as long as i spend more than a dozen of minutes to search, especially if google was not helpful , so that other can make use of my errands :)

**Comment by aminghasemi** [comment]
thanks a lot, this post solves my problem!
