### ISSUE TITLE
is_owner / is_admin mismatch

### ISSUE THREAD

**Issue by smarek** [taigaio/taiga-back#636]
Hi, 

recently I've upgraded stable to latest revision, and even after having all the migrations run, there was problem with `is_owner` vs. `is_admin` column naming.

I have manually renamed the column `is_admin` to `is_owner`, and the problem was fixed, but I don't know how things could have gotten to such state.

Could you please let me know, if there is anything you know about that could cause such problems, or if it is possible to create a fixup for this, so it won't happen in the future?

Thank you

Stacktrace as follows (from `gunicorn.stdout.log`):
```
Internal Server Error: /api/v1/projects
Traceback (most recent call last):
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: column projects_membership.is_owner does not exist
LINE 1: ...p"."project_id", "projects_membership"."role_id", "projects_...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/viewsets.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/views.py", line 444, in dispatch
    response = self.handle_exception(exc)
  File "/home/taiga/taiga-back/taiga/base/api/views.py", line 441, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/mixins.py", line 139, in list
    return response.Ok(serializer.data)
  File "/home/taiga/taiga-back/taiga/base/api/serializers.py", line 613, in data
    self._data = [self.to_native(item) for item in obj]
  File "/home/taiga/taiga-back/taiga/base/api/serializers.py", line 613, in <listcomp>
    self._data = [self.to_native(item) for item in obj]
  File "/home/taiga/taiga-back/taiga/base/api/serializers.py", line 396, in to_native
    value = field.field_to_native(obj, field_name)
  File "/home/taiga/taiga-back/taiga/base/api/fields.py", line 1082, in field_to_native
    value = getattr(self.parent, self.method_name)(obj)
  File "/home/taiga/taiga-back/taiga/projects/serializers.py", line 266, in get_my_permissions
    return get_user_project_permissions(self.context["request"].user, obj)
  File "/home/taiga/taiga-back/taiga/permissions/service.py", line 80, in get_user_project_permissions
    membership = _get_user_project_membership(user, project)
  File "/home/taiga/taiga-back/taiga/permissions/service.py", line 28, in _get_user_project_membership
    return user.cached_membership_for_project(project)
  File "/home/taiga/taiga-back/taiga/users/models.py", line 159, in cached_membership_for_project
    self._fill_cached_memberships()
  File "/home/taiga/taiga-back/taiga/users/models.py", line 147, in _fill_cached_memberships
    for membership in qs.all():
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/models/query.py", line 162, in __iter__
    self._fetch_all()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/utils/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column projects_membership.is_owner does not exist
LINE 1: ...p"."project_id", "projects_membership"."role_id", "projects_...
```

**Comment by superalex** [comment]
Hello @smarek 

Right now there is no reference for is_admin in the stable branch, those references only exist in master. Is it possible you executed the migrations in master branch before checking out to stable?

**Comment by smarek** [comment]
It is indeed possible, because somehow the Git was merged incorrectly at the time I ran db migrations.
Is it possible to check current DB state/consistency, if it equals current state of Taiga-Back ?

**Comment by smarek** [comment]
Probably this could be connected, now, when I access API userstories, error will roll out

```
Internal Server Error: /api/v1/userstories
Traceback (most recent call last):
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/home/taiga/taiga-back/taiga/base/response.py", line 98, in rendered_content
    ret = renderer.render(self.data, media_type, context)
  File "/home/taiga/taiga-back/taiga/base/api/renderers.py", line 632, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/home/taiga/taiga-back/taiga/base/api/renderers.py", line 582, in get_context
    raw_data_post_form = self.get_raw_data_form(view, "POST", request)
  File "/home/taiga/taiga-back/taiga/base/api/renderers.py", line 532, in get_raw_data_form
    content = renderer.render(serializer.data, accepted, context)
  File "/home/taiga/taiga-back/taiga/base/api/serializers.py", line 615, in data
    self._data = self.to_native(obj)
  File "/home/taiga/taiga-back/taiga/projects/notifications/mixins.py", line 242, in to_native
    obj.is_watcher = user.id in obj.watchers
AttributeError: 'NoneType' object has no attribute 'watchers'
```

**Comment by smarek** [comment]
Regarding state of things, I'm looking for most reliable way to backup / restore projects, #100 mentions `dump_project`/`load_dump`, those I did and they passed, but that doesn't necessarily mean that importing it will be successfull, is it?
Is, after, simply importing it and running the migrations enough to restore fully working state of taiga-back?

**Comment by superalex** [comment]
You could try fixing your database executing 

```
python manage.py makemigrations
python manage.py migrate
```

That way django should detect the differences between your tables and the specified in the models files and generate some migrations scripts executed by the migrate command.

**Comment by smarek** [comment]
well, I don't know, if this output is good or bad news.

```
(taiga)taiga@smarek:/home/taiga/taiga-back$ python manage.py makemigrations
Trying import local.py settings...
No changes detected
(taiga)taiga@smarek:/home/taiga/taiga-back$ python manage.py migrate
Trying import local.py settings...
Operations to perform:
  Synchronize unmigrated apps: messages, sr, locale, api, _humanize, mdrender, stats, front, sitemaps, django_transactional_cleanup, staticfiles, searches, django_jinja, export_import, events, raven_contrib_django, base
  Apply all migrations: likes, sessions, feedback, attachments, references, easy_thumbnails, github, users, userstorage, wiki, custom_attributes, webhooks, admin, notifications, gitlab, external_apps, timeline, milestones, history, projects, auth, userstories, djmail, votes, tasks, contenttypes, issues, bitbucket
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  No migrations to apply.
```

**Comment by superalex** [comment]
Are you in master branch for both taiga-back and taiga-front and it keeps failing?

**Comment by smarek** [comment]
@superalex sorry for delay, no, i'm in stable branches in both. and it currently works, it's not failing to work, but i wonder about current state / stability.

**Comment by superalex** [comment]
If should be safe if using stable branch ;)

Regards!,
