### ISSUE TITLE
unable to add comment to the issue

### ISSUE THREAD

**Issue by adrian-wi** [taigaio/taiga-back#646]
Hi I have installed my own production taiga version on ubuntu 14.04 
When I try to add new comment to the issue I am getting the following error: 

[01/Mar/2016 22:22:44] "OPTIONS /api/v1/projects?member=4&order_by=memberships__user_order HTTP/1.1" 200 0
[01/Mar/2016 22:22:45] "OPTIONS /api/v1/projects/by_slug?slug=admin-beautysite HTTP/1.1" 200 0
[01/Mar/2016 22:22:45] "GET /api/v1/projects?member=4&order_by=memberships__user_order HTTP/1.1" 200 1949
[01/Mar/2016 22:22:45] "GET /api/v1/projects/by_slug?slug=admin-beautysite HTTP/1.1" 200 7610
[01/Mar/2016 22:22:46] "OPTIONS /api/v1/issues/by_ref?page=1&project=3&ref=1 HTTP/1.1" 200 0
[01/Mar/2016 22:22:46] "GET /api/v1/issues/by_ref?page=1&project=3&ref=1 HTTP/1.1" 200 1281
[01/Mar/2016 22:22:46] "OPTIONS /api/v1/history/issue/1 HTTP/1.1" 200 0
[01/Mar/2016 22:22:46] "OPTIONS /api/v1/issues/custom-attributes-values/1 HTTP/1.1" 200 0
[01/Mar/2016 22:22:46] "OPTIONS /api/v1/issues/attachments?object_id=1&project=3 HTTP/1.1" 200 0
[01/Mar/2016 22:22:46] "GET /api/v1/history/issue/1 HTTP/1.1" 200 1183
[01/Mar/2016 22:22:47] "GET /api/v1/issues/custom-attributes-values/1 HTTP/1.1" 200 51
[01/Mar/2016 22:22:47] "GET /api/v1/issues/attachments?object_id=1&project=3 HTTP/1.1" 200 2
[01/Mar/2016 22:22:54] "OPTIONS /api/v1/issues/1 HTTP/1.1" 200 0
Raven is not configured (logging is disabled). Please see the documentation for more information.
ERROR:2016-03-01 22:22:54,431: Internal Server Error: /api/v1/issues/1
Traceback (most recent call last):
  File "/home/gearsoft/.virtualenvs/taiga/lib/python3.4/site-packages/django_sites/base.py", line 85, in get_by_id
    return Site(sites[id])
KeyError: 'front'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gearsoft/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gearsoft/taiga-back/taiga/base/api/viewsets.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/gearsoft/.virtualenvs/taiga/lib/python3.4/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/gearsoft/taiga-back/taiga/base/api/views.py", line 444, in dispatch
    response = self.handle_exception(exc)
  File "/home/gearsoft/taiga-back/taiga/base/api/views.py", line 441, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/gearsoft/taiga-back/taiga/base/api/mixins.py", line 199, in partial_update
 return self.update(request, *args, **kwargs)
  File "/home/gearsoft/taiga-back/taiga/projects/issues/api.py", line 144, in update
    return super().update(request, *args, **kwargs)
  File "/usr/lib/python3.4/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/home/gearsoft/taiga-back/taiga/base/decorators.py", line 60, in decorator
    return func(self, *args, **kwargs)
  File "/home/gearsoft/taiga-back/taiga/base/api/mixins.py", line 194, in update
    self.post_save(self.object, created=False)
  File "/home/gearsoft/taiga-back/taiga/projects/occ/mixins.py", line 84, in post_save
    super().post_save(obj, created)
  File "/home/gearsoft/taiga-back/taiga/projects/history/mixins.py", line 73, in post_save
    self.persist_history_snapshot(obj=obj)
  File "/home/gearsoft/taiga-back/taiga/projects/history/mixins.py", line 67, in persist_history_snapshot
    notifications_services.analize_object_for_watchers(obj, comment, user)
  File "/home/gearsoft/taiga-back/taiga/projects/notifications/services.py", line 111, in analize_object_for_watchers
    _, data = mdr.render_and_extract(obj.get_project(), "\n".join(texts))
  File "/home/gearsoft/taiga-back/taiga/mdrender/service.py", line 122, in render_and_extract
    result = bleach.clean(md.convert(text))
  File "/home/gearsoft/.virtualenvs/taiga/lib/python3.4/site-packages/markdown/__init__.py", line 375, in convert
    newRoot = treeprocessor.run(root)
  File "/home/gearsoft/taiga-back/taiga/mdrender/extensions/target_link.py", line 38, in run
    home_url = resolve("home")
  File "/home/gearsoft/taiga-back/taiga/front/templatetags/functions.py", line 27, in resolve
    site = get_site_by_id("front")
  File "/home/gearsoft/.virtualenvs/taiga/lib/python3.4/site-packages/django_sites/base.py", line 87, in get_by_id
    raise exceptions.SiteNotFound("Site with id '{}' not found".format(id))
django_sites.exceptions.SiteNotFound: Site with id 'front' not found
[01/Mar/2016 22:23:04] "PATCH /api/v1/issues/1 HTTP/1.1" 500 37

Can anybody help?

**Comment by bameda** [comment]
```
django_sites.exceptions.SiteNotFound: Site with id 'front' not found
```

According to taiga setup documentation you have to add to settings/local.py

```
SITES["front"] = {
    "domain": "example.com",     # the host of your taiga-front client
    "scheme": "http",                   # http or htps
    "name": "front"
}
```

**Comment by adrian-wi** [comment]
my settings/local.py file looks like : 
MEDIA_URL = "http://<my ip>/media/"
STATIC_URL = "http://<my ip>/static/"
ADMIN_MEDIA_PREFIX = "http://<my ip>/static/admin/"
SITES["front"]["scheme"] = "http"
SITES["front"]["domain"] = "<my ip>:80"

and front is available under <my ip>:80

**Comment by bameda** [comment]
`SITES["front"]["domain"]` must be a host not `:80`

**Comment by adrian-wi** [comment]
I have tried both, with and without, and getting the same error

**Comment by bameda** [comment]
Have you restarted taiga-back server???

**Comment by adrian-wi** [comment]
Yes

**Comment by bameda** [comment]
try this:
```
cd taiga-back
workon taiga
./manage.py shell

from django.conf import settings
getattr(settings, "SITES", None)
```
and paste the output here
