### ISSUE TITLE
problem with sending emails

### ISSUE THREAD

**Issue by adrian-wi** [taigaio/taiga-back#649]
Hi, I have my own taiga production instance,  I have added external email provider smtp settings as described: 
https://poczta.onet.pl/pomoc/13224,0,,6,0,37,2,0,,pomoc.html
and user and password, but i am always getting: 

[02/Mar/2016 23:56:22] "OPTIONS /api/v1/issues/1 HTTP/1.1" 200 0
Raven is not configured (logging is disabled). Please see the documentation for more information.
ERROR:2016-03-02 23:57:23,677: Internal Server Error: /api/v1/issues/1
Traceback (most recent call last):
  File "/home/gearsoft/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gearsoft/taiga-back/taiga/base/api/viewsets.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/gearsoft/.virtualenvs/taiga/lib/python3.4/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/gearsoft/taiga-back/taiga/base/api/views.py", line 444, in dispatch
    response = self.handle_exception(exc)
  File "/home/gearsoft/taiga-back/taiga/base/api/views.py", line 441, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/gearsoft/taiga-back/taiga/base/api/mixins.py", line 199, in partial_update
    return self.update(request, *args, **kwargs)
  File "/home/gearsoft/taiga-back/taiga/projects/issues/api.py", line 144, in update
    return super().update(request, *args, **kwargs)
  File "/usr/lib/python3.4/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/home/gearsoft/taiga-back/taiga/base/decorators.py", line 60, in decorator
    return func(self, *args, **kwargs)
  File "/home/gearsoft/taiga-back/taiga/base/api/mixins.py", line 194, in update
    self.post_save(self.object, created=False)
  File "/home/gearsoft/taiga-back/taiga/projects/occ/mixins.py", line 84, in post_save
    super().post_save(obj, created)
  File "/home/gearsoft/taiga-back/taiga/projects/history/mixins.py", line 74, in post_save
    super().post_save(obj, created=created)
  File "/home/gearsoft/taiga-back/taiga/projects/notifications/mixins.py", line 106, in post_save
    self.send_notifications(obj)
  File "/home/gearsoft/taiga-back/taiga/projects/notifications/mixins.py", line 103, in send_notifications
    services.send_notifications(obj, history=history)
  File "/usr/lib/python3.4/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/home/gearsoft/taiga-back/taiga/projects/notifications/services.py", line 236, in send_notifications
    send_sync_notifications(notification.id)
  File "/usr/lib/python3.4/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/home/gearsoft/taiga-back/taiga/projects/notifications/services.py", line 293, in send_sync_notifications
    email.send(user.email, context, headers=headers)
  File "/home/gearsoft/.virtualenvs/taiga/lib/python3.4/site-packages/djmail/template_mail.py", line 125, in send
    return email.send()
  File "/home/gearsoft/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/mail/message.py", line 303, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/home/gearsoft/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/mail/backends/smtp.py", line 100, in send_messages
    new_conn_created = self.open()
  File "/home/gearsoft/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/mail/backends/smtp.py", line 58, in open
    self.connection = connection_class(self.host, self.port, **connection_params)
  File "/usr/lib/python3.4/smtplib.py", line 242, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.4/smtplib.py", line 323, in connect
    (code, msg) = self.getreply()
  File "/usr/lib/python3.4/smtplib.py", line 376, in getreply
    raise SMTPServerDisconnected("Connection unexpectedly closed")
smtplib.SMTPServerDisconnected: Connection unexpectedly closed
[02/Mar/2016 23:58:23] "PATCH /api/v1/issues/1 HTTP/1.1" 500 37

Does anyone have an idea, what might be wrong,  (emails setting I have used, work with different applications)

**Comment by superalex** [comment]
Could you show us your local.py settings file please?, it seems like a configuration issue.

Regards,

**Comment by adrian-wi** [comment]
so I tried with different emails providers, now I tried o2 settings:

http://pomoc.o2.pl/id,16791062,pytanie.html?ticaid=61695b

my local.py looks like:

from .development import *


MEDIA_URL = "http://<my ip>/media/"
STATIC_URL = "http://<my ip>/static/"
ADMIN_MEDIA_PREFIX = "http://<my ip>/static/admin/"


SECRET_KEY = "theveryultratopsecretkey"

DEBUG = False
TEMPLATE_DEBUG = False
PUBLIC_REGISTER_ENABLED = True

DEFAULT_FROM_EMAIL = "biuro@beautysite.pl"
SERVER_EMAIL = DEFAULT_FROM_EMAIL


#DEBUG = False

#ADMINS = (
#    ("Admin", "example@example.com"),
#)

DATABASES = {
    'default': {
        'ENGINE': 'transaction_hooks.backends.postgresql_psycopg2',
        'NAME': 'taiga',
        'USER': 'taiga',
        'PASSWORD': '<my db password>',
        'HOST': 'localhost',
        'PORT': '',
    }
}

SITES = {
    "api": {
       "scheme": "http",
       "domain": "<my ip>:8000",
       "name": "api"
    },
    "front": {
       "scheme": "http",
       "domain": "<my ip>"
    }
}



# EMAIL SETTINGS EXAMPLE
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = False
EMAIL_HOST = 'poczta.o2.pl'
EMAIL_PORT = 465
EMAIL_HOST_USER = 'mymail@o2.pl'
EMAIL_HOST_PASSWORD = 'mypassword'
DEFAULT_FROM_EMAIL = "mymail@o2.pl"

# GMAIL SETTINGS EXAMPLE
#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#EMAIL_USE_TLS = True
#EMAIL_HOST = 'smtp.gmail.com'
#EMAIL_PORT = 587
#EMAIL_HOST_USER = 'biuro@beautysite.pl'
#EMAIL_HOST_PASSWORD = 'mypassword'


I also have an email in gmail, but with gmail settings I was getting the
following error message:

http://joequery.me/guides/python-smtp-authenticationerror/
I have verified my ceredentials couple of times (and they were correct) I
have also disabled captcha, but still no luck...





2016-03-03 7:50 GMT+01:00 Alejandro <notifications@github.com>:

**Comment by superalex** [comment]
Everythin seems to be ok, are you sure your taiga installation can reach the external network?

**Comment by bameda** [comment]
Have you try to enable TLS??? (http://imap.poczta.o2.pl/thebat.php)


EMAIL_USE_TLS = True


On Thu, Mar 3, 2016 at 10:59 AM, adrian-wi <notifications@github.com> wrote:

> so I tried with different emails providers, now I tried o2 settings:
>
> http://pomoc.o2.pl/id,16791062,pytanie.html?ticaid=61695b
>
> my local.py looks like:
>
> from .development import *
>
>
> MEDIA_URL = "http://<my ip>/media/"
> STATIC_URL = "http://<my ip>/static/"
> ADMIN_MEDIA_PREFIX = "http://<my ip>/static/admin/"
>
>
> SECRET_KEY = "theveryultratopsecretkey"
>
> DEBUG = False
> TEMPLATE_DEBUG = False
> PUBLIC_REGISTER_ENABLED = True
>
> DEFAULT_FROM_EMAIL = "biuro@beautysite.pl"
> SERVER_EMAIL = DEFAULT_FROM_EMAIL
>
>
> #DEBUG = False
>
> #ADMINS = (
> # ("Admin", "example@example.com"),
> #)
>
> DATABASES = {
> 'default': {
> 'ENGINE': 'transaction_hooks.backends.postgresql_psycopg2',
> 'NAME': 'taiga',
> 'USER': 'taiga',
> 'PASSWORD': '<my db password>',
> 'HOST': 'localhost',
> 'PORT': '',
> }
> }
>
> SITES = {
> "api": {
> "scheme": "http",
> "domain": "<my ip>:8000",
> "name": "api"
> },
> "front": {
> "scheme": "http",
> "domain": "<my ip>"
> }
> }
>
>
>
> # EMAIL SETTINGS EXAMPLE
> EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
> EMAIL_USE_TLS = False
> EMAIL_HOST = 'poczta.o2.pl'
> EMAIL_PORT = 465
> EMAIL_HOST_USER = 'mymail@o2.pl'
> EMAIL_HOST_PASSWORD = 'mypassword'
> DEFAULT_FROM_EMAIL = "mymail@o2.pl"
>
> # GMAIL SETTINGS EXAMPLE
> #EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
> #EMAIL_USE_TLS = True
> #EMAIL_HOST = 'smtp.gmail.com'
> #EMAIL_PORT = 587
> #EMAIL_HOST_USER = 'biuro@beautysite.pl'
> #EMAIL_HOST_PASSWORD = 'mypassword'
>
>
> I also have an email in gmail, but with gmail settings I was getting the
> following error message:
>
> http://joequery.me/guides/python-smtp-authenticationerror/
> I have verified my ceredentials couple of times (and they were correct) I
> have also disabled captcha, but still no luck...
>
>
>
>
>
> 2016-03-03 7:50 GMT+01:00 Alejandro <notifications@github.com>:
>
> > Could you show us your local.py settings file please?, it seems like a
> > configuration issue.
> >
> > Regards,
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/taigaio/taiga-back/issues/649#issuecomment-191613829
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/taigaio/taiga-back/issues/649#issuecomment-191689588>.
>



-- 

---


*David Barragán Merino*
* Engineer *
<david.barragan@kaleidos.net>
david.barragan@kaleidos.net  | Tel: (+34) 913562995
www.kaleidos.net/FFF8E7

**Comment by bameda** [comment]
Hi @adrian-wi, is this resolved?

**Comment by adrian-wi** [comment]
Not yet

**Comment by superalex** [comment]
Did you check that your taiga installation can reach the external network?

**Comment by superalex** [comment]
@adrian-wi did you check this one?

**Comment by TLDay** [comment]
I faced this issue 20 minutes ago, my taiga installation could reach the external network perfectly, and configuration was absolutely correct. At last, changed `EMAIL_USE_TLS` to `EMAIL_USE_SSL` solved  my question. Maybe it's useful for someone.

**Comment by TLDay** [comment]
Taiga is really an amazing product. I love it.

**Comment by themightychris** [comment]
Using SSL instead of TLS as @TLDay just fixed an issue I was seeing trying to use mailgun where any request that tried to send an email would just time out and fail without error
