### ISSUE TITLE
Unable to add existing user to project

### ISSUE THREAD

**Issue by Jaredmmx** [taigaio/taiga-back#655]
I am unable to add an existing user to a project. I get error 500. 

ERROR:2016-03-04 12:17:07,223: Internal Server Error: /api/v1/memberships/bulk_create
Traceback (most recent call last):
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/viewsets.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/views.py", line 444, in dispatch
    response = self.handle_exception(exc)
  File "/home/taiga/taiga-back/taiga/base/api/views.py", line 441, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/taiga/taiga-back/taiga/projects/api.py", line 530, in bulk_create
    precall=self.pre_save)
  File "/home/taiga/taiga-back/taiga/projects/services/members.py", line 31, in create_members_in_bulk
    db.save_in_bulk(members, callback, precall)
  File "/usr/lib/python3.4/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/home/taiga/taiga-back/taiga/base/utils/db.py", line 96, in save_in_bulk
    callback(instance, created=created)
  File "/home/taiga/taiga-back/taiga/projects/api.py", line 565, in post_save
    services.send_invitation(invitation=object)
  File "/home/taiga/taiga-back/taiga/projects/services/invitations.py", line 16, in send_invitation
    email.send()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/mail/message.py", line 303, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/mail/backends/smtp.py", line 100, in send_messages
    new_conn_created = self.open()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/mail/backends/smtp.py", line 58, in open
    self.connection = connection_class(self.host, self.port, **connection_params)
  File "/usr/lib/python3.4/smtplib.py", line 242, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.4/smtplib.py", line 321, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.4/smtplib.py", line 292, in _get_socket
    self.source_address)
  File "/usr/lib/python3.4/socket.py", line 494, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.4/socket.py", line 533, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

That user already has part in another two projects.

I send Request Headers and Payload in PNG
I send Response HTML in zip file

[response.zip](https://github.com/taigaio/taiga-back/files/158644/response.zip)
![captura](https://cloud.githubusercontent.com/assets/7081952/13527129/c8ba5806-e204-11e5-9c4f-715a6b739313.PNG)

**Comment by Jaredmmx** [comment]
Thanks... I just couldn't find the path to the problem. I was so easy as setting up dns resolution.

**Comment by superalex** [comment]
Great!, should we close the issue?

**Comment by Jaredmmx** [comment]
Sure! Thanks!
