### ISSUE TITLE
Error while executing python manage.py migrate --noinput

### ISSUE THREAD

**Issue by florisvanwoudenberg** [taigaio/taiga-back#685]
ImportError: Could not import 'taiga.external_apps.auth_backends.Token' for API setting 'DEFAULT_AUTHENTICATION_CLASSES'. ImportError: /home/taiga/.virtualenvs/taiga/lib/python3.4/lib-dynload/_ctypes.cpython-34m-x86_64-linux-gnu.so: undefined symbol: _PyTraceback_Add.

**Comment by cmthomps** [comment]
Same problem here.  Trying to upgrade from 1.9.1 to 1.2.0.

**Comment by cmthomps** [comment]
Actually.  Mine might be slightly different.  Here is the full error:

(taiga)administrator@taiga:~/taiga-back$ python manage.py migrate --noinput
Trying import local.py settings...
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/administrator/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/administrator/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/home/administrator/.virtualenvs/taiga/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/administrator/.virtualenvs/taiga/lib/python3.4/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/administrator/.virtualenvs/taiga/lib/python3.4/site-packages/django/apps/config.py", line 116, in create
    mod = import_module(mod_path)
  File "/home/administrator/.virtualenvs/taiga/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/administrator/.virtualenvs/taiga/lib/python3.4/site-packages/taiga_contrib_ldap_auth/apps.py", line 20, in <module>
    from taiga.auth.services import register_auth_plugin
  File "/home/administrator/taiga-back/taiga/auth/services.py", line 34, in <module>
    from taiga.base.mails import mail_builder
  File "/home/administrator/taiga-back/taiga/base/mails.py", line 20, in <module>
    from djmail import template_mail
  File "/home/administrator/.virtualenvs/taiga/lib/python3.4/site-packages/djmail/template_mail.py", line 14, in <module>
    from . import models
  File "/home/administrator/.virtualenvs/taiga/lib/python3.4/site-packages/djmail/models.py", line 24, in <module>
    class Message(models.Model):
  File "/home/administrator/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/models/base.py", line 94, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/home/administrator/.virtualenvs/taiga/lib/python3.4/site-packages/django/apps/registry.py", line 239, in get_containing_app_config
    self.check_apps_ready()
  File "/home/administrator/.virtualenvs/taiga/lib/python3.4/site-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

**Comment by superalex** [comment]
Did you update the requirements?

`pip install -r requirements.txt`

**Comment by cmthomps** [comment]
Yes.  This was the last line of output from that process.

Successfully installed Django django-sampledatahelper gunicorn Pillow amqp djmail django-jinja django-sites requests easy-thumbnails celery Unidecode raven django-ipware premailer pyjwkest django-pglocks billiard kombu pycryptodome
Cleaning up...

**Comment by bameda** [comment]
Have you follow some documentation?

Try to migrate to 1.10 first and then to 2.0.

On Mon, Apr 4, 2016 at 3:06 PM, cmthomps <notifications@github.com> wrote:

> Yes. This was the last line of output from that process.
>
> Successfully installed Django django-sampledatahelper gunicorn Pillow amqp
> djmail django-jinja django-sites requests easy-thumbnails celery Unidecode
> raven django-ipware premailer pyjwkest django-pglocks billiard kombu
> pycryptodome
> Cleaning up...
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/taigaio/taiga-back/issues/685#issuecomment-205288990>
>



-- 

---


*David Barragán Merino*
* Engineer *
<david.barragan@kaleidos.net>
david.barragan@kaleidos.net  | Tel: (+34) 913562995
www.kaleidos.net/FFF8E7

**Comment by florisvanwoudenberg** [comment]
Yes I did, I'm always up-to-date

**Comment by superalex** [comment]
Could please try executing this from a python shell in your virtualenv:

`from _ctypes import Union, Structure, Array`

**Comment by florisvanwoudenberg** [comment]
(taiga)scrum :: ~/taiga-back ‹stable› » python                                                                      1 ↵
Python 3.4.0 (default, Apr 11 2014, 13:05:11)
[GCC 4.8.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from _ctypes import Union, Structure, Array
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /home/taiga/.virtualenvs/taiga/lib/python3.4/lib-dynload/_ctypes.cpython-34m-x86_64-linux-gnu.so: undefined symbol: _PyTraceback_Add
>>>

**Comment by superalex** [comment]
That seems to be the error. I found this issue: http://stackoverflow.com/questions/32818523/getting-django-core-exceptions-improperlyconfigured-geos-is-required-and-has-n

It seems Ubunut has pushed a Python 3.4 update which is not compatible with existing virtual environments and that the solutions is removing the virtualenv, creating it again and reinstalling all the requirements inside.

**Comment by florisvanwoudenberg** [comment]
Ok, does this not result in dataloss?

**Comment by bameda** [comment]
no.

You have to
```
deactivate taiga
rmvirtualenv taiga
mkvirtualenv -p /usr/bin/python3.4 taiga
pip install - r requirements.txt
```
install contrib plugins if you have anyone and execute `manage.py migrate` again.

**Comment by florisvanwoudenberg** [comment]
Thanks, this fixed it.

**Comment by superalex** [comment]
Great! :+1:

**Comment by cmthomps** [comment]
For anyone coming across this issue and having the "Apps aren't loaded yet" error.  My problem was related to the Taiga LDAP plugin (taiga-contrib-ldap-auth).  I was able to fix it by following the instructions here:

https://github.com/ensky/taiga-contrib-ldap-auth/pull/30

After I made the suggested modification I was able to upgrade with no issues.

**Comment by TinZazar** [comment]
Hello, new in here? Well yes, and I'm trying to execute python manage.py migrate for the first time after I passed the tutorial - Create a blank Django project. On the last step witch is: "Run Migration & Createsuperuser" I get some error in PowerShell. 

Here it is:
_PS C:\Users\uvft\src> python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Program Files\Python36\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_comma
nd_line
    utility.execute()
  File "C:\Program Files\Python36\lib\site-packages\django\core\management\__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "C:\Program Files\Python36\lib\site-packages\django\conf\__init__.py", line 56, in __getattr__
    self._setup(name)
  File "C:\Program Files\Python36\lib\site-packages\django\conf\__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "C:\Program Files\Python36\lib\site-packages\django\conf\__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\Program Files\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ValueError: source code string cannot contain null bytes_

If someone can help me i would be grateful.

**Comment by jespino** [comment]
Hi @TinZazar, looks like you are not asking in the right place. This is not a forum about django development, it is an issue in the Taiga project.

**Comment by MohitSh98** [comment]
hello, is their anyone help me out with this , i am just a beginner to django ??

(trydjango1-11) C:\dev\cfehome\trydjango1-11\src>python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\dev\cfehome\trydjango1-11\lib\site-packages\django\core\management\__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "C:\dev\cfehome\trydjango1-11\lib\site-packages\django\core\management\__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\dev\cfehome\trydjango1-11\lib\site-packages\django\core\management\__init__.py", line 205, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "C:\dev\cfehome\trydjango1-11\lib\site-packages\django\core\management\__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "C:\dev\cfehome\trydjango1-11\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\dev\cfehome\trydjango1-11\lib\site-packages\django\core\management\commands\migrate.py", line 15, in <module>
    from django.db.migrations.autodetector import MigrationAutodetector
  File "C:\dev\cfehome\trydjango1-11\lib\site-packages\django\db\migrations\autodetector.py", line 13, in <module>
    from django.db.migrations.questioner import MigrationQuestioner
  File "C:\dev\cfehome\trydjango1-11\lib\site-packages\django\db\migrations\questioner.py", line 12, in <module>
    from .loader import MigrationLoader
  File "C:\dev\cfehome\trydjango1-11\lib\site-packages\django\db\migrations\loader.py", line 10, in <module>
    from django.db.migrations.recorder import MigrationRecorder
  File "C:\dev\cfehome\trydjango1-11\lib\site-packages\django\db\migrations\recorder.py", line 12, in <module>
    class MigrationRecorder(object):
  File "C:\dev\cfehome\trydjango1-11\lib\site-packages\django\db\migrations\recorder.py", line 26, in MigrationRecorder
    class Migration(models.Model):
  File "C:\dev\cfehome\trydjango1-11\lib\site-packages\django\db\migrations\recorder.py", line 27, in Migration
    app = models.CharField(max_length=255)
  File "C:\dev\cfehome\trydjango1-11\lib\site-packages\django\db\models\fields\__init__.py", line 1061, in __init__
    super(CharField, self).__init__(*args, **kwargs)
  File "C:\dev\cfehome\trydjango1-11\lib\site-packages\django\db\models\fields\__init__.py", line 172, in __init__
    self.db_tablespace = db_tablespace or settings.DEFAULT_INDEX_TABLESPACE
  File "C:\dev\cfehome\trydjango1-11\lib\site-packages\django\conf\__init__.py", line 56, in __getattr__
    self._setup(name)
  File "C:\dev\cfehome\trydjango1-11\lib\site-packages\django\conf\__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "C:\dev\cfehome\trydjango1-11\lib\site-packages\django\conf\__init__.py", line 129, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.


what should i do ??? i didn't understand the error term.

**Comment by theriverman** [comment]
Hi,

This is a very complex product based on Django. Definitely not a good starting point for beginner Django developers. I recommend following the official Django tutorial (votes app) to learn the basics. Taiga is not suitable for starters.

**Comment by alexhermida** [comment]
@MohitSh98 as the error message said you need to configure your custom SECRET_KEY (https://docs.djangoproject.com/en/2.2/ref/settings/#std:setting-SECRET_KEY) and follow in detail the instructions at https://taigaio.github.io/taiga-doc/dist/setup-development.html#_setup_python_environment

**Comment by kkarnik22** [comment]
I removed all the migrations file except the __init__.py file. It worked for me.
Reference to the topic: https://stackoverflow.com/questions/40353649/django-migrate-error-typeerror-expected-string-or-bytes-like-object
Reference for the answer that worked for me: https://stackoverflow.com/a/48052630/12101710
