### ISSUE TITLE
Error on python manage.py migrate --noinput (Upgrade from 1.10)

### ISSUE THREAD

**Issue by aa-matthias** [taigaio/taiga-back#698]
I receive an error when trying to upgrade from 1.10

(taiga)matthias@SWIFFER-LINUX:~/taiga-back$ python manage.py migrate --noinput
Trying import local.py settings...
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/matthias/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/matthias/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/home/matthias/.virtualenvs/taiga/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/matthias/.virtualenvs/taiga/lib/python3.4/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/matthias/.virtualenvs/taiga/lib/python3.4/site-packages/django/apps/config.py", line 116, in create
    mod = import_module(mod_path)
  File "/home/matthias/.virtualenvs/taiga/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/matthias/.virtualenvs/taiga/lib/python3.4/site-packages/taiga_contrib_slack/apps.py", line 20, in <module>
    from . import signal_handlers as handlers
  File "/home/matthias/.virtualenvs/taiga/lib/python3.4/site-packages/taiga_contrib_slack/signal_handlers.py", line 19, in <module>
    from taiga.projects.history import services as history_service
  File "/home/matthias/taiga-back/taiga/projects/history/services.py", line 36, in <module>
    from django.contrib.contenttypes.models import ContentType
  File "/home/matthias/.virtualenvs/taiga/lib/python3.4/site-packages/django/contrib/contenttypes/models.py", line 159, in <module>
    class ContentType(models.Model):
  File "/home/matthias/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/models/base.py", line 94, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/home/matthias/.virtualenvs/taiga/lib/python3.4/site-packages/django/apps/registry.py", line 239, in get_containing_app_config
    self.check_apps_ready()
  File "/home/matthias/.virtualenvs/taiga/lib/python3.4/site-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

any ideas what can cause this error ?

**Comment by bameda** [comment]
Hi @aa-matthias, you have to upgrade taiga-contrib plugins (right now you are using `taiga-contrib-slack`) before apply migrations

```
(...)
File "/home/matthias/.virtualenvs/taiga/lib/python3.4/site-packages/taiga_contrib_slack/apps.py", line 20, in 
from . import signal_handlers as handlers
File "/home/matthias/.virtualenvs/taiga/lib/python3.4/site-packages/taiga_contrib_slack/signal_handlers.py", line 19, in 
from taiga.projects.history import services as history_service
(...)
