### ISSUE TITLE
error on upgrade

### ISSUE THREAD

**Issue by segler-alex** [taigaio/taiga-back#710]
Hi,

i wanted to update my taiga instance following the guide on http://taigaio.github.io/taiga-doc/dist/upgrades.html

when i did the following:
(taiga)taiga@magicserver:~/taiga-back$ python manage.py migrate --noinput
Trying import local.py settings...
Traceback (most recent call last):
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/apps/config.py", line 118, in create
    cls = getattr(mod, cls_name)
AttributeError: 'module' object has no attribute 'api'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/Crypto/Util/_raw_api.py", line 37, in <module>
    from cffi import FFI
ImportError: No module named 'cffi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/taiga/taiga-back/taiga/base/api/settings.py", line 202, in import_from_string
    module = importlib.import_module(module_path)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2231, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2203, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1448, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/taiga/taiga-back/taiga/external_apps/auth_backends.py", line 22, in <module>
    from . import services
  File "/home/taiga/taiga-back/taiga/external_apps/services.py", line 25, in <module>
    from . import encryption
  File "/home/taiga/taiga-back/taiga/external_apps/encryption.py", line 18, in <module>
    from Crypto.PublicKey import RSA
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/Crypto/PublicKey/RSA.py", line 79, in <module>
    from Crypto.IO import PKCS8, PEM
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/Crypto/IO/PKCS8.py", line 73, in <module>
    from Crypto.IO._PBES import PBES1, PBES2, PbesError
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/Crypto/IO/_PBES.py", line 44, in <module>
    from Crypto.Cipher import DES, ARC2, DES3, AES
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/Crypto/Cipher/__init__.py", line 78, in <module>
    from Crypto.Cipher._mode_ecb import _create_ecb_cipher
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/Crypto/Cipher/_mode_ecb.py", line 29, in <module>
    from Crypto.Util._raw_api import (load_pycryptodome_raw_lib,
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/Crypto/Util/_raw_api.py", line 94, in <module>
    from ctypes import (CDLL, c_void_p, byref, c_ulong, c_ulonglong, c_size_t,
  File "/usr/lib/python3.4/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: /home/taiga/.virtualenvs/taiga/lib/python3.4/lib-dynload/_ctypes.cpython-34m-x86_64-linux-gnu.so: undefined symbol: _PyTraceback_Add

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/apps/config.py", line 123, in create
    import_module(entry)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2231, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2203, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1448, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/taiga/taiga-back/taiga/base/api/__init__.py", line 53, in <module>
    from .viewsets import ModelListViewSet
  File "/home/taiga/taiga-back/taiga/base/api/viewsets.py", line 48, in <module>
    from . import views
  File "/home/taiga/taiga-back/taiga/base/api/views.py", line 134, in <module>
    class APIView(View):
  File "/home/taiga/taiga-back/taiga/base/api/views.py", line 138, in APIView
    authentication_classes = api_settings.DEFAULT_AUTHENTICATION_CLASSES
  File "/home/taiga/taiga-back/taiga/base/api/settings.py", line 238, in __getattr__
    val = perform_import(val, attr)
  File "/home/taiga/taiga-back/taiga/base/api/settings.py", line 190, in perform_import
    return [import_from_string(item, setting_name) for item in val]
  File "/home/taiga/taiga-back/taiga/base/api/settings.py", line 190, in <listcomp>
    return [import_from_string(item, setting_name) for item in val]
  File "/home/taiga/taiga-back/taiga/base/api/settings.py", line 206, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'taiga.external_apps.auth_backends.Token' for API setting 'DEFAULT_AUTHENTICATION_CLASSES'. ImportError: /home/taiga/.virtualenvs/taiga/lib/python3.4/lib-dynload/_ctypes.cpython-34m-x86_64-linux-gnu.so: undefined symbol: _PyTraceback_Add.

can you help me? what is wrong?

thank you in advance

**Comment by segler-alex** [comment]
i already fixed it with 

deactivate
rmvirtualenv taiga
mkvirtualenv taiga -p /usr/bin/python3.4
pip install -r requirements.txt
