### ISSUE TITLE
Problem migrating

### ISSUE THREAD

**Issue by sergiosantamaria** [taigaio/taiga-back#720]
Hi,

I'm running a CentOS 6.7 machine on VPS. I'm trying to install the backend but i'm on problems during the migration. I had several problems creating the virtualenv but i finally got it(I think so).

When I run "/home/taiga/.pyenv/versions/miniconda3-3.9.1/bin/python3.4 manage.py migrate --noinput" or "python3.4 manage.py migrate --noinput" I get 
`(delme) [taiga@ISIwebsrvr taiga-back]$ /home/taiga/.pyenv/versions/miniconda3-3.9.1/bin/python3.4 manage.py migrate --noinput
Trying import local.py settings...
Trying import development.py settings...
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/taiga/.pyenv/versions/miniconda3-3.9.1/lib/python3.4/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/taiga/.pyenv/versions/miniconda3-3.9.1/lib/python3.4/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/home/taiga/.pyenv/versions/miniconda3-3.9.1/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/taiga/.pyenv/versions/miniconda3-3.9.1/lib/python3.4/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/taiga/.pyenv/versions/miniconda3-3.9.1/lib/python3.4/site-packages/django/apps/config.py", line 116, in create
    mod = import_module(mod_path)
  File "/home/taiga/.pyenv/versions/miniconda3-3.9.1/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2224, in _find_and_load_unlocked
ImportError: No module named 'taiga'`

I doesn't understand very well why I get this answer.

Anyway when I run "python manage.py migrate --noinput"
`(delme) [taiga@ISIwebsrvr taiga-back]$ python manage.py migrate --noinput
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named 'django'
`
I have no idea how continue and solve this problem.
Any help will be wellcome.
Greetings.

**Comment by superalex** [comment]
Hello @sergiosantamaria it seems django isn't correctly installed in your virtualenv, you could try executing just python under your virtual env and on the interpreter "import django"

**Comment by sergiosantamaria** [comment]
I've tried reinstalling Django but doesn't change what I get from the server

`(delme) [taiga@ISIwebsrvr taiga-back]$ /home/taiga/.pyenv/versions/miniconda3-3.9.1/bin/python3.4 manage.py migrate 
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named 'django'
(delme) [taiga@ISIwebsrvr taiga-back]$ sudo /home/taiga/.pyenv/versions/miniconda3-3.9.1/bin/pip3.4 install Django
Collecting Django
  Using cached Django-1.9.6-py2.py3-none-any.whl
Installing collected packages: Django
Successfully installed Django-1.9.6
(delme) [taiga@ISIwebsrvr taiga-back]$ /home/taiga/.pyenv/versions/miniconda3-3.9.1/bin/python3.4 manage.py migrate 
Trying import local.py settings...
Trying import development.py settings...
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/taiga/.pyenv/versions/miniconda3-3.9.1/lib/python3.4/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/taiga/.pyenv/versions/miniconda3-3.9.1/lib/python3.4/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/home/taiga/.pyenv/versions/miniconda3-3.9.1/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/taiga/.pyenv/versions/miniconda3-3.9.1/lib/python3.4/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/taiga/.pyenv/versions/miniconda3-3.9.1/lib/python3.4/site-packages/django/apps/config.py", line 116, in create
    mod = import_module(mod_path)
  File "/home/taiga/.pyenv/versions/miniconda3-3.9.1/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2224, in _find_and_load_unlocked
ImportError: **No module named 'taiga'**
(delme) [taiga@ISIwebsrvr taiga-back]$ 
`

Still doesn't know what module is taiga and how to install it

**Comment by bameda** [comment]
Are you using virtualenv or virtualenvwrapper?

**Comment by sergiosantamaria** [comment]
Hello,

It was my fail, I had deleted the folder taiga inside taiga-backend... brain-explosion

Sorry for your loss of time.
Thanks

**Comment by bameda** [comment]
oook

**Comment by sivasai519** [comment]
Hello Bameda,
Thanks in advance,

I getting this error, while i am executing this command.

Trying import local.py settings...
Trying import development.py settings...
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: permission denied for relation django_migrations


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 83, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/loader.py", line 52, in __init__
    self.build_graph()
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/loader.py", line 203, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 66, in applied_migrations
    return set(tuple(x) for x in self.migration_qs.values_list("app", "name"))
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 256, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 1087, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 125, in __iter__
    for row in compiler.results_iter():
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 789, in results_iter
    results = self.execute_sql(MULTI)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 835, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: permission denied for relation django_migrations.

Could you please help me out from this issue.

**Comment by bameda** [comment]
You `<dbuser>` has not permissions to manipulate the `<database>`. You should grant permisions with:
```
psql <database> -c "GRANT ALL ON ALL TABLES IN SCHEMA public to <dbuser>;"
psql <database> -c "GRANT ALL ON ALL SEQUENCES IN SCHEMA public to <dbuser>;"
psql <database> -c "GRANT ALL ON ALL FUNCTIONS IN SCHEMA public to <dbuser>;"
```

**Comment by sivasai519** [comment]
Thanks for the reply Bameda,
As you state, I given permissions to my database user.
Again I am getting same error.

Trying import local.py settings...
Trying import development.py settings...
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: permission denied for relation django_migrations


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 83, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/loader.py", line 52, in __init__
    self.build_graph()
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/loader.py", line 203, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 66, in applied_migrations
    return set(tuple(x) for x in self.migration_qs.values_list("app", "name"))
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 256, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 1087, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 125, in __iter__
    for row in compiler.results_iter():
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 789, in results_iter
    results = self.execute_sql(MULTI)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 835, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: permission denied for relation django_migrations
