### ISSUE TITLE
/api/v1/userstories & RabbitMQ bug

### ISSUE THREAD

**Issue by onekiloparsec** [taigaio/taiga-back#725]
I noticed a bug with /api/v1/userstories & RabbitMQ bug. I am running the latest stable branches of taiga-front and taiga-back (2016-05-13T09:00+0200).

The visible consequences is that upon the creation of a user story, the "new US" form/layer isn't removed, without any message, and you have to manually close it. And when deleting a US, same thing, except that an error message is shown "Oomla...".

But in both cases, the job is actually done (a new US is created, and then deleted).

```
ERROR:2016-05-13 07:21:54,087: Internal Server Error: /api/v1/userstories/32
Traceback (most recent call last):
  File "/home/taiga/taiga-back/taiga/events/backends/rabbitmq.py", line 32, in _make_rabbitmq_connection
    (authdata, host) = parse_result.netloc.split("@")
ValueError: too many values to unpack (expected 2)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/viewsets.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/views.py", line 445, in dispatch
    response = self.handle_exception(exc)
  File "/home/taiga/taiga-back/taiga/base/api/views.py", line 442, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/lib/python3.4/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/transaction.py", line 267, in __exit__
    connection.set_autocommit(True)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/backends/base/base.py", line 397, in set_autocommit
    self.run_and_clear_commit_hooks()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/backends/base/base.py", line 623, in run_and_clear_commit_hooks
    func()
  File "/home/taiga/taiga-back/taiga/events/signal_handlers.py", line 59, in <lambda>
    emit_event = lambda: events.emit_event_for_model(instance, sessionid=sesionid, type="delete")
  File "/home/taiga/taiga-back/taiga/events/events.py", line 78, in emit_event_for_model
    data=data)
  File "/home/taiga/taiga-back/taiga/events/events.py", line 47, in emit_event
    channel=channel)
  File "/home/taiga/taiga-back/taiga/events/backends/rabbitmq.py", line 51, in emit_event
    connection = _make_rabbitmq_connection(self.url)
  File "/home/taiga/taiga-back/taiga/events/backends/rabbitmq.py", line 34, in _make_rabbitmq_connection
    raise RuntimeError("Invalid url") from e
RuntimeError: Invalid url

```

**Comment by superalex** [comment]
Hello @onekiloparsec it sounds like a problem in your celery configuration, could you please show us your local.py config file?

**Comment by onekiloparsec** [comment]
Sure! Thanks for the rapid reply. 

```
from .common import *

MEDIA_URL = "https://taiga.<domain.ltd>/media/"
STATIC_URL = "https://taiga.<domain.ltd>/static/"
ADMIN_MEDIA_PREFIX = "https://taiga.<domain.ltd>/static/admin/"
SITES["front"]["scheme"] = "https"
SITES["front"]["domain"] = "taiga.<domain.ltd>"

DEBUG = True
TEMPLATE_DEBUG = True
PUBLIC_REGISTER_ENABLED = False

ALLOWED_HOSTS = ["taiga.<domain.ltd>"]

ADMINS = (
    ("Cédric", "c.foellmi@<domain.ltd>"),
)

DEFAULT_FROM_EMAIL = "taiga@<domain.ltd>"
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# Uncomment and populate with proper connection parameters
# for enable email sending. EMAIL_HOST_USER should end by @domain.tld

# Console
#EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# SMTP
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_USE_SSL = True
EMAIL_HOST = "ssl0.ovh.net"
EMAIL_HOST_USER = "taiga@<domain.ltd>"
EMAIL_HOST_PASSWORD = <PASSWORD>
EMAIL_PORT = 465

# Files
#EMAIL_BACKEND = 'django.core.mail.backends.filebased.EmailBackend'
#EMAIL_FILE_PATH = '/tmp/taiga/email-messages'

from .celery import *

BROKER_URL = 'amqp://guest:guest@localhost:5672//'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ENABLED = True

EVENTS_PUSH_BACKEND = "taiga.events.backends.rabbitmq.EventsPushBackend"
EVENTS_PUSH_BACKEND_OPTIONS = {"url": "amqp://taiga:<PASSWORD>@localhost:5672/taiga"}
``
```

**Comment by superalex** [comment]
Cuould you try commenting all the settings related to CELERY and EVENTS to isolate your problem?

**Comment by onekiloparsec** [comment]
I've commented out both CELERY and EVENTS, and it worked again. I've added back CELERY only and it sill works... So it seems related to events. Will investigate more.

**Comment by macarena** [comment]
This bug is affecting me too.
I'll try to comment those lines too, but is there any resolution or at least new information about this bug?

**Comment by macarena** [comment]
I understand this bug was considered closed, but to keep the record, i solved this thinking about the error _RuntimeError: Invalid url_
Since my amqp URL is correct (as @onekiloparsec is too), the only different element is the password. My password has a hash symbol #. Maybe, for some reason, this hash makes the URL parsing crashes. Changing for a cleaner password worked for me.
