### ISSUE TITLE
Internal Server Error: Attribute Error for only one project

### ISSUE THREAD

**Issue by dwarakanathjagadeesan** [taigaio/taiga-back#733]
Hi,

I have hosted taiga locally and we have hosted few projects on this platform. Apparently, only one project we have(one of the heavily used ones) is having an issue where we are able to see only empty screens in this project. 

/api/v1/projects/by_slug?slug=admin-fresco-play-1 is giving me 500 internal error. On checking the unicorn.stderr.log below is the trace,

`AttributeError: 'QuerySet' object has no attribute 'user'
ERROR:2016-05-25 06:41:19,555: Internal Server Error: /api/v1/projects/by_slug
Traceback (most recent call last):
  File "/home/ubuntu/taiga-back/taiga/base/api/serializers.py", line 617, in data
    self._data = [self.to_native(item) for item in obj]
  File "/home/ubuntu/taiga-back/taiga/base/api/serializers.py", line 617, in <listcomp>
    self._data = [self.to_native(item) for item in obj]
  File "/home/ubuntu/taiga-back/taiga/base/api/serializers.py", line 396, in to_native
    value = field.field_to_native(obj, field_name)
  File "/home/ubuntu/taiga-back/taiga/base/api/fields.py", line 1082, in field_to_native
    value = getattr(self.parent, self.method_name)(obj)
  File "/home/ubuntu/taiga-back/taiga/projects/serializers.py", line 239, in get_photo
    return get_photo_or_gravatar_url(membership.user)
  File "/home/ubuntu/taiga-back/taiga/users/services.py", line 87, in get_photo_or_gravatar_url
    return get_photo_url(user.photo) if user.photo else get_gravatar_url(user.email)
  File "/home/ubuntu/taiga-back/taiga/users/services.py", line 78, in get_photo_url
    url = get_thumbnailer(photo)[settings.THN_AVATAR_SMALL].url
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/easy_thumbnails/files.py", line 342, in __getitem__
    return self.get_thumbnail(options, silent_template_exception=True)
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/easy_thumbnails/files.py", line 517, in get_thumbnail
    silent_template_exception=silent_template_exception)
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/easy_thumbnails/files.py", line 404, in generate_thumbnail
    subsampling=subsampling)
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/easy_thumbnails/engine.py", line 71, in save_image
    image.save(destination, format=format, **options)
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/PIL/Image.py", line 1675, in save
    save_handler(self, fp, filename)
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/PIL/PngImagePlugin.py", line 757, in _save
    data = name + b"\0\0" + zlib.compress(im.info["icc_profile"])
TypeError: 'tuple' does not support the buffer interface

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    except:
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    callback, param_dict = resolver.resolve404()
  File "/home/ubuntu/taiga-back/taiga/base/api/viewsets.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    PendingDeprecationWarning)
  File "/home/ubuntu/taiga-back/taiga/base/api/views.py", line 445, in dispatch
    response = self.handle_exception(exc)
  File "/home/ubuntu/taiga-back/taiga/base/api/views.py", line 442, in dispatch
    response = handler(request, *args, **kwargs)
`

Could you please help on this?

Regards,
Dwarak

**Comment by superalex** [comment]
It sounds like some of your users or your project avatar has a tiff file. The library used to generate miniatures has a bug with this format. There is a PR to solve this issue that I hope will be merged soon to the stable branch (https://github.com/taigaio/taiga-back/pull/732), as a workaround while that PR is merged you can just change that image for another image format: jpg, png...

**Comment by dwarakanathjagadeesan** [comment]
@superalex How do I find which user who has a tiff image uploaded and how to locate it in my server?

Could you please help me with this?

**Comment by superalex** [comment]
I think the easiest way should be executing a find in your media folder to locate the tiff files.

**Comment by dwarakanathjagadeesan** [comment]
@superalex : Sorry to bother you with one more. I have renamed the file and was trying to restart taiga and here is what I got,

Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/home/ubuntu/taiga-back/taiga/__init__.py", line 18, in <module>
    from . import celery
  File "/home/ubuntu/taiga-back/taiga/celery.py", line 20, in <module>
    from celery import Celery
  File "<frozen importlib._bootstrap>", line 2281, in _handle_fromlist
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/celery/five.py", line 306, in __getattr__
    module = __import__(self._object_origins[name], None, None, [name])
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/celery/app/__init__.py", line 22, in <module>
    from .base import Celery, AppPickler
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/celery/app/base.py", line 43, in <module>
    from .utils import (
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/celery/app/utils.py", line 20, in <module>
    from celery.datastructures import ConfigurationView
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/celery/datastructures.py", line 27, in <module>
    from django.utils.functional import LazyObject, LazySettings
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/django/utils/functional.py", line 228, in <module>
    class SimpleLazyObject(LazyObject):
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/django/utils/functional.py", line 251, in SimpleLazyObject
    __unicode__ = new_method_proxy(unicode)
NameError: name 'unicode' is not defined

But if I type locale in my virtualenv I am able to get the below,

ANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE=en_US.UTF-8
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

**Comment by superalex** [comment]
I don't know what can be happening...how did you restart taiga?, did you do it under the correct virtualenv?
