### ISSUE TITLE
ImportError: No module named 'django' 

### ISSUE THREAD

**Issue by llwp** [taigaio/taiga-back#789]
Seems to be a python installation related issue.

Following the instructions (which are superb by the way) step by step, very carefully for the third time.
During the install using pip, an error presents (in screenshot & below) and then subsequent steps fail.

Several various errors; 
 *  Could not find a tag or branch 'dbb8d7375066859f897604132bd437832d2014ea', assuming commit.
 * warning: no files found matching 'sampledatahelper/static/*'
 * warning: no files found matching 'sampledatahelper/l10n/names/*'
 * warning: no files found matching '*.txt' under directory 'docs'
 * Single threaded build, not installing mp_compile:1 processes
 * warning: no previously-included files found matching '.editorconfig'
 * warning: no files found matching '*.py' under directory 'Lib'

Ultimately ending here:
![screenshot 2016-07-18 at 21 23 20](https://cloud.githubusercontent.com/assets/9566542/16935505/fd7d1f30-4d2d-11e6-94a4-8b48bc0aba1c.png)

I included the VM python & pip versions in the screenshot:
 * Python 3.4.3
 * pip 1.5.4 from /home/aj/.virtualenvs/taiga/lib/python3.4/site-packages (python 3.4)

Kindly let me know what I should do to recover...

Thanks!

**Comment by superalex** [comment]
Hello @llwp 

You could removing your virtualenv, creating it again and reinstalling the dependencies:

```
rmvirtualenv taiga
mkvirtualenv -p /usr/bin/python3.4 taiga
pip install -r requirements.txt
```

You should see no errors before doing the following migration step

**Comment by llwp** [comment]
Nope.
Same exact issue.
Same exact errors as summarized above.

**Comment by bameda** [comment]
Try to print your python path with this command:

```
python -c "import sys; print('\n'.join(sys.path))"
```

you have to see some line like ```/home/aj/.virtualenvs/taiga/lib/python3.4/site-packages```

**Comment by llwp** [comment]
Yup.  Among others, exactly that one:
```shell
/home/aj/.virtualenvs/taiga/lib/python3.4/site-packages
```

**Comment by bameda** [comment]
Try  to run this

```
pip install --upgrade setuptools 
```

And try again

```
pip install --upgrade -r requirements.txt
```

**Comment by llwp** [comment]
Somewhat reassuring - that did result in a different set of errors from the server.
At one point in the process, I was disconnected and when it came back there was a notice from ubuntu that restart was required, so I did that before reconnecting to the virtualenv.
First:
```shell
cd taiga-back
workon taiga
```
Then:
```shell
(taiga)aj@taigaio1:~/taiga-back$ python manage.py migrate --noinput
Trying import local.py settings...
Trying import development.py settings...
Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/home/aj/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/aj/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/home/aj/.virtualenvs/taiga/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/aj/.virtualenvs/taiga/lib/python3.4/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/aj/.virtualenvs/taiga/lib/python3.4/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/aj/.virtualenvs/taiga/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/aj/taiga-back/taiga/projects/models.py", line 47, in <module>
    from taiga.projects.notifications.services import (
  File "/home/aj/taiga-back/taiga/projects/notifications/services.py", line 36, in <module>
    from taiga.projects.history.services import (make_key_from_model_object,
  File "/home/aj/taiga-back/taiga/projects/history/services.py", line 47, in <module>
    from taiga.mdrender.service import render as mdrender
  File "/home/aj/taiga-back/taiga/mdrender/service.py", line 21, in <module>
    import bleach
  File "/home/aj/.virtualenvs/taiga/lib/python3.4/site-packages/bleach/__init__.py", line 8, in <module>
    from html5lib.sanitizer import HTMLSanitizer
ImportError: No module named 'html5lib.sanitizer'
```

**Comment by llwp** [comment]
Oh - in the pip script running on the taiga virtualenv there were a few messages that things could not be found:
```shell

  Could not find .egg-info directory in install record for django-ipware==1.1.3 (from -r requirements.txt (line 29))
  Running setup.py install for cssutils
    Skipping implicit fixer: buffer
    Skipping implicit fixer: idioms
    Skipping implicit fixer: set_literal
    Skipping implicit fixer: ws_comma
    
    Installing cssparse script to /home/aj/.virtualenvs/taiga/bin
    Installing csscombine script to /home/aj/.virtualenvs/taiga/bin
    Installing csscapture script to /home/aj/.virtualenvs/taiga/bin
  Could not find .egg-info directory in install record for cssutils==1.0.1 (from -r requirements.txt (line 31))
  Running setup.py install for lxml
    Building lxml version 3.5.0.
    Building without Cython.
    Using build configuration of libxslt 1.1.28
    building 'lxml.etree' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security
 -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/libxml2 -Isrc/lxml/includes -I/usr/include/python3.4m -I/home/aj/.virtualenvs/taiga/include/python3.4m -c src/lxml/lxml.e
tree.c -o build/temp.linux-x86_64-3.4/src/lxml/lxml.etree.o -w
```
(this "-w" was where the reboot/disconnect took place)
These are 2 of the items we were notified that could not be found, there are others:
 * Could not find .egg-info directory in install record for django-ipware
 * Could not find .egg-info directory in install record for cssutils

**Comment by bameda** [comment]
No, you can do the migration because your virtualenv is broken. Do this:
```
workon taiga
pip install --upgrade setuptools 
pip install --upgrade -r requirements.txt
```

**Comment by llwp** [comment]
I did that first; based on [the previous comment](https://github.com/taigaio/taiga-back/issues/789#issuecomment-233608351).

Attempted again:
```shell
workon taiga
pip install --upgrade setuptools
pip install --upgrade -r requirements.txt
```

Much faster - - mostly said "Requirement already up-to-date".
No difference, virtualenv is still broken.

To verify results, did the same thing all over again:
```shell
rmvirtualenv taiga
mkvirtualenv -p /usr/bin/python3.4 taiga
pip install --upgrade setuptools
pip install -r requirements.txt
```

And it fails in the same way.

**Comment by bameda** [comment]
Ok, try to regenerate the virtualenv again:

```
deactivate
rmvirtualenv taiga
mkvirtualenv -p /user/bin/python3.4 taiga
pip install --upgrade setuptools
pip install -r requirements.txt
```
And then do the migration

```
./manage.py migrate
```

**Comment by llwp** [comment]
Yes - that is exactly what was done, verified multiple times now.

It is consistently failing in the same way.

**Comment by llwp** [comment]
Here is another excerpt:
```shell
Could not find .egg-info directory in install record for pycryptodome (from pyjwkest==1.1.5->-r requirements.txt (line 34))
  Running setup.py install for future
    
    warning: no files found matching '*.au' under directory 'tests'
    warning: no files found matching '*.gif' under directory 'tests'
    warning: no files found matching '*.txt' under directory 'tests'
    Installing futurize script to /home/aj/.virtualenvs/taiga/bin
    Installing pasteurize script to /home/aj/.virtualenvs/taiga/bin
  Could not find .egg-info directory in install record for future (from pyjwkest==1.1.5->-r requirements.txt (line 34))
  Running setup.py install for anyjson
    Fixing build/lib/anyjson/__init__.py
    Skipping implicit fixer: buffer
    Skipping implicit fixer: idioms
    Skipping implicit fixer: set_literal
    Skipping implicit fixer: ws_comma
    Fixing build/lib/anyjson/__init__.py
    Skipping implicit fixer: buffer
    Skipping implicit fixer: idioms
    Skipping implicit fixer: set_literal
    Skipping implicit fixer: ws_comma
    
  Could not find .egg-info directory in install record for anyjson>=0.3.3 (from kombu>=3.0.33,<3.1->celery==3.1.20->-r requirements.txt (line 24))
  Running setup.py install for webencodings
    
  Could not find .egg-info directory in install record for webencodings (from html5lib>=0.999->bleach==1.4.2->-r requirements.txt (line 28))
```

**Comment by superalex** [comment]
Just a fast question, what hardware are you using to install Taiga?

**Comment by llwp** [comment]
The machine is virtual - GCP.  Google Cloud Platform, which is like AWS.

**Comment by llwp** [comment]
1 Intel Haswell vCPU implemented as a single hardware hyper-thread on a 2.3 GHz Intel Xeon E5 v3, and 3.75 GB memory.

**Comment by bameda** [comment]
I read more and some people with this kind of problems have to upgrade pip too, so try with

```
pip install --upgrade setuptools pip
pip install --upgrade -r requirements.txt
```

**Comment by llwp** [comment]
Thanks, @bameda ... yup, this is exactly right (from point of previous run/fail) ...

What I've tried:
```shell
deactivate #shuts down previous 
rmvirtualenv taiga #delete previous setup
mkvirtualenv -p /usr/bin/python3.4 taiga #create new environment
pip install --upgrade setuptools #upgrade w pip - tools
pip install -r requirements.txt #the actual run
```

Same failures...

**Comment by bameda** [comment]
I cannot think what else you can do, sorry. Maybe you can try to install python 3.5 in the server and try with it.

**Comment by bameda** [comment]
Hi @llwp 

We've made some updates over the taiga requirements related to a bug with html5lib. Could you try to update your repository ```git pul``` and instal the requirements again ```pip install --upgrade -r requirements.txt```

The bug is related to html5lib-0.999999999 and bleach-1.4.2

https://github.com/mozilla/bleach/issues/212

**Comment by llwp** [comment]
I followed these instructions to install/compile python 3.5:
http://askubuntu.com/questions/680824/how-do-i-update-python-from-3-4-3-to-3-5

And then:
```shell
deactivate                                #shuts down previous 
rmvirtualenv taiga                        #delete previous setup
git pull                                  #git fetch and merge of latest
mkvirtualenv -p /usr/bin/python3.5 taiga  #create new environment, python 3.5
pip install --upgrade setuptools          #upgrade w pip - tools
pip install -r requirements.txt           #try try again...
```

New results!
```shell
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_
FORTIFY_SOURCE=2 -fPIC -DPSYCOPG_DEFAULT_PYDATETIME=1 -DPSYCOPG_VERSION="2.6.1 (dt dec pq3 ext lo64)" -DPG_VERSION_HEX=0x09030D -DHAVE_LO64=1 -I/usr/include/python
3.5m -I/home/aj/.virtualenvs/taiga/include/python3.5m -I. -I/usr/include/postgresql -I/usr/include/postgresql/9.3/server -c psycopg/psycopgmodule.c -o build/temp.l
inux-x86_64-3.5/psycopg/psycopgmodule.o -Wdeclaration-after-statement
In file included from psycopg/psycopgmodule.c:27:0:
./psycopg/psycopg.h:30:20: fatal error: Python.h: No such file or directory
 #include <Python.h>
                    ^
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
----------------------------------------
Cleaning up...
Command /home/aj/.virtualenvs/taiga/bin/python3.5 -c "import setuptools, tokenize;__file__='/home/aj/.virtualenvs/taiga/build/psycopg2/setup.py';exec(compile(getat
tr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-op0kqr4b-record/install-record.txt --single-versio
n-externally-managed --compile --install-headers /home/aj/.virtualenvs/taiga/include/site/python3.5 failed with error code 1 in /home/aj/.virtualenvs/taiga/build/p
sycopg2
Storing debug log for failure in /home/aj/.pip/pip.log
```

Also tried, for good measure:
```shell
deactivate                                #shuts down previous 
rmvirtualenv taiga                        #delete previous setup
git pull                                  #git fetch and merge of latest
mkvirtualenv -p /usr/bin/python3.4 taiga  #create new environment, python 3.4
pip install --upgrade setuptools          #upgrade w pip - tools
pip install -r requirements.txt           #try try again...
```

Maybe I am missing the necessary error in the output - looks like the same types of errors noted earlier... but I've attached the whole result this time...
[everything.txt](https://github.com/taigaio/taiga-back/files/376150/everything.txt)

**Comment by bameda** [comment]
```Python.h: No such file or directory``` normally is because you need `python-dev` but in your env I'dont know.

**Comment by llwp** [comment]
If the solution is `apt-get install python-dev` on the server and not in the virtualenv... then it is already installed.

**Comment by DhaneshKumarHeerani** [comment]
Can you please tell me why i'ts showing the error when i am runnnig runtests.py file 
  from .statement import Statement
ImportError: No module named 'tests_django.statement'

**Comment by usamamashkoor** [comment]
I was facing the same issue i forgot to activate my environment try deactivate and then activating it again maybe it solves your problem.
