### ISSUE TITLE
html5lib.sanitizer not found

### ISSUE THREAD

**Issue by eggnita** [taigaio/taiga-back#794]
Hi, I'm struggling a lot because of the html5lib module. It seems that the version that I have installed does not have *.sanitizer class. I have followed 4 times all the install instructions and I still get this. It could be that the taiga-back to be outdated considering that the latest release of html5lib was on July 16 2016 https://pypi.python.org/pypi/html5lib ?

see the error trace bellow:
Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/taiga/taiga-back/taiga/projects/models.py", line 47, in <module>
    from taiga.projects.notifications.services import (
  File "/home/taiga/taiga-back/taiga/projects/notifications/services.py", line 36, in <module>
    from taiga.projects.history.services import (make_key_from_model_object,
  File "/home/taiga/taiga-back/taiga/projects/history/services.py", line 47, in <module>
    from taiga.mdrender.service import render as mdrender
  File "/home/taiga/taiga-back/taiga/mdrender/service.py", line 21, in <module>
    import bleach
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/bleach/__init__.py", line 8, in <module>
    from html5lib.sanitizer import HTMLSanitizer
ImportError: No module named 'html5lib.sanitizer'

**Comment by bameda** [comment]
You have to downgrade htmllib, try with this

```pip install --upgrade bleach ```

**Comment by superalex** [comment]
The problem was solved in master with this commit https://github.com/taigaio/taiga-back/commit/698b15722d8c330ae0503b2a6975e2b62b23d06f but it wasn't backported to stable.

I'm backporting it to the stable branch now (just waiting for all the tests to pass)

**Comment by superalex** [comment]
It's backported now, could you please update your repo and install the requirements again?

**Comment by eggnita** [comment]
Thank you, This works perfectly.
