### ISSUE TITLE
Issue saved, but I get warning and stay on the create form

### ISSUE THREAD

**Issue by florisvanwoudenberg** [taigaio/taiga-back#805]
Since 2 week I have a problem with creating issues.
After submitting, I get a warning about the Oompa Loompa' and I stay on the 'create issue' form.

After closing this and refreshing the page, I see that the issue is created.

Any idee? Attached a screenshot from the console.
![screen shot 2016-08-04 at 12 03 34](https://cloud.githubusercontent.com/assets/1166612/17398232/17244948-5a3c-11e6-989b-0a250aca8833.png)

**Comment by bameda** [comment]
taiga-back return a server error (HTTP 500). What can you see in log files?

**Comment by florisvanwoudenberg** [comment]
Which logs should I check?

**Comment by bameda** [comment]
gunicorn logs, defined in the circus conf file

**Comment by florisvanwoudenberg** [comment]
And what should I look for, since I do not see strange thing in /home/taiga/logs/gunicorn.stdout.log

**Comment by bameda** [comment]
You should see the trace of the error.

And what about /home/taiga/logs/gunicorn.stderr.log?

**Comment by florisvanwoudenberg** [comment]
```
ERROR:2016-08-04 11:09:24,413: Internal Server Error: /api/v1/issues
Traceback (most recent call last):
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/viewsets.py", line 106, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/views.py", line 446, in dispatch
    response = self.handle_exception(exc)
  File "/home/taiga/taiga-back/taiga/base/api/views.py", line 443, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/mixins.py", line 99, in create
    self.object = serializer.save(force_insert=True)
  File "/home/taiga/taiga-back/taiga/projects/notifications/mixins.py", line 249, in save
    obj = super(EditableWatchedResourceModelSerializer, self).save(**kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/serializers.py", line 1086, in save
    self.object = super().save(**kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/serializers.py", line 645, in save
    self.save_object(self.object, **kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/serializers.py", line 1104, in save_object
    obj.save(**kwargs)
  File "/home/taiga/taiga-back/taiga/projects/issues/models.py", line 95, in save
    return super().save(*args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/models/base.py", line 700, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/models/base.py", line 737, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/dispatch/dispatcher.py", line 192, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/taiga/taiga-back/taiga/projects/references/models.py", line 103, in attach_sequence
    instance.save(update_fields=['ref'])
  File "/home/taiga/taiga-back/taiga/projects/issues/models.py", line 95, in save
    return super().save(*args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/models/base.py", line 700, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/models/base.py", line 737, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/dispatch/dispatcher.py", line 192, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/taiga/taiga-back/taiga/events/signal_handlers.py", line 47, in on_save_any_model
    connection.on_commit(emit_event)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/backends/base/base.py", line 616, in on_commit
    func()
  File "/home/taiga/taiga-back/taiga/events/signal_handlers.py", line 46, in <lambda>
    emit_event = lambda: events.emit_event_for_model(instance, sessionid=sesionid, type=type)
  File "/home/taiga/taiga-back/taiga/events/events.py", line 83, in emit_event_for_model
    data=data)
  File "/home/taiga/taiga-back/taiga/events/events.py", line 52, in emit_event
    channel=channel)
  File "/home/taiga/taiga-back/taiga/events/backends/rabbitmq.py", line 52, in emit_event
    connection = _make_rabbitmq_connection(self.url)
  File "/home/taiga/taiga-back/taiga/events/backends/rabbitmq.py", line 44, in _make_rabbitmq_connection
    password=password, virtual_host=vhost[1:])
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/amqp/connection.py", line 180, in __init__
    (10, 30),  # tune
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/amqp/abstract_channel.py", line 67, in wait
    self.channel_id, allowed_methods, timeout)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/amqp/connection.py", line 241, in _wait_method
    channel, method_sig, args, content = read_timeout(timeout)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/amqp/connection.py", line 330, in read_timeout
    return self.method_reader.read_method()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/amqp/method_framing.py", line 189, in read_method
    raise m
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/amqp/method_framing.py", line 107, in _next_method
    frame_type, channel, payload = read_frame()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/amqp/transport.py", line 154, in read_frame
    frame_header = read(7, True)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/amqp/transport.py", line 277, in _read
    s = recv(n - len(rbuf))
ConnectionResetError: [Errno 104] Connection reset by peer
```

**Comment by bameda** [comment]
It seems that taiga-back can;'t connect to RabbitMQ `ConnectionResetError: [Errno 104] Connection reset by peer`. Have you updated your system? Is RabbitMQ running?

**Comment by bameda** [comment]
You can restart RabbitMQ and try it again

**Comment by mostafahussein** [comment]
I got similar issue after migrating taiga to another server and solved by recreating the rabbitmq taiga user.
