### ISSUE TITLE
Repeated email issue in logs

### ISSUE THREAD

**Issue by tanc** [taigaio/taiga-back#810]
We have a self hosted instance of Taiga and I'm trying to understand the email logs. I'm seeing something repeated in the logs every minute or so:

```
Aug 17 11:24:05 taiga.agile.coop postfix/smtpd[11070]: connect from localhost[127.0.0.1]
Aug 17 11:24:05 taiga.agile.coop postfix/smtpd[11070]: warning: Illegal address syntax from localhost[127.0.0.1] in RCPT command: <>
Aug 17 11:24:06 taiga.agile.coop postfix/smtpd[11070]: lost connection after RSET from localhost[127.0.0.1]
Aug 17 11:24:06 taiga.agile.coop postfix/smtpd[11070]: disconnect from localhost[127.0.0.1]
Aug 17 11:24:06 taiga.agile.coop postfix/pickup[18154]: 69B29B177C: uid=1000 from=<taiga>
Aug 17 11:24:06 taiga.agile.coop postfix/cleanup[8999]: 69B29B177C: message-id=<20160817102406.69B29B177C@taiga.agile.coop>
Aug 17 11:24:06 taiga.agile.coop postfix/qmgr[1822]: 69B29B177C: from=<taiga@taiga.agile.coop>, size=3064, nrcpt=1 (queue active)
Aug 17 11:24:06 taiga.agile.coop postfix/local[10043]: 69B29B177C: to=<taiga@taiga.agile.coop>, orig_to=<taiga>, relay=local, delay=0.27, delays=0.19/0/0/0.08, dsn=2.0.0, status=sent (delivered to mailbox)
Aug 17 11:24:06 taiga.agile.coop postfix/qmgr[1822]: 69B29B177C: removed
```

Do you know what might be causing this? I realise this may not be a Taiga issue but any guidance would be appreciated.

**Comment by tanc** [comment]
We're also having a problem where not all email notifications are sending. I've got Taiga set up to send emails after a 60 second delay (with `CHANGE_NOTIFICATIONS_MIN_INTERVAL = 60` in local.py) using cron to trigger them. The cron command was working perfectly when set up but now when I run it manually I'm seeing:

```
Traceback (most recent call last):
  File "/home/taiga/taiga-back/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/raven/contrib/django/management/__init__.py", line 41, in new_execute
    return original_func(self, *args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/taiga/taiga-back/taiga/projects/notifications/management/commands/send_notifications.py", line 30, in handle
    send_sync_notifications(change_notification.pk)
  File "/usr/lib/python3.4/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/home/taiga/taiga-back/taiga/projects/notifications/services.py", line 291, in send_sync_notifications
    email.send(user.email, context, headers=headers)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/djmail/template_mail.py", line 118, in send
    return email.send()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/mail/message.py", line 292, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/mail/backends/smtp.py", line 107, in send_messages
    sent = self._send(message)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/mail/backends/smtp.py", line 123, in _send
    self.connection.sendmail(from_email, recipients, message.as_bytes(linesep='\r\n'))
  File "/usr/lib/python3.4/smtplib.py", line 792, in sendmail
    raise SMTPRecipientsRefused(senderrs)
smtplib.SMTPRecipientsRefused: {'': (501, b'5.1.3 Bad recipient address syntax')}
```

So it definitely looks like Taiga is trying to send an email to a bad address.

The command being run is `manage.py send_notifications`

**Comment by bameda** [comment]
You have some user in your Taiga server with an invalid email.

**Comment by tanc** [comment]
It was the admin user which didn't have an email set. I've now given that user an email and everything is working correctly. Thanks!

**Comment by bameda** [comment]
you are welcome.
