### ISSUE TITLE
Error after upgrade : "cannot import name 'get_photo_or_gravatar_url'"

### ISSUE THREAD

**Issue by unixfox** [taigaio/taiga-back#832]
Hi!

I just upgraded Taiga to 3.0.0 using this procedure:
````
git checkout stable
workon taiga
git pull
pip install --upgrade -r requirements.txt
python manage.py migrate --noinput
````
And I'm stuck at `python manage.py migrate --noinput` with this error:
````
Trying import local.py settings...
Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/taiga_contrib_slack/apps.py", line 41, in ready
    from .api import SlackHookViewSet
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/taiga_contrib_slack/api.py", line 26, in <module>
    from . import tasks
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/taiga_contrib_slack/tasks.py", line 31, in <module>
    from taiga.users.services import get_photo_or_gravatar_url
ImportError: cannot import name 'get_photo_or_gravatar_url'
````

What should I do to fix this error ?

**Comment by superalex** [comment]
It seems your taiga-contrib-slack plugin isn't updated yo should execute something like:

`  pip install --upgrade taiga-contrib-slack`

before the migrate command

**Comment by unixfox** [comment]
Thank you @superalex !
You should add this to the documentation to warn futures users who will make an upgrade.

**Comment by bameda** [comment]
.Done

**Comment by xmltravelgate** [comment]
Hi,

Also upgraded taiga-contrib-google-auth after upgrading taiga-contrib-slack and I'm getting this error when running `manage.py migrate --noinput`

Thanks!!

```
Trying import local.py settings...
Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www/taiga/virtualenv/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/var/www/taiga/virtualenv/lib/python3.5/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/var/www/taiga/virtualenv/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/var/www/taiga/virtualenv/lib/python3.5/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/var/www/taiga/virtualenv/lib/python3.5/site-packages/django/apps/config.py", line 116, in create
    mod = import_module(mod_path)
  File "/var/www/taiga/virtualenv/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/var/www/taiga/app/back/taiga/stats/apps.py", line 20, in <module>
    from .routers import router
  File "/var/www/taiga/app/back/taiga/stats/routers.py", line 18, in <module>
    from taiga.base import routers
  File "/var/www/taiga/app/back/taiga/base/routers.py", line 23, in <module>
    from django.conf.urls import patterns, url
ImportError: cannot import name 'patterns'
```
