### ISSUE TITLE
ImportError after update to 3.0

### ISSUE THREAD

**Issue by Skorpyon** [taigaio/taiga-back#835]
After update under [this tutorial](https://taigaio.github.io/taiga-doc/dist/upgrades.html) on step of migration I got ImportError.

**(taiga)taiga@astracode:~/taiga-back$ python manage.py migrate --noinput**
Trying import local.py settings...
Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/home/taiga/virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/taiga/virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/home/taiga/virtualenvs/taiga/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/taiga/virtualenvs/taiga/lib/python3.4/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/home/taiga/virtualenvs/taiga/lib/python3.4/site-packages/taiga_contrib_slack/apps.py", line 41, in ready
    from .api import SlackHookViewSet
  File "/home/taiga/virtualenvs/taiga/lib/python3.4/site-packages/taiga_contrib_slack/api.py", line 26, in <module>
    from . import tasks
  File "/home/taiga/virtualenvs/taiga/lib/python3.4/site-packages/taiga_contrib_slack/tasks.py", line 31, in <module>
    from taiga.users.services import get_photo_or_gravatar_url
**ImportError: cannot import name 'get_photo_or_gravatar_url'**

**Comment by bameda** [comment]
According to the documentation process you have to upgrade the plugins before run the migration.

There is some related issues: 
https://github.com/taigaio/taiga-contrib-slack/issues/50
https://github.com/taigaio/taiga-back/issues/832
