### ISSUE TITLE
ImportError: cannot import name Celery

### ISSUE THREAD

**Issue by aorborc** [taigaio/taiga-back#838]
**taiga@ip-my-ip:~/taiga-back$ python manage.py migrate --noinput**

Trying import local.py settings...
Trying import development.py settings...
Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 116, in create
    mod = import_module(mod_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/taiga/taiga-back/taiga/__init__.py", line 19, in <module>
    from . import celery
  File "/home/taiga/taiga-back/taiga/celery.py", line 21, in <module>
    from celery import Celery

**ImportError: cannot import name Celery**

**celery 3.1.24 ???** 

The requirements.txt has 3.1.20

**Comment by superalex** [comment]
It seems you didn't activate the virtualenv where taiga is installed before executing the migration?. Taiga uses python3 (from your virtualenv) and in that output I see the python2.7 from your system
