### ISSUE TITLE
Problem sending email after upgrading

### ISSUE THREAD

**Issue by dalareo** [taigaio/taiga-back#844]
Hi, I have a dockerized version of Taiga here: https://github.com/dalareo/docker-taiga

I have upgraded submodules to latest stable version but now I am unable to send emails. I get:

```
10/10/2016 1:44:11 AMTraceback (most recent call last):
10/10/2016 1:44:11 AM  File "/usr/local/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
10/10/2016 1:44:11 AM    response = self.process_exception_by_middleware(e, request)
10/10/2016 1:44:11 AM  File "/usr/local/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
10/10/2016 1:44:11 AM    response = wrapped_callback(request, *callback_args, **callback_kwargs)
10/10/2016 1:44:11 AM  File "/usr/src/taiga-back/taiga/base/api/viewsets.py", line 106, in view
10/10/2016 1:44:11 AM    return self.dispatch(request, *args, **kwargs)
10/10/2016 1:44:11 AM  File "/usr/local/lib/python3.4/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
10/10/2016 1:44:11 AM    return view_func(*args, **kwargs)
10/10/2016 1:44:11 AM  File "/usr/src/taiga-back/taiga/base/api/views.py", line 446, in dispatch
10/10/2016 1:44:11 AM    response = self.handle_exception(exc)
10/10/2016 1:44:11 AM  File "/usr/src/taiga-back/taiga/base/api/views.py", line 443, in dispatch
10/10/2016 1:44:11 AM    response = handler(request, *args, **kwargs)
10/10/2016 1:44:11 AM  File "/usr/src/taiga-back/taiga/auth/api.py", line 132, in register
10/10/2016 1:44:11 AM    return self._public_register(request)
10/10/2016 1:44:11 AM  File "/usr/src/taiga-back/taiga/auth/api.py", line 106, in _public_register
10/10/2016 1:44:11 AM    user = public_register(**data)
10/10/2016 1:44:11 AM  File "/usr/local/lib/python3.4/contextlib.py", line 30, in inner
10/10/2016 1:44:11 AM    return func(*args, **kwds)
10/10/2016 1:44:11 AM  File "/usr/src/taiga-back/taiga/auth/services.py", line 125, in public_register
10/10/2016 1:44:11 AM    send_register_email(user)
10/10/2016 1:44:11 AM  File "/usr/src/taiga-back/taiga/auth/services.py", line 63, in send_register_email
10/10/2016 1:44:11 AM    return bool(email.send())
10/10/2016 1:44:11 AM  File "/usr/local/lib/python3.4/site-packages/django/core/mail/message.py", line 292, in send
10/10/2016 1:44:11 AM    return self.get_connection(fail_silently).send_messages([self])
10/10/2016 1:44:11 AM  File "/usr/local/lib/python3.4/site-packages/django/core/mail/backends/smtp.py", line 100, in send_messages
10/10/2016 1:44:11 AM    new_conn_created = self.open()
10/10/2016 1:44:11 AM  File "/usr/local/lib/python3.4/site-packages/django/core/mail/backends/smtp.py", line 58, in open
10/10/2016 1:44:11 AM    self.connection = connection_class(self.host, self.port, **connection_params)
10/10/2016 1:44:11 AM  File "/usr/local/lib/python3.4/smtplib.py", line 242, in __init__
10/10/2016 1:44:11 AM    (code, msg) = self.connect(host, port)
10/10/2016 1:44:11 AM  File "/usr/local/lib/python3.4/smtplib.py", line 321, in connect
10/10/2016 1:44:11 AM    self.sock = self._get_socket(host, port, self.timeout)
10/10/2016 1:44:11 AM  File "/usr/local/lib/python3.4/smtplib.py", line 292, in _get_socket
10/10/2016 1:44:11 AM    self.source_address)
10/10/2016 1:44:11 AM  File "/usr/local/lib/python3.4/socket.py", line 516, in create_connection
10/10/2016 1:44:11 AM    raise err
10/10/2016 1:44:11 AM  File "/usr/local/lib/python3.4/socket.py", line 507, in create_connection
10/10/2016 1:44:11 AM    sock.connect(sa)
10/10/2016 1:44:11 AMTimeoutError: [Errno 110] Connection timed out
```

My settings file is:  https://raw.githubusercontent.com/dalareo/docker-taiga/master/docker-settings.py

**Comment by superalex** [comment]
Hello @dalareo 

It doesn't seem a problem related to the upgrade, it seems your machine can't connect to the internet, you could check if that machine can resolve DNS names and get data from the network?.

Regards,

**Comment by dalareo** [comment]
Yes. If I ping Google.com from the machine it resolves perfectly

**Comment by superalex** [comment]
The problem seems related to connecting to smtp.sendgrid.net on port 587

**Comment by dalareo** [comment]
I've also trued with Zoho using smtp.zoho.com and my credentials with the same result. Maybe using SSL connections??

**Comment by dalareo** [comment]
SSL connection keeps throwing the same error.  Connection time out. Connecting to that server and port from my command line using telnet throws no error. Any idea @superalex ?

**Comment by dalareo** [comment]
The problem is related to my server security. I use Google Engine instances...

**Comment by superalex** [comment]
Thanks @dalareo
