### ISSUE TITLE
"TypeError: 'NoneType' object is not iterable", when I try to create a project

### ISSUE THREAD

**Issue by enydrueda** [taigaio/taiga-back#854]
When I try to create a project taiga return:

ERROR:2016-10-17 21:40:17,336: Internal Server Error: /admin/projects/project/add/
Traceback (most recent call last):
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/contrib/admin/options.py", line 541, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/contrib/admin/sites.py", line 244, in inner
    return view(request, *args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/contrib/admin/options.py", line 1437, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/usr/lib/python3.4/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/contrib/admin/options.py", line 1378, in changeform_view
    self.save_model(request, new_object, form, not add)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/contrib/admin/options.py", line 991, in save_model
    obj.save()
  File "/home/taiga/taiga-back/taiga/projects/models.py", line 298, in save
    super().save(*args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/models/base.py", line 700, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/models/base.py", line 737, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/dispatch/dispatcher.py", line 192, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/taiga/taiga-back/taiga/projects/signals.py", line 61, in project_post_save
    template.apply_to_project(instance)
  File "/home/taiga/taiga-back/taiga/projects/models.py", line 914, in apply_to_project
    for epic_status in self.epic_statuses:
TypeError: 'NoneType' object is not iterable

**Comment by enydrueda** [comment]
Either admin or web interface

**Comment by bameda** [comment]
ummmm, 

Have you update your taiga instance tu the last version recently?
Have you reload the features like the upgrade section said? 

```
cd taiga-back
workon taiga
python manage.py loaddata initial_project_templates --traceback
```

**Comment by enydrueda** [comment]
Arrrg, I didn't that, thank you

**Comment by bameda** [comment]
:smile_cat: 

you are welcome

**Comment by aberwag** [comment]
:+1:

**Comment by vibhor-trantor** [comment]
👍
