### ISSUE TITLE
500 when creating project

### ISSUE THREAD

**Issue by joaokamun** [taigaio/taiga-back#868]
**Before adding an issue**
Please ensure that your issue is not already reported in our [issues list](https://tree.taiga.io/project/taiga/issues?order_by=-created_date).
If this issue was already reported, remember that you can upvote it to raise its importance.

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When creating a project, it gives a error 500 - It creates the project but with no membership.

**If the current behavior is a bug, please provide the steps to reproduce.**
I don't know exactly when started to give this bug (because when I first set instance, everything was working just fine). You just need to create any project, public or private, with superadmin or normal user.

**What is the expected behavior?**
Create a project correctly.

**Is it happening in taiga.io or in your own instance?**
Own instance.

**What browser/version are you using?**
Chromium 54

**Are there any console errors *(Ctrl + F12)* in red?**
Yeah. I'll show stack trace on log.
```
ERROR:2016-10-25 14:52:46,749: Internal Server Error: /api/v1/projects
Traceback (most recent call last):
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/viewsets.py", line 106, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/views.py", line 446, in dispatch
    response = self.handle_exception(exc)
  File "/home/taiga/taiga-back/taiga/base/api/views.py", line 443, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/mixins.py", line 100, in create
    self.object = validator.save(force_insert=True)
  File "/home/taiga/taiga-back/taiga/base/api/serializers.py", line 1089, in save
    self.object = super().save(**kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/serializers.py", line 648, in save
    self.save_object(self.object, **kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/serializers.py", line 1107, in save_object
    obj.save(**kwargs)
  File "/home/taiga/taiga-back/taiga/projects/models.py", line 291, in save
    super().save(*args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/models/base.py", line 700, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/models/base.py", line 737, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/dispatch/dispatcher.py", line 192, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/taiga/taiga-back/taiga/projects/signals.py", line 61, in project_post_save
    template.apply_to_project(instance)
  File "/home/taiga/taiga-back/taiga/projects/models.py", line 907, in apply_to_project
    for epic_status in self.epic_statuses:
TypeError: 'NoneType' object is not iterable
(END)
```

Thanks for reporting!

**Comment by joaokamun** [comment]
Sorry replicate of #854 !
Didn't search enough!
