### ISSUE TITLE
[bug] 500 Internal Server Error on API user-storage

### ISSUE THREAD

**Issue by alchy58** [taigaio/taiga-back#903]
Hello,

I just finished to install my own instance of Taiga reading the [Setup production guide](https://taigaio.github.io/taiga-doc/dist/setup-production.html).

Taiga works well but I have 500 or 404 error sometimes.
One of them is when I try to update a user story status (from the us, backlog, kanban views), I got 

> PATCH http://taiga.mycloud.com/api/v1/userstories/6 500 Internal Server Error
> {"error": "Server application error"}

Here is the /home/taiga/logs/gunicorn.stderr.log
```
taiga@taiga:~/logs$ cat gunicorn.stderr.log 
ERROR:2016-12-22 17:39:43,246: Internal Server Error: /api/v1/userstories/6
Traceback (most recent call last):
  File "/home/taiga/taiga-back/taiga/events/backends/rabbitmq.py", line 33, in _make_rabbitmq_connection
    (authdata, host) = parse_result.netloc.split("@")
ValueError: not enough values to unpack (expected 2, got 1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/viewsets.py", line 106, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/views.py", line 446, in dispatch
    response = self.handle_exception(exc)
  File "/home/taiga/taiga-back/taiga/base/api/views.py", line 443, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/mixins.py", line 207, in partial_update
    return self.update(request, *args, **kwargs)
  File "/home/taiga/taiga-back/taiga/projects/userstories/api.py", line 276, in update
    return super().update(request, *args, **kwargs)
  File "/usr/lib/python3.5/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/home/taiga/taiga-back/taiga/base/decorators.py", line 60, in decorator
    return func(self, *args, **kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/mixins.py", line 200, in update
    self.post_save(self.object, created=False)
  File "/home/taiga/taiga-back/taiga/projects/userstories/api.py", line 196, in post_save
    status=obj.status)
  File "/home/taiga/taiga-back/taiga/projects/userstories/api.py", line 178, in _reorder_if_needed
    milestone=milestone)
  File "/home/taiga/taiga-back/taiga/projects/userstories/services.py", line 102, in update_userstories_order_in_bulk
    projectid=project.pk)
  File "/home/taiga/taiga-back/taiga/events/events.py", line 102, in emit_event_for_ids
    data=data)
  File "/home/taiga/taiga-back/taiga/events/events.py", line 52, in emit_event
    channel=channel)
  File "/home/taiga/taiga-back/taiga/events/backends/rabbitmq.py", line 52, in emit_event
    connection = _make_rabbitmq_connection(self.url)
  File "/home/taiga/taiga-back/taiga/events/backends/rabbitmq.py", line 35, in _make_rabbitmq_connection
    raise RuntimeError("Invalid url") from e
RuntimeError: Invalid url
```

Which additional informations do you need ?

Thank you

EDIT : 

I have the same error when I try to add multiple US in an Epic.
Stories are well created but not attached to the Epic.
```
ERROR:2016-12-22 18:28:52,089: Internal Server Error: /api/v1/epics/1/related_userstories/bulk_create
Traceback (most recent call last):
  File "/home/taiga/taiga-back/taiga/events/backends/rabbitmq.py", line 33, in _make_rabbitmq_connection
    (authdata, host) = parse_result.netloc.split("@")
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by superalex** [comment]
It seems related to a bad configuration for the asynchronous tasks, could you please show us your changes in local.py?

**Comment by bameda** [comment]
The 404 in user-storage calls is not an error, is because the user doesn't have information saved in his storage space.

**Comment by alchy58** [comment]
Hi @superalex 

Here is my local.py

```
from .common import *

MEDIA_URL = "https://taiga.hostname.fr/media/"
STATIC_URL = "https://taiga.hostname.fr/static/"
ADMIN_MEDIA_PREFIX = "https://taiga.hostname.fr/static/admin/"
SITES["front"]["scheme"] = "https"
SITES["front"]["domain"] = "taiga.hostname.fr"

SECRET_KEY = "secret_key"

DEBUG = False
TEMPLATE_DEBUG = False
PUBLIC_REGISTER_ENABLED = True

from .celery import *

BROKER_URL = 'amqp://guest:guest@localhost:5672//'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ENABLED = True

EVENTS_PUSH_BACKEND = "taiga.events.backends.rabbitmq.EventsPushBackend"
EVENTS_PUSH_BACKEND_OPTIONS = {"url": "amqp://taiga:password@localhost:5672/taiga"}
```

**Comment by superalex** [comment]
Hello @alchy58 

The problem seems related to your celery connection, you could try commenting the lines:

```
BROKER_URL = 'amqp://guest:guest@localhost:5672//'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ENABLED = True

EVENTS_PUSH_BACKEND = "taiga.events.backends.rabbitmq.EventsPushBackend"
EVENTS_PUSH_BACKEND_OPTIONS = {"url": "amqp://taiga:password@localhost:5672/taiga"}
```

To check what's failing exactly

**Comment by alchy58** [comment]
Hi @superalex,

I commented the EVENTS_PUSH_BACKEND* lines and it's working.
I should miss something (or passwords / secrets are too complicated due to specials characters).
As I work alone, I don't need to use events rights ?

**Comment by superalex** [comment]
It could be related to using special characters.

The EVENTS_PUSH_BACKEND is related to the asynchronous mode for Taiga, that mode is faster (especially if there are a lot of users) because the API requests end sooner (in asynchronous mode some tasks are just launched, in synchronous mode the app have to wait for them). 

If you are working alone it's ok to work without taiga events.

**Comment by ilyaoki** [comment]
In my case, adding another slash to the rabbitmq vhost solved the problem
EVENTS_PUSH_BACKEND_OPTIONS = {"url": "amqp://taiga:password@localhost:5672//taiga"}
You also need to change this in settings of taiga-back
