### ISSUE TITLE
celery worker crashes immediately

### ISSUE THREAD

**Issue by jonathanwbayer** [taigaio/taiga-back#916]
Hi,

When I try to launch celery I get the following error (running as taiga; virtualenv'd in)

celery worker -A taiga
Trying import local.py settings...
Traceback (most recent call last):
  File "/opt/taiga/.virtualenvs/taiga/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/opt/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/celery/__main__.py", line 30, in main
    main()
  File "/opt/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/celery/bin/celery.py", line 81, in main
    cmd.execute_from_commandline(argv)
  File "/opt/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/celery/bin/celery.py", line 793, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/opt/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/celery/bin/base.py", line 311, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/opt/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/celery/bin/celery.py", line 785, in handle_argv
    return self.execute(command, argv)
  File "/opt/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/celery/bin/celery.py", line 717, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/opt/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/celery/bin/worker.py", line 179, in run_from_argv
    return self(*args, **options)
  File "/opt/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/celery/bin/base.py", line 274, in __call__
    ret = self.run(*args, **kwargs)
  File "/opt/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/celery/bin/worker.py", line 212, in run
    state_db=self.node_format(state_db, hostname), **kwargs
  File "/opt/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/celery/worker/__init__.py", line 95, in __init__
    self.app.loader.init_worker()
  File "/opt/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/celery/loaders/base.py", line 128, in init_worker
    self.import_default_modules()
  File "/opt/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/celery/loaders/base.py", line 116, in import_default_modules
    signals.import_modules.send(sender=self.app)
  File "/opt/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/celery/utils/dispatch/signal.py", line 166, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/opt/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/vine/promises.py", line 139, in __call__
    return self.throw()
  File "/opt/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/vine/promises.py", line 136, in __call__
    retval = fun(*final_args, **final_kwargs)
  File "/opt/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/celery/app/base.py", line 330, in _autodiscover_tasks
    self.loader.autodiscover_tasks(packages, related_name)
  File "/opt/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/celery/loaders/base.py", line 252, in autodiscover_tasks
    related_name) if mod)
  File "/opt/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/celery/loaders/base.py", line 273, in autodiscover_tasks
    return [find_related_module(pkg, related_name) for pkg in packages]
  File "/opt/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/celery/loaders/base.py", line 273, in <listcomp>
    return [find_related_module(pkg, related_name) for pkg in packages]
  File "/opt/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/celery/loaders/base.py", line 295, in find_related_module
    _imp.find_module(related_name, pkg_path)
  File "/opt/taiga/.virtualenvs/taiga/lib64/python3.5/imp.py", line 270, in find_module
    "not {}".format(type(name)))
RuntimeError: 'list' must be None or a list, not <class 'str'>

**Comment by bameda** [comment]
Have you created some customization? it seems a problem during the autodiscover, something similar to this http://stackoverflow.com/questions/35838989/runtimeerror-list-must-be-none-or-a-list-not-class-str-while-trying-to-s

**Comment by jonathanwbayer** [comment]
None that I'm aware of, just a straight up git pull. a git diff shows no differences; where would i check for this sort of thing?

**Comment by bameda** [comment]
And in your settings/local.py
