### ISSUE TITLE
Can't add members: "No default throttle rate set for 'create-memberships' scope"

### ISSUE THREAD

**Issue by borfo** [taigaio/taiga-back#926]
I have set up Taiga on my own server, following the "Taiga: Setup production environment" instructions.

When I try to add members to a project using ADMIN > MEMBERS > NEW MEMBER, I fill out the form, hit the "CREATE" button, and nothing happens - the form stays up, no invitation email is sent, and no users are added to the project.  This is the case whether the email address I enter in the form is associated with an existing user or not.

I get the following error in gunicorn.stderr.log:

```
Raven is not configured (logging is disabled). Please see the documentation for more information.
ERROR:2017-01-27 04:29:46,405: Internal Server Error: /api/v1/memberships
Traceback (most recent call last):
  File "/home/taiga/production/taiga-back/taiga/base/api/throttling.py", line 118, in get_rate
    return self.THROTTLE_RATES[self.scope]
KeyError: 'create-memberships'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/taiga/production/taiga-back/taiga/base/api/viewsets.py", line 106, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/taiga/production/taiga-back/taiga/base/api/views.py", line 446, in dispatch
    response = self.handle_exception(exc)
  File "/home/taiga/production/taiga-back/taiga/base/api/views.py", line 434, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/taiga/production/taiga-back/taiga/base/api/views.py", line 367, in initial
    self.check_throttles(request)
  File "/home/taiga/production/taiga-back/taiga/base/api/views.py", line 341, in check_throttles
    for throttle in self.get_throttles():
  File "/home/taiga/production/taiga-back/taiga/base/api/views.py", line 289, in get_throttles
    return [throttle() for throttle in self.throttle_classes]
  File "/home/taiga/production/taiga-back/taiga/base/api/views.py", line 289, in <listcomp>
    return [throttle() for throttle in self.throttle_classes]
  File "/home/taiga/production/taiga-back/taiga/base/api/throttling.py", line 96, in __init__
    self.rate = self.get_rate()
  File "/home/taiga/production/taiga-back/taiga/base/api/throttling.py", line 121, in get_rate
    raise ImproperlyConfigured(msg)
django.core.exceptions.ImproperlyConfigured: No default throttle rate set for "create-memberships" scope
Trying import local.py settings...
Raven is not configured (logging is disabled). Please see the documentation for more information.
ERROR:2017-01-27 04:29:56,658: Internal Server Error: /api/v1/memberships/bulk_create
Traceback (most recent call last):
  File "/home/taiga/production/taiga-back/taiga/base/api/throttling.py", line 118, in get_rate
    return self.THROTTLE_RATES[self.scope]
KeyError: 'create-memberships'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/taiga/production/taiga-back/taiga/base/api/viewsets.py", line 106, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/taiga/production/taiga-back/taiga/base/api/views.py", line 446, in dispatch
    response = self.handle_exception(exc)
  File "/home/taiga/production/taiga-back/taiga/base/api/views.py", line 434, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/taiga/production/taiga-back/taiga/base/api/views.py", line 367, in initial
    self.check_throttles(request)
  File "/home/taiga/production/taiga-back/taiga/base/api/views.py", line 341, in check_throttles
    for throttle in self.get_throttles():
  File "/home/taiga/production/taiga-back/taiga/base/api/views.py", line 289, in get_throttles
    return [throttle() for throttle in self.throttle_classes]
  File "/home/taiga/production/taiga-back/taiga/base/api/views.py", line 289, in <listcomp>
    return [throttle() for throttle in self.throttle_classes]
  File "/home/taiga/production/taiga-back/taiga/base/api/throttling.py", line 96, in __init__
    self.rate = self.get_rate()
  File "/home/taiga/production/taiga-back/taiga/base/api/throttling.py", line 121, in get_rate
    raise ImproperlyConfigured(msg)
django.core.exceptions.ImproperlyConfigured: No default throttle rate set for "create-memberships" scope
```

Anyone have any hints as to what might be going wrong?

**Comment by borfo** [comment]
Oops - just figured this out...  I had held onto an old common.py because I had made some changes to it in order to implement a translation, and as a result didn't have some of the throttling settings that should have been in common.py.

Solved by updating common.py to latest stable version, and moving my customizations to local.py.

CLOSED
