### ISSUE TITLE
Role does not exist during backend installation

### ISSUE THREAD

**Issue by dqlopez** [taigaio/taiga-back#927]
Followed the installation procedure [here](https://taigaio.github.io/taiga-doc/dist/setup-production.html), on the **Populate the database with initial basic data**, I encountered the _role does not exist error_:

```
(taiga) dqlopez@ubuntu:~/taiga-back$ python manage.py migrate --noinput
Trying import local.py settings...
Trying import development.py settings...
Raven is not configured (logging is disabled). Please see the documentation for more information.
Traceback (most recent call last):
  File "/home/dqlopez/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/backends/base/base.py", line 199, in ensure_connection
    self.connect()
  File "/home/dqlopez/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/backends/base/base.py", line 171, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/dqlopez/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/backends/postgresql/base.py", line 175, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/dqlopez/.virtualenvs/taiga/lib/python3.5/site-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
psycopg2.OperationalError: FATAL:  role "dqlopez" does not exist

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/home/dqlopez/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/dqlopez/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/dqlopez/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/dqlopez/.virtualenvs/taiga/lib/python3.5/site-packages/raven/contrib/django/management/__init__.py", line 41, in new_execute
    return original_func(self, *args, **kwargs)
  File "/home/dqlopez/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/dqlopez/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 89, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/home/dqlopez/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/home/dqlopez/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/home/dqlopez/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/migrations/loader.py", line 176, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/home/dqlopez/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/migrations/recorder.py", line 65, in applied_migrations
    self.ensure_schema()
  File "/home/dqlopez/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/migrations/recorder.py", line 52, in ensure_schema
    if self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor()):
  File "/home/dqlopez/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/backends/base/base.py", line 231, in cursor
    cursor = self.make_debug_cursor(self._cursor())
  File "/home/dqlopez/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/backends/base/base.py", line 204, in _cursor
    self.ensure_connection()
  File "/home/dqlopez/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/backends/base/base.py", line 199, in ensure_connection
    self.connect()
  File "/home/dqlopez/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/dqlopez/.virtualenvs/taiga/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/dqlopez/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/backends/base/base.py", line 199, in ensure_connection
    self.connect()
  File "/home/dqlopez/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/backends/base/base.py", line 171, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/dqlopez/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/backends/postgresql/base.py", line 175, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/dqlopez/.virtualenvs/taiga/lib/python3.5/site-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
django.db.utils.OperationalError: FATAL:  role "dqlopez" does not exist
```

Am I right that this is Postgres related issue? If thus what is the recommended approach to resolve this?

**Comment by bameda** [comment]
Yes, the installation process recommends creating a user 'taiga' but you have not followed those steps. Now you should to create the user dqlopez in postgresql or use a valid one to create the db.

**Comment by dqlopez** [comment]
There, I miss the replacement of assumed username **taiga**. Thanks!

**Comment by bameda** [comment]
You are welcome

**Comment by LinyanCui** [comment]
Excuse me, I have met the same problem with you. And I tried  several methods recommended on the website. Sadly，none of them worked. Would you please share your solution？Tank you so much!

**Comment by cr05s19xx** [comment]
If you are having this issue, you can try out this tutorial:
https://www.digitalocean.com/community/tutorials/how-to-install-and-use-postgresql-on-ubuntu-18-04

You have to create
-  a role
- a database

**Comment by apatewp** [comment]
> If you are having this issue, you can try out this tutorial:
> https://www.digitalocean.com/community/tutorials/how-to-install-and-use-postgresql-on-ubuntu-18-04
> 
> You have to create
> 
> * a role
> * a database

thank you so much, i am an ultra noob and your help is deeply appreciated.
