### ISSUE TITLE
Error while upgrading to 3.10

### ISSUE THREAD

**Issue by florisvanwoudenberg** [taigaio/taiga-back#951]
While upgrading the self-hosted instance of taiga (ubuntu 14.04LTS), I get this error:
Command python setup.py egg_info failed with error code 1 in /home/taiga/.virtualenvs/taiga/build/asana
Storing debug log for failure in /home/taiga/.pip/pip.log

Any idea?

**Comment by jespino** [comment]
Yes, the asana package use some especial syntax in the setup.py, so you have to upgrade your pip and your setuptools in your virtualenv before.

**Comment by florisvanwoudenberg** [comment]
Ok, I updated pip and setuptools, but I do not see any projects. I see my profile, so there is a db connention, but no projects

**Comment by superalex** [comment]
Are you receiving any errors in your browser console or in taiga-back logs?

**Comment by pvlvsk** [comment]
I have the same problems on Ubuntu 16.04, pip and setuptools latest.

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-9dnzg9q6/asana/

Where I should look into to solve the problem.

**Comment by ABrazaAtArk** [comment]
Upgrading Taiga (ubuntu 14.04LTS) and got the same error. Upgraded pip and setuptools to the latest, still the same issue.

**Comment by jespino** [comment]
Can you paste the complete pip error trace?

**Comment by ABrazaAtArk** [comment]
Ignoring link https://pypi.python.org/packages/27/5d/4c7998cdee7bfcbbed5d68fecf37a9f1780cfe89b3385b206829205b8e43/asana-0.2.0.tar.gz#md5=cddfa7db53ea850c63efc7077910bf79 (from https://pypi.python.org/simple/asana/), version 0.2.0 doesn't match ==0.6.2
  Ignoring link https://pypi.python.org/packages/31/03/0155f952df19ca6a7aa3b6794f1b0c83bcda9cc797c48d048ce209ed503c/asana-0.1.4.tar.gz#md5=30a7f1dc137751f506d688c5f7b0f488 (from https://pypi.python.org/simple/asana/), version 0.1.4 doesn't match ==0.6.2
  Ignoring link https://pypi.python.org/packages/35/93/f393c6e5e7281fab932f04534d16266b9fbe198d92973fd7bde6e9291675/asana-0.5.1.tar.gz#md5=48a22128578b60fb6e2ffa6bad8550cd (from https://pypi.python.org/simple/asana/), version 0.5.1 doesn't match ==0.6.2
  Ignoring link https://pypi.python.org/packages/4d/69/bd94242c7522d634bffafc49b427a39fa4214e5cfdd667dd756fe0b3c440/asana-0.0.3.tar.gz#md5=878cd95f5479c34976d3585818e5ef94 (from https://pypi.python.org/simple/asana/), version 0.0.3 doesn't match ==0.6.2
  Ignoring link https://pypi.python.org/packages/5a/08/fa950e5f74398f1f1e64155442ba1277df11ce83d6505ac374240a85bce0/asana-0.2.2.tar.gz#md5=80a8cdc26a07254593636a30cf0cc92e (from https://pypi.python.org/simple/asana/), version 0.2.2 doesn't match ==0.6.2
  Ignoring link https://pypi.python.org/packages/5c/1f/94d854075cb900eb265726f516e32850a481cf4aecfc7176b9280fc34a49/asana-0.4.0.tar.gz#md5=27c748b5ffd4f0a8b26b9ca89e12e97a (from https://pypi.python.org/simple/asana/), version 0.4.0 doesn't match ==0.6.2
  Ignoring link https://pypi.python.org/packages/67/59/bc098746fd0e8b87c2374ad8bcca442bef54419a0e9204a0508075f65e3b/asana-0.0.1.tar.gz#md5=88c4841468657bd995a686e2917ae769 (from https://pypi.python.org/simple/asana/), version 0.0.1 doesn't match ==0.6.2
  Ignoring link https://pypi.python.org/packages/77/6f/1e6ac37847c90ae4418b62d9d7aaacd073e19aaeaaaf7799e23900547c02/asana-0.6.1.tar.gz#md5=f800bdf96f9e3be6eaf4d1d1e17ac555 (from https://pypi.python.org/simple/asana/), version 0.6.1 doesn't match ==0.6.2
  Ignoring link https://pypi.python.org/packages/8b/b4/2b0b2b04a5f8fcb21c5f10c3295e7a0c96ef9b6d6e9806242fef3a511587/asana-0.1.0-rc.1.tar.gz#md5=6e74ffbad86432e5e91cc6307f690cd9 (from https://pypi.python.org/simple/asana/), version 0.1.0-rc.1 doesn't match ==0.6.2
  Ignoring link https://pypi.python.org/packages/9f/f7/d379d296dd2281f2c50c4ec59304281a76bf251bf1aadb7520106dc1b54a/asana-0.3.0.tar.gz#md5=2e5a75e369d96d1d69d33b51b835e73a (from https://pypi.python.org/simple/asana/), version 0.3.0 doesn't match ==0.6.2
  Ignoring link https://pypi.python.org/packages/b7/30/78affa21ce948f45997358916c3a7909f5465b9bafcd84654891bf511511/asana-0.5.1-py2.py3-none-any.whl#md5=7122a6747d83e1f5f87d27b906be3cde (from https://pypi.python.org/simple/asana/), version 0.5.1 doesn't match ==0.6.2
  Ignoring link https://pypi.python.org/packages/b7/57/7814b6acdaac5937d4e3f108b074addec9fd42be6372d4f22207e07b309f/asana-0.2.1.tar.gz#md5=03a86159f135a72ba7ef02a6ddad96ba (from https://pypi.python.org/simple/asana/), version 0.2.1 doesn't match ==0.6.2
  Ignoring link https://pypi.python.org/packages/e7/8c/e6747b48e4a70c8726431c653dd3aeb83a4d725b66edab3daf32a9630f31/asana-0.5.0.tar.gz#md5=93abccf43abac78857062d7c7d6dad1a (from https://pypi.python.org/simple/asana/), version 0.5.0 doesn't match ==0.6.2
  Ignoring link https://pypi.python.org/packages/e7/8d/ef351dff46ed754d2c44ac3390647b44eb778124d3fceba163a0e7dbbb34/asana-0.0.5.tar.gz#md5=65f7e3569829002b6a0be4c07e91e378 (from https://pypi.python.org/simple/asana/), version 0.0.5 doesn't match ==0.6.2
  Ignoring link https://pypi.python.org/packages/e8/3a/6f81bc84f0603816919ff5d1b268439a02efe3598f47286e5f8d7f4e06e6/asana-0.0.4.tar.gz#md5=5690472e6d7e61552b49ec14f6a7010d (from https://pypi.python.org/simple/asana/), version 0.0.4 doesn't match ==0.6.2
  Ignoring link https://pypi.python.org/packages/ea/d3/d961baa791856438aae6602b63132efcd52f7fd557de107ae7d9fc2f7403/asana-0.1.3.tar.gz#md5=f81bae1c23ac73051e45be5bacb50975 (from https://pypi.python.org/simple/asana/), version 0.1.3 doesn't match ==0.6.2
  Ignoring link https://pypi.python.org/packages/ee/91/7cb91c224bb3c61c74c051c5de88adf1891fefceb44446afefc6e1684b98/asana-0.0.2.tar.gz#md5=31d17be73f7682828ac00f32366a5eef (from https://pypi.python.org/simple/asana/), version 0.0.2 doesn't match ==0.6.2
  Downloading asana-0.6.2.tar.gz
  Downloading from URL https://pypi.python.org/packages/f8/f7/500b4d42b96658f9bd65a9cca6c99ab0134516727eeef4eb1a4fff2626e4/asana-0.6.2.tar.gz#md5=c522740a6ed3492cef93e570d7ddcf16 (from https://pypi.python.org/simple/asana/)
  Running setup.py (path:/home/taiga/.virtualenvs/taiga/build/asana/setup.py) egg_info for package asana
    error in asana setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
    Complete output from command python setup.py egg_info:
    error in asana setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /home/taiga/.virtualenvs/taiga/build/asana
Exception information:
Traceback (most recent call last):
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/pip/req.py", line 1229, in prepare_files
    req_to_install.run_egg_info()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/pip/req.py", line 325, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/pip/util.py", line 697, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command python setup.py egg_info failed with error code 1 in /home/taiga/.virtualenvs/taiga/build/asana


________________________________

**Comment by jespino** [comment]
You have to upgrade setuptools and pip to the last version in pypi not in ubuntu, this means, "pip install --upgrade pip setuptools"

This is clearly related to your pip/setuptools version, because the asana python package use a modern syntax in the install_requires setup information.

**Comment by yangsae** [comment]
jespino's comment helped me a lot.
