### ISSUE TITLE
Pip install error while upgrading to 3.10 at the seciton of backend application

### ISSUE THREAD

**Issue by littleyanglovegithub** [taigaio/taiga-back#960]
when I execute `pip install --upgrade -r requirements.txt` at the section of backend application, show a error:

> Collecting cairocffi (from CairoSVG==2.0.1->-r requirements.txt (line 39))
  Using cached cairocffi-0.8.0.tar.gz
    Complete output from command python setup.py egg_info:
    
    Installed /tmp/pip-build-_t5odueg/cairocffi/.eggs/cffi-1.9.1-py3.5-linux-x86_64.egg
    Searching for pycparser
    Reading https://pypi.python.org/simple/pycparser/
    Downloading https://pypi.python.org/packages/be/64/1bb257ffb17d01f4a38d7ce686809a736837ad4371bcc5c42ba7a715c3ac/pycparser-2.17.tar.gz#md5=ca98dcb50bc1276f230118f6af5a40c7
    Traceback (most recent call last):
      File "/usr/lib/python3.5/urllib/request.py", line 1254, in do_open
        h.request(req.get_method(), req.selector, req.data, headers)
      File "/usr/lib/python3.5/http/client.py", line 1106, in request
        self._send_request(method, url, body, headers)
      File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
        self.endheaders(body)
      File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
        self._send_output(message_body)
      File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
        self.send(msg)
      File "/usr/lib/python3.5/http/client.py", line 877, in send
        self.connect()
      File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/setuptools/ssl_support.py", line 174, in connect
        (self.host, self.port), getattr(self, 'source_address', None)
      File "/usr/lib/python3.5/socket.py", line 693, in create_connection
        for res in getaddrinfo(host, port, 0, SOCK_STREAM):
      File "/usr/lib/python3.5/socket.py", line 732, in getaddrinfo
        for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
    socket.gaierror: [Errno -3] Temporary failure in name resolution
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/setuptools/package_index.py", line 747, in open_url
        return open_with_auth(url, self.opener)
      File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/setuptools/package_index.py", line 948, in _socket_timeout
        return func(*args, **kwargs)
      File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/setuptools/package_index.py", line 1067, in open_with_auth
        fp = opener(request)
      File "/usr/lib/python3.5/urllib/request.py", line 466, in open
        response = self._open(req, data)
      File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
        '_open', req)
      File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
        result = func(*args)
      File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/setuptools/ssl_support.py", line 161, in https_open
        lambda host, **kw: VerifyingHTTPSConn(host, self.ca_bundle, **kw), req
      File "/usr/lib/python3.5/urllib/request.py", line 1256, in do_open
        raise URLError(err)
    urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-_t5odueg/cairocffi/setup.py", line 44, in <module>
        extras_require={'xcb': ['xcffib>=0.3.2']},
      File "/usr/lib/python3.5/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/setuptools/dist.py", line 317, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/setuptools/dist.py", line 372, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/pkg_resources/__init__.py", line 826, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1092, in best_match
        return self.obtain(req, installer)
      File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1104, in obtain
        return installer(requirement)
      File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/setuptools/dist.py", line 440, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 662, in easy_install
        not self.always_copy, self.local_index
      File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/setuptools/package_index.py", line 636, in fetch_distribution
        dist = find(requirement)
      File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/setuptools/package_index.py", line 617, in find
        dist.download_location = self.download(dist.location, tmpdir)
      File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/setuptools/package_index.py", line 566, in download
        found = self._download_url(scheme.group(1), spec, tmpdir)
      File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/setuptools/package_index.py", line 805, in _download_url
        return self._attempt_download(url, filename)
      File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/setuptools/package_index.py", line 811, in _attempt_download
        headers = self._download_to(url, filename)
      File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/setuptools/package_index.py", line 710, in _download_to
        fp = self.open_url(strip_fragment(url))
      File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/setuptools/package_index.py", line 761, in open_url
        % (url, v.reason))
    distutils.errors.DistutilsError: Download error for https://pypi.python.org/packages/be/64/1bb257ffb17d01f4a38d7ce686809a736837ad4371bcc5c42ba7a715c3ac/pycparser-2.17.tar.gz#md5=ca98dcb50bc1276f230118f6af5a40c7: [Errno -3] Temporary failure in name resolution
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-_t5odueg/cairocffi/

what should I do?
I'm looking forward for you reply.

**Comment by bameda** [comment]
Try to do first
```
pip install --upgrade pip setuptools
```
And try again

**Comment by littleyanglovegithub** [comment]
Thank you for you reply, but another error after execute `pip install --upgrade pip setuptools`:

(taiga) taiga@ubuntu2:~/taiga-back$ pip install --upgrade -r requirements.txt 
Collecting git+https://github.com/Xof/django-pglocks.git (from -r requirements.txt (line 33))
  Cloning https://github.com/Xof/django-pglocks.git to /tmp/pip-f50loagp-build
Collecting Django==1.10.6 (from -r requirements.txt (line 1))
  Using cached Django-1.10.6-py2.py3-none-any.whl
Requirement already up-to-date: django-picklefield==0.3.2 in /home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages (from -r requirements.txt (line 3))
Collecting django-sampledatahelper==0.4.1 (from -r requirements.txt (line 4))
  Using cached django-sampledatahelper-0.4.1.tar.gz
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.python.org/simple/versiontools/: [Errno -3] Temporary failure in name resolution -- Some packages may not be found!
    Couldn't find index page for 'versiontools' (maybe misspelled?)
    No local packages or working download links found for versiontools>=1.8
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-h1pkf6k0/django-sampledatahelper/setup.py", line 42, in <module>
        'Topic :: Internet :: WWW/HTTP',
      File "/usr/lib/python3.5/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/setuptools/dist.py", line 317, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/setuptools/dist.py", line 372, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/pkg_resources/__init__.py", line 851, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1123, in best_match
        return self.obtain(req, installer)
      File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1135, in obtain
        return installer(requirement)
      File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/setuptools/dist.py", line 440, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 668, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('versiontools>=1.8')
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-h1pkf6k0/django-sampledatahelper/

**Comment by jespino** [comment]
This line:

> Download error on https://pypi.python.org/simple/versiontools/: [Errno -3] Temporary failure in name resolution -- Some packages may not be found!

Looks like you had a temporary problem with your dns resolution. Can you try again and confirm that this is fixed?

**Comment by littleyanglovegithub** [comment]
I try it again and again and again......, and have fixed it.......
LOL....
Thank you for your help.
