### ISSUE TITLE
Unable to create new projects

### ISSUE THREAD

**Issue by lordloh** [taigaio/taiga-back#973]
**Before adding an issue**
Please ensure that your issue is not already reported in our [issues list](https://tree.taiga.io/project/taiga/issues?order_by=-created_date).
If this issue was already reported, remember that you can upvote it to raise its importance.

**Do you want to request a *feature* or report a *bug*?**
Help solving a problem

**What is the current behavior?**
I try to create a new project and the "Create Project" button grays out with a spinning ring - forever. However, in the `/admin/` under projects, a new project is created, but is not visible to me in the UI and has no owner.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
A new project gets created

**Is it happening in taiga.io or in your own instance?**
Own instance

**What browser/version are you using?**
Latest chrome

**Are there any console errors *(Ctrl + F12)* in red?**
Yes. 500 Error on `/api/v1/projects`
Thanks for reporting!

`gunicorn.stderr.log`
```
taiga@ratnavali:~/logs$ cat gunicorn.stderr.log
[2017-04-01 23:49:29 -0500] [8034] [INFO] Starting gunicorn 19.6.0
[2017-04-01 23:49:29 -0500] [8034] [INFO] Listening at: http://127.0.0.1:8001 (8034)
[2017-04-01 23:49:29 -0500] [8034] [INFO] Using worker: sync
[2017-04-01 23:49:29 -0500] [8037] [INFO] Booting worker with pid: 8037
[2017-04-01 23:49:29 -0500] [8039] [INFO] Booting worker with pid: 8039
[2017-04-01 23:49:29 -0500] [8041] [INFO] Booting worker with pid: 8041
Trying import local.py settings...
ERROR:2017-04-02 04:56:06,763: Internal Server Error: /api/v1/projects
Traceback (most recent call last):
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/viewsets.py", line 106, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/views.py", line 461, in dispatch
    response = self.handle_exception(exc)
  File "/home/taiga/taiga-back/taiga/base/api/views.py", line 458, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/mixins.py", line 100, in create
    self.object = validator.save(force_insert=True)
  File "/home/taiga/taiga-back/taiga/base/api/serializers.py", line 1115, in save
    self.object = super().save(**kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/serializers.py", line 648, in save
    self.save_object(self.object, **kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/serializers.py", line 1133, in save_object
    obj.save(**kwargs)
  File "/home/taiga/taiga-back/taiga/projects/models.py", line 299, in save
    super().save(*args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/models/base.py", line 796, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/models/base.py", line 833, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/dispatch/dispatcher.py", line 191, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/taiga/taiga-back/taiga/projects/signals.py", line 65, in project_post_save
    template.apply_to_project(instance)
  File "/home/taiga/taiga-back/taiga/projects/models.py", line 978, in apply_to_project
    for epic_status in self.epic_statuses:
TypeError: 'NoneType' object is not iterable

```

**Comment by bameda** [comment]
It seems that you have upgraded your instance but you don't follow all the steps from the [doc](https://taigaio.github.io/taiga-doc/dist/upgrades.html). You should to reload the fixtures with:

```
cd taiga-back
workon taiga
python manage.py loaddata initial_project_templates --traceback
```

**Comment by lordloh** [comment]
Thanks a lot. That fixed the problem. The upgrade instructions caused me the problem. The default python on my system is 2.6. I forgot that I had to replace all `python` and `pip` with `python3` and `pip3` :-(

**Comment by bameda** [comment]
Great!!
(and wow! python 2.6 is a very old version)

**Comment by lordloh** [comment]
Sorry... 2.7.12
I rounded up ;-)
