### ISSUE TITLE
CairoSVG wrong version

### ISSUE THREAD

**Issue by fnoop** [taigaio/taiga-back#974]
When upgrading taiga-back to 3.1.0, I get a error upgrading pip requirements:

```
Collecting CairoSVG==2.0.1 (from -r requirements.txt (line 39))
  Using cached CairoSVG-2.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-lJJoKi/CairoSVG/setup.py", line 24, in <module>
        with open(init_path, 'r', encoding='utf-8') as fd:
    TypeError: 'encoding' is an invalid keyword argument for this function

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-lJJoKi/CairoSVG/
```

CairoSVG >=2.0.0 is for python3 only.  Latest cairosvg compatible with python 2.7 is 1.0.22:
https://github.com/Kozea/CairoSVG/issues/115

Running on CentOS 7.3.1611.

**Comment by fnoop** [comment]
If I change requirements.txt to use CairoSVG 1.0.22 then the pip upgrade goes fine.  If I then try to migrate, I get this:

python manage.py migrate --noinput
Trying import local.py settings...
Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/www/apps/taiga/.virtualenvs/taiga/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/srv/www/apps/taiga/.virtualenvs/taiga/lib/python2.7/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/srv/www/apps/taiga/.virtualenvs/taiga/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/srv/www/apps/taiga/.virtualenvs/taiga/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/srv/www/apps/taiga/.virtualenvs/taiga/lib/python2.7/site-packages/django/apps/config.py", line 116, in create
    mod = import_module(mod_path)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/srv/www/apps/taiga/taiga-back/taiga/__init__.py", line 19, in <module>
    from . import celery
  File "/srv/www/apps/taiga/taiga-back/taiga/celery.py", line 21, in <module>
    from celery import Celery
ImportError: cannot import name Celery
```

If I do `python3 manage.py migrate --noinput` then it goes fine.

Has everything moved to python3?

**Comment by sbhalim** [comment]
Don't change CairoSVG requirement. You should install the requirements with ```pip3``` (Python 3).
A proper way is to do ```workon taiga``` before running ```pip install```.
I think the installation docs need to include this.

**Comment by fnoop** [comment]
Yup everything working with python3/pip3.  Should be noted in the docs, as python/pip2 is the default at least in CentOS.
