### ISSUE TITLE
Cannot create any new project

### ISSUE THREAD

**Issue by yomguy** [taigaio/taiga-back#975]
Hi,

After upgrading to 3.1, I cannot create any new project:

```
Traceback (most recent call last):
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/viewsets.py", line 106, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/views.py", line 461, in dispatch
    response = self.handle_exception(exc)
  File "/home/taiga/taiga-back/taiga/base/api/views.py", line 458, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/mixins.py", line 100, in create
    self.object = validator.save(force_insert=True)
  File "/home/taiga/taiga-back/taiga/base/api/serializers.py", line 1115, in save
    self.object = super().save(**kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/serializers.py", line 648, in save
    self.save_object(self.object, **kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/serializers.py", line 1133, in save_object
    obj.save(**kwargs)
  File "/home/taiga/taiga-back/taiga/projects/models.py", line 299, in save
    super().save(*args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/models/base.py", line 796, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/models/base.py", line 833, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/dispatch/dispatcher.py", line 191, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/taiga/taiga-back/taiga/projects/signals.py", line 65, in project_post_save
    template.apply_to_project(instance)
  File "/home/taiga/taiga-back/taiga/projects/models.py", line 1092, in apply_to_project
    for ca in self.epic_custom_attributes:
TypeError: 'NoneType' object is not iterable
```

Thanks for this GREAT app!

**Comment by superalex** [comment]
Hello @yomguy 

It seems to be a duplicated from https://github.com/taigaio/taiga-back/issues/854

**Comment by yomguy** [comment]
Hi @superalex
Oh this is indeed fixed by applying:

`python manage.py loaddata initial_project_templates --traceback` 

But, as I have already applied this during the last 3.0 upgrade, it may be good to add it to the default upgrade process in the doc : https://taigaio.github.io/taiga-doc/dist/upgrades.html

Sorry for the noise, Thanks!
