### ISSUE TITLE
can't create superuser

### ISSUE THREAD

**Issue by sonnyESP24** [taigaio/taiga-back#979]
is_staff issue when creating superuser, hoping it will be fixed

**Comment by tawanda** [comment]
Populate the database with initial basic data

```
python manage.py migrate --noinput
python manage.py loaddata initial_user
python manage.py loaddata initial_project_templates
python manage.py compilemessages
python manage.py collectstatic --noinput
```

This creates a new user `admin` with password `123123`

Maybe you should try reading the docs

https://taigaio.github.io/taiga-doc/dist/setup-production.html

**Comment by agorton-nvl** [comment]
@tawanda Your solution doesn't have anything to do with the stated problem. The docs also wouldn't address anything of this nature. Pretty far off base. 

The issue is when running the Django specific command: `python manage.py createsuperuser` yields the following error:

(taiga):~/taiga-back$ ./manage.py createsuperuser
Trying import local.py settings...
Username: xxxx
Email address: xxxx
Password:
Password (again):
Traceback (most recent call last):
  File "./manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.6/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 63, in execute
    return super(Command, self).execute(*args, **options)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.6/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 183, in handle
    self.UserModel._default_manager.db_manager(database).create_superuser(**user_data)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.6/site-packages/django/contrib/auth/models.py", line 170, in create_superuser
    return self._create_user(username, email, password, **extra_fields)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.6/site-packages/django/contrib/auth/models.py", line 151, in _create_user
    user = self.model(username=username, email=email, **extra_fields)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 68, in __init__
    super(AbstractBaseUser, self).__init__(*args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.6/site-packages/django/db/models/base.py", line 573, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
TypeError: 'is_staff' is an invalid keyword argument for this function
```

The last line reveals the error, `TypeError: 'is_staff' is an invalid keyword argument for this function`

It's disconcerting that these errors continue to be unaddressed more than two years later.

**Comment by migonzalvar** [comment]
@agorton-nvl Taiga uses a custom auth user model (see https://docs.djangoproject.com/en/1.11/topics/auth/customizing/#auth-custom-user) and it does not implement every property of a regular django contrib auth model. So, actually, this it is not an error.

To create the default superadmin you should use the following command:

```
python manage.py loaddata initial_user
```

It will create the default superuser `admin`.

Then you can use its superpowers to promote any regular user to superuser using Django admin web interface.

If you need to create programmatically antoher superuser, you could do it this way:

```
from taiga.users.models import User
username = 'anotheradmin'
email = 'anotheradmin@example.com'
password = '123123'
user = User.objects.create(username=username, email=email, is_superuser=True)
user.set_password(password)
user.save()
```
