### ISSUE TITLE
problem with Celery ubuntu 16.04

### ISSUE THREAD

**Issue by pierluigi65** [taigaio/taiga-back#981]
I have 3 errors in trying to install Taiga backend 3, following all the instuctions you write here:
http://taigaio.github.io/taiga-doc/dist/setup-production.html
Some hours spent for nothing...
Hoping the software is better.
I'm thinking to change it before testing....
Paradox : Taiga would help an organization to coding better .... 
But leave my frustration this is my last error output when i send the command:

python manage.py migrate --noinput

Trying import local.py settings...
Trying import development.py settings...
Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 116, in create
    mod = import_module(mod_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/pierluigi/taiga-back/taiga/__init__.py", line 19, in <module>
    from . import celery
  File "/home/pierluigi/taiga-back/taiga/celery.py", line 21, in <module>
    from celery import Celery
ImportError: cannot import name Celery

If there are so many problems with python versions why don't make a virtual machine where everything works fine? Or make a .deb package with a ppa

I know that could be a virtualenv problem but I didn't found any instuction about using it ...

**Comment by theriverman** [comment]
Hello,

I believe you might have missed a command on the way.

First of all: Create a user:group pair

`sudo adduser taiga`

Then:

`sudo su taiga`

Then 
`cd ~`
`git clone https://github.com/taigaio/taiga-back.git taiga-back`
`cd taiga-back`
`git checkout stable`
`mkvirtualenv -p /usr/bin/python3.5 taiga`
`pip install -r requirements.txt`

Then
`python manage.py migrate --noinput`

... and issue the rest of the commands from the documentation.

**Comment by pierluigi65** [comment]
wow thanks.
And why in the documentation is not mentioned to create a new user? can you please modify the documentation so we can finish our installation witout problems?
http://taigaio.github.io/taiga-doc/dist/setup-production.html
thank you

**Comment by theriverman** [comment]
You're welcome. 

It is actually documented, but is not crystal clear. 
Quoting from the beginning:

"We assume the following:
ip: 80.88.23.45

hostname:example.com (which points to 80.88.23.45)

username: taiga

system ram >=1GB(needed for compilation of lxml)

"



/riverman

**Comment by pierluigi65** [comment]
Hi we don't reach the goal...
I have another problem with postgres. Postgres is working fine...
Here the log:

python manage.py migrate --noinput
Trying import local.py settings...
Trying import development.py settings...
Traceback (most recent call last):
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/backends/base/base.py", line 199, in ensure_connection
    self.connect()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/backends/base/base.py", line 171, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 83, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/migrations/loader.py", line 52, in __init__
    self.build_graph()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/migrations/loader.py", line 203, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/migrations/recorder.py", line 65, in applied_migrations
    self.ensure_schema()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/migrations/recorder.py", line 52, in ensure_schema
    if self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor()):
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/backends/base/base.py", line 231, in cursor
    cursor = self.make_debug_cursor(self._cursor())
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/backends/base/base.py", line 204, in _cursor
    self.ensure_connection()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/backends/base/base.py", line 199, in ensure_connection
    self.connect()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/backends/base/base.py", line 199, in ensure_connection
    self.connect()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/backends/base/base.py", line 171, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

**Comment by theriverman** [comment]
I'm not an expert, so the following is gonna be only a guess.

I think you already have a database created (name=taiga) and probably messed up with broken data.

Log on as postgres
`sudo su postgres`
then
`psql -l`
and check if you have a database named taiga already.
if so, drop that database
[note: this will remove all data from the database, so proceed only if you don't have anything stored in it!]
`psql -U postgres -c "drop database taiga"`

Create the database again
`sudo -u postgres createdb taiga -O taiga`

then proceed with my previous commands in order.

**Comment by pierluigi65** [comment]
I create a new database but the error is the same...

**Comment by superalex** [comment]
Hello @pierluigi65 

Are you sure postgresql is running correctly in the server?, did you try connecting to it to ensure it's working ok?

If you are having problems with the installation you could also use taiga-scripts -> https://taigaio.github.io/taiga-doc/dist/setup-alternatives.html
