### ISSUE TITLE
Internal Server Error: /api/v1/gitlab-hook

### ISSUE THREAD

**Issue by lobocode** [taigaio/taiga-back#982]
Hello everybody!
When I try test hook with gitlab, print this error in gunicorn.stdeer.log:

`ERROR:2017-04-11 14:41:25,372: Internal Server Error: /api/v1/gitlab-hook
Traceback (most recent call last):
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/viewsets.py", line 106, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/views.py", line 461, in dispatch
    response = self.handle_exception(exc)
  File "/home/taiga/taiga-back/taiga/base/api/views.py", line 458, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/taiga/taiga-back/taiga/hooks/api.py", line 79, in create
    event_hook.process_event()
  File "/home/taiga/taiga-back/taiga/hooks/event_hooks.py", line 264, in process_event
    user=self.get_user(commit['user_id'], self.platform_slug))
  File "/home/taiga/taiga-back/taiga/hooks/event_hooks.py", line 55, in get_user
    user = get_user_model().objects.get(is_system=True, username__startswith=platform)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/models/query.py", line 385, in get
    self.model._meta.object_name
taiga.users.models.DoesNotExist: User matching query does not exist.
`
What's the problem?

**Comment by lobocode** [comment]
Solved!
I fix the problem. Just run the following code from check if gitlab account is there:
`import uuid
random_hash = uuid.uuid4().hex
User.objects.filter(is_system=True, username__startswith="gitlab").count()
`
If not, or print 0 value, then, run the code:
`import uuid
random_hash = uuid.uuid4().hex
user = User.objects.create(
username="gitlab-{}".format(random_hash),
email="gitl...@taiga.io".format(random_hash),
full_name="GitLab",
is_active=False,
is_system=True,
bio="",
)
`
