### ISSUE TITLE
Error creating a new private Scrum project

### ISSUE THREAD

**Issue by puetzstef** [taigaio/taiga-back#996]
**Before adding an issue**
Please ensure that your issue is not already reported in our [issues list](https://tree.taiga.io/project/taiga/issues?order_by=-created_date).
If this issue was already reported, remember that you can upvote it to raise its importance.

**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
I can't create a new private scrum project
**If the current behavior is a bug, please provide the steps to reproduce.**
It can be reproduced by creating a Scrum project
**What is the expected behavior?**
The project should be created after clicking the create button
**Is it happening in taiga.io or in your own instance?**
Own instance
**What browser/version are you using?**
Google Chrome newest Version
Newest Taiga stable version 3.1.0 with latest git checkout.
**Are there any console errors *(Ctrl + F12)* in red?**
POST https://projects.absglobalfactoring.de/api/v1/projects 500 (Internal Server Error) angular.js:11756
Thanks for reporting!
![errorsavingnewproject](https://cloud.githubusercontent.com/assets/25301590/26191839/bb8c1e52-3baf-11e7-9c21-56d1ccd14960.JPG)

**Comment by superalex** [comment]
Hello,

Could you please check your instance logs folder to see the full stacktrace associated to that 500 error.

**Comment by puetzstef** [comment]
Hi superalex, 
thank you for your reply. I found the following stacktrace in the gunicorn.stderr.log. It seems to be the right one:

ERROR:2017-05-18 07:59:04,021: Internal Server Error: /api/v1/projects
Traceback (most recent call last):
  File "/var/www/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/var/www/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/var/www/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/www/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/taiga/taiga-back/taiga/base/api/viewsets.py", line 106, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/www/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/www/taiga/taiga-back/taiga/base/api/views.py", line 461, in dispatch
    response = self.handle_exception(exc)
  File "/var/www/taiga/taiga-back/taiga/base/api/views.py", line 458, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/www/taiga/taiga-back/taiga/base/api/mixins.py", line 100, in create
    self.object = validator.save(force_insert=True)
  File "/var/www/taiga/taiga-back/taiga/base/api/serializers.py", line 1115, in save
    self.object = super().save(**kwargs)
  File "/var/www/taiga/taiga-back/taiga/base/api/serializers.py", line 648, in save
    self.save_object(self.object, **kwargs)
  File "/var/www/taiga/taiga-back/taiga/base/api/serializers.py", line 1133, in save_object
    obj.save(**kwargs)
  File "/var/www/taiga/taiga-back/taiga/projects/models.py", line 299, in save
    super().save(*args, **kwargs)
  File "/var/www/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/models/base.py", line 796, in save
    force_update=force_update, update_fields=update_fields)
  File "/var/www/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/models/base.py", line 833, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/var/www/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/dispatch/dispatcher.py", line 191, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/var/www/taiga/taiga-back/taiga/projects/signals.py", line 65, in project_post_save
    template.apply_to_project(instance)
  File "/var/www/taiga/taiga-back/taiga/projects/models.py", line 1092, in apply_to_project
    for ca in self.epic_custom_attributes:
TypeError: 'NoneType' object is not iterable

**Comment by superalex** [comment]
Is it possible you upgraded from a previous taiga version? https://taigaio.github.io/taiga-doc/dist/upgrades.html#_3_0_0_3_1_0_2

**Comment by puetzstef** [comment]
Yes, you are right.

**Comment by puetzstef** [comment]
I missed the celery part because I thought this would only apply for an Ubuntu 14.04 to Ubuntu 16.04 upgrade. I will check the upgrade guide and tell you if everything is fine after correcting the celery config.

**Comment by puetzstef** [comment]
Hi superalex,
it's working again after following your hint. :) The issue was the celery config. Great! Thank you very much for the fast reponse and help!

**Comment by puetzstef** [comment]
Issue was solved.

**Comment by superalex** [comment]
You are welcome @puetzstef  :+1:
