### ISSUE TITLE
Taiga setup fails

### ISSUE THREAD

**Issue by Arthanarisamy** [taigaio/taiga-back#997]
Running pip install -r requirements.txt fails with below error. I am not a Python user, sorry if i miss something very basic.
Following the steps mentioned in below link
     https://taigaio.github.io/taiga-doc/dist/setup-production.html

1) I did ensure that the python version is `Python 3.5.3` with command python -V
2) Was able to create virtual environment successfully and it is pointing to Python 3.5.3(/home/user/.virtualenvs/taiga/bin/python)
3) All other dependencies are installed

Note -: I have older versions of Python too installed in my machine, hope it shouldn't be a problem since Python version is set to latest.

    Downloading/unpacking cryptography==1.7.1 (from -r requirements.txt (line 41))
    Downloading cryptography-1.7.1.tar.gz (420kB): 420kB downloaded
    Running setup.py (path:/home/admin/.virtualenvs/taiga/build/cryptography/setup.py) egg_info for 
    package cryptography
    
    no previously-included directories found matching 'docs/_build'
    warning: no previously-included files matching '*' found under directory 'vectors'
    Downloading/unpacking PyJWT==1.4.2 (from -r requirements.txt (line 42))
    Downloading PyJWT-1.4.2-py2.py3-none-any.whl
    Downloading/unpacking asana==0.6.2 (from -r requirements.txt (line 43))
    Downloading asana-0.6.2.tar.gz
    Running setup.py (path:/home/admin/.virtualenvs/taiga/build/asana/setup.py) egg_info for package 
    asana
    error in asana setup command: 'install_requires' must be a string or list of strings containing valid 
    project/version requirement specifiers
    Complete output from command python setup.py egg_info:
    error in asana setup command: 'install_requires' must be a string or list of strings containing valid 
    project/version requirement specifiers

**Comment by theriverman** [comment]
Hi,

First remove all data you created so far to avoid confusion later.
rm -R /home/admin/.virtualenvs/taiga
rm -R <path to taiga back, front, events>

Once it's done, create a new user
sudo adduser taiga
sudo su taiga
cd ~

Then start over the whole process as user taiga and see if you succeed.
Good luck

**Comment by Arthanarisamy** [comment]
Hi,
Thanks for the reply, i did try removing the virtual environment and starting things all over from the beginning except for creating a new user. Tried that as well, but still no luck, fails with the same error.

    (taiga)taiga@lap132:~/taiga/taiga-back$ python -V
    Python 3.5.3

`
  (taiga)taiga@lap132:~/taiga/taiga-back$ pip install -r requirements.txt
  Downloading/unpacking asana==0.6.2 (from -r requirements.txt (line 43))
  Downloading asana-0.6.2.tar.gz
  Running setup.py (path:/home/taiga/.virtualenvs/taiga/build/asana/setup.py) egg_info for package 
  asana
    error in asana setup command: 'install_requires' must be a string or list of strings containing valid 
  project/version requirement specifiers
    Complete output from command python setup.py egg_info:
    error in asana setup command: 'install_requires' must be a string or list of strings containing valid 
  project/version requirement specifiers`

Any further suggestions please?

**Comment by Arthanarisamy** [comment]
Tried upgrading the version of pip and pip setuptools, that didn't help too.
Any help?

`(taiga)taiga@lap132:~/taiga/taiga-back$ pip -V
pip 9.0.1 from /home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages (python 3.5)`

Below the trace for your reference

	(taiga)taiga@ixedlap132:~/taiga/taiga-back$ pip install -r requirements.txt
    Collecting git+https://github.com/Xof/django-pglocks.git (from -r requirements.txt (line 33))
    Cloning https://github.com/Xof/django-pglocks.git to /tmp/pip-pyfg8d48-build
    Collecting Django==1.10.6 (from -r requirements.txt (line 1))
    Downloading Django-1.10.6-py2.py3-none-any.whl (6.8MB)
    100% |████████████████████████████████| 6.8MB 176kB/s 
    Collecting django-picklefield==0.3.2 (from -r requirements.txt (line 3))
    Downloading django_picklefield-0.3.2-py2.py3-none-any.whl
    Collecting django-sampledatahelper==0.4.1 (from -r requirements.txt (line 4))
    Downloading django-sampledatahelper-0.4.1.tar.gz
    Collecting gunicorn==19.6.0 (from -r requirements.txt (line 5))
    Downloading gunicorn-19.6.0-py2.py3-none-any.whl (114kB)
    100% |████████████████████████████████| 122kB 220kB/s 
    Collecting psycopg2==2.7 (from -r requirements.txt (line 6))
    Downloading psycopg2-2.7-cp35-cp35m-manylinux1_x86_64.whl (2.1MB)
    100% |████████████████████████████████| 2.1MB 246kB/s 
    Collecting Pillow==3.4.2 (from -r requirements.txt (line 7))
    Downloading Pillow-3.4.2-cp35-cp35m-manylinux1_x86_64.whl (5.6MB)
    100% |████████████████████████████████| 5.6MB 188kB/s 
    Collecting pytz==2016.10 (from -r requirements.txt (line 8))
    Downloading pytz-2016.10-py2.py3-none-any.whl (483kB)
    100% |████████████████████████████████| 491kB 2.7MB/s 
    Requirement already satisfied: six==1.10.0 in /home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages (from -r requirements.txt (line 9))
    Collecting amqp==2.1.4 (from -r requirements.txt (line 10))
    Downloading amqp-2.1.4-py2.py3-none-any.whl (49kB)
    100% |████████████████████████████████| 51kB 4.9MB/s 
    Collecting djmail==1.0.1 (from -r requirements.txt (line 11))
    Downloading djmail-1.0.1.tar.gz
    Collecting django-jinja==2.2.2 (from -r requirements.txt (line 12))
    Downloading django-jinja-2.2.2.tar.gz
    Collecting jinja2==2.9.5 (from -r requirements.txt (line 13))
    Downloading Jinja2-2.9.5-py2.py3-none-any.whl (340kB)
    100% |████████████████████████████████| 348kB 436kB/s 
    Collecting pygments==2.2.0 (from -r requirements.txt (line 14))
    Downloading Pygments-2.2.0-py2.py3-none-any.whl (841kB)
    100% |████████████████████████████████| 849kB 355kB/s 
    Collecting django-sites==0.9 (from -r requirements.txt (line 15))
    Downloading django-sites-0.9.tar.gz
    Collecting Markdown==2.6.8 (from -r requirements.txt (line 16))
    Downloading Markdown-2.6.8.tar.gz (307kB)
    100% |████████████████████████████████| 317kB 402kB/s 
    Collecting fn==0.4.3 (from -r requirements.txt (line 17))
    Downloading fn-0.4.3.tar.gz
    Collecting diff-match-patch==20121119 (from -r requirements.txt (line 18))
    Downloading diff-match-patch-20121119.tar.gz (54kB)
    100% |████████████████████████████████| 61kB 4.8MB/s 
    Collecting requests==2.13.0 (from -r requirements.txt (line 19))
    Downloading requests-2.13.0-py2.py3-none-any.whl (584kB)
    100% |████████████████████████████████| 593kB 368kB/s 
    Collecting requests-oauthlib==0.8.0 (from -r requirements.txt (line 20))
    Downloading requests_oauthlib-0.8.0-py2.py3-none-any.whl
    Collecting webcolors==1.7 (from -r requirements.txt (line 21))
    Downloading webcolors-1.7.tar.gz
    Collecting django-sr==0.0.4 (from -r requirements.txt (line 22))
    Downloading django-sr-0.0.4.tar.gz
    Collecting easy-thumbnails==2.3 (from -r requirements.txt (line 23))
    Downloading easy_thumbnails-2.3-py2.py3-none-any.whl (96kB)
    100% |████████████████████████████████| 102kB 429kB/s 
    Collecting celery==4.0.2 (from -r requirements.txt (line 24))
    Downloading celery-4.0.2-py2.py3-none-any.whl (396kB)
    100% |████████████████████████████████| 399kB 398kB/s 
    Collecting redis==2.10.5 (from -r requirements.txt (line 25))
    Downloading redis-2.10.5-py2.py3-none-any.whl (60kB)
    100% |████████████████████████████████| 61kB 265kB/s 
    Collecting Unidecode==0.4.20 (from -r requirements.txt (line 26))
    Downloading Unidecode-0.04.20-py2.py3-none-any.whl (228kB)
    100% |████████████████████████████████| 235kB 218kB/s 
    Collecting raven==6.0.0 (from -r requirements.txt (line 27))
    Downloading raven-6.0.0-py2.py3-none-any.whl (279kB)
    100% |████████████████████████████████| 286kB 215kB/s 
    Collecting bleach==1.5.0 (from -r requirements.txt (line 28))
    Downloading bleach-1.5.0-py2.py3-none-any.whl
    Collecting django-ipware==1.1.6 (from -r requirements.txt (line 29))
    Downloading django-ipware-1.1.6.tar.gz
    Collecting premailer==3.0.1 (from -r requirements.txt (line 30))
    Downloading premailer-3.0.1-py2.py3-none-any.whl
    Collecting cssutils==1.0.1 (from -r requirements.txt (line 31))
    Downloading cssutils-1.0.1.tar.gz (353kB)
    100% |████████████████████████████████| 358kB 214kB/s 
    Collecting lxml==3.7.3 (from -r requirements.txt (line 32))
    Downloading lxml-3.7.3-cp35-cp35m-manylinux1_x86_64.whl (7.1MB)
    100% |████████████████████████████████| 7.1MB 161kB/s 
    Collecting pyjwkest==1.3.2 (from -r requirements.txt (line 34))
    Downloading pyjwkest-1.3.2.tar.gz (41kB)
    100% |████████████████████████████████| 51kB 6.9MB/s 
    Collecting python-dateutil==2.6.0 (from -r requirements.txt (line 35))
    Downloading python_dateutil-2.6.0-py2.py3-none-any.whl (194kB)
    100% |████████████████████████████████| 194kB 4.5MB/s 
    Collecting netaddr==0.7.19 (from -r requirements.txt (line 36))
    Downloading netaddr-0.7.19-py2.py3-none-any.whl (1.6MB)
    100% |████████████████████████████████| 1.6MB 282kB/s 
    Collecting serpy==0.1.1 (from -r requirements.txt (line 37))
    Downloading serpy-0.1.1-py2.py3-none-any.whl
    Collecting psd-tools==1.4 (from -r requirements.txt (line 38))
    Downloading psd-tools-1.4.tar.gz (135kB)
    100% |████████████████████████████████| 143kB 432kB/s 
    Collecting CairoSVG==2.0.1 (from -r requirements.txt (line 39))
    Downloading CairoSVG-2.0.1-py3-none-any.whl (101kB)
    100% |████████████████████████████████| 102kB 417kB/s 
    Collecting python-magic==0.4.13 (from -r requirements.txt (line 40))
    Downloading python_magic-0.4.13-py2.py3-none-any.whl
    Collecting cryptography==1.7.1 (from -r requirements.txt (line 41))
    Downloading cryptography-1.7.1.tar.gz (420kB)
    100% |████████████████████████████████| 430kB 394kB/s 
    Collecting PyJWT==1.4.2 (from -r requirements.txt (line 42))
    Downloading PyJWT-1.4.2-py2.py3-none-any.whl
    Collecting asana==0.6.2 (from -r requirements.txt (line 43))
    Downloading asana-0.6.2.tar.gz
    Collecting sampledata (from django-sampledatahelper==0.4.1->-r requirements.txt (line 4))
    Downloading sampledata-0.3.7.tar.gz (178kB)
    100% |████████████████████████████████| 184kB 416kB/s 
    Collecting vine>=1.1.3 (from amqp==2.1.4->-r requirements.txt (line 10))
    Downloading vine-1.1.3-py2.py3-none-any.whl
    Collecting MarkupSafe>=0.23 (from jinja2==2.9.5->-r requirements.txt (line 13))
    Downloading MarkupSafe-1.0.tar.gz
    Collecting oauthlib>=0.6.2 (from requests-oauthlib==0.8.0->-r requirements.txt (line 20))
    Downloading oauthlib-2.0.2.tar.gz (125kB)
    100% |████████████████████████████████| 133kB 434kB/s 
    Collecting kombu<5.0,>=4.0.2 (from celery==4.0.2->-r requirements.txt (line 24))
    Downloading kombu-4.0.2-py2.py3-none-any.whl (178kB)
    100% |████████████████████████████████| 184kB 418kB/s 
    Collecting billiard<3.6.0,>=3.5.0.2 (from celery==4.0.2->-r requirements.txt (line 24))
    Downloading billiard-3.5.0.2-py3-none-any.whl (102kB)
    100% |████████████████████████████████| 102kB 430kB/s 
    Collecting contextlib2 (from raven==6.0.0->-r requirements.txt (line 27))
    Downloading contextlib2-0.5.5-py2.py3-none-any.whl
    Collecting html5lib!=0.9999,!=0.99999,<0.99999999,>=0.999 (from bleach==1.5.0->-r requirements.txt (line 28))
    Downloading html5lib-0.9999999.tar.gz (889kB)
    100% |████████████████████████████████| 890kB 352kB/s 
    Collecting cssselect (from premailer==3.0.1->-r requirements.txt (line 30))
    Downloading cssselect-1.0.1-py2.py3-none-any.whl
    Collecting pycryptodomex (from pyjwkest==1.3.2->-r requirements.txt (line 34))
    Downloading pycryptodomex-3.4.6.tar.gz (6.5MB)
    100% |████████████████████████████████| 6.5MB 199kB/s 
    Collecting future (from pyjwkest==1.3.2->-r requirements.txt (line 34))
    Downloading future-0.16.0.tar.gz (824kB)
    100% |████████████████████████████████| 829kB 410kB/s 
    Collecting docopt>=0.5 (from psd-tools==1.4->-r requirements.txt (line 38))
    Downloading docopt-0.6.2.tar.gz
    Collecting tinycss (from CairoSVG==2.0.1->-r requirements.txt (line 39))
    Downloading tinycss-0.4.tar.gz (87kB)
    100% |████████████████████████████████| 92kB 379kB/s 
    Collecting cairocffi (from CairoSVG==2.0.1->-r requirements.txt (line 39))
    Downloading cairocffi-0.8.0.tar.gz (79kB)
    100% |████████████████████████████████| 81kB 343kB/s 
    Complete output from command python setup.py egg_info:
    c/_cffi_backend.c:2:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    Traceback (most recent call last):
      File "/usr/lib/python3.5/distutils/unixccompiler.py", line 118, in _compile
        extra_postargs)
      File "/usr/lib/python3.5/distutils/ccompiler.py", line 909, in spawn
        spawn(cmd, dry_run=self.dry_run)
      File "/usr/lib/python3.5/distutils/spawn.py", line 36, in spawn
        _spawn_posix(cmd, search_path, dry_run=dry_run)
      File "/usr/lib/python3.5/distutils/spawn.py", line 159, in _spawn_posix
        % (cmd, exit_status))
    distutils.errors.DistutilsExecError: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/setuptools/command/bdist_egg.py", line 161, in run
        cmd = self.call_command('install_lib', warn_dir=0)
      File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/setuptools/command/bdist_egg.py", line 147, in call_command
        self.run_command(cmdname)
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/setuptools/command/install_lib.py", line 11, in run
        self.build()
      File "/usr/lib/python3.5/distutils/command/install_lib.py", line 109, in build
        self.run_command('build_ext')
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/setuptools/command/build_ext.py", line 75, in run
        _build_ext.run(self)
      File "/usr/lib/python3.5/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/usr/lib/python3.5/distutils/command/build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "/usr/lib/python3.5/distutils/command/build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
        _build_ext.build_extension(self, ext)
      File "/usr/lib/python3.5/distutils/command/build_ext.py", line 533, in build_extension
        depends=ext.depends)
      File "/usr/lib/python3.5/distutils/ccompiler.py", line 574, in compile
        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
      File "/usr/lib/python3.5/distutils/unixccompiler.py", line 120, in _compile
        raise CompileError(msg)
    distutils.errors.CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/setuptools/sandbox.py", line 157, in save_modules
        yield saved
      File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/setuptools/sandbox.py", line 198, in setup_context
        yield
      File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/setuptools/sandbox.py", line 255, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/setuptools/sandbox.py", line 285, in run
        return func()
      File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/setuptools/sandbox.py", line 253, in runner
        _execfile(setup_script, ns)
      File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/setuptools/sandbox.py", line 47, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-64ysl24e/cffi-1.10.0/setup.py", line 232, in <module>
      File "/usr/lib/python3.5/distutils/core.py", line 163, in setup
        raise SystemExit("error: " + str(msg))
    SystemExit: error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 1105, in run_setup
        run_setup(setup_script, args)
      File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/setuptools/sandbox.py", line 258, in run_setup
        raise
      File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/setuptools/sandbox.py", line 198, in setup_context
        yield
      File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/setuptools/sandbox.py", line 169, in save_modules
        saved_exc.resume()
      File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/setuptools/sandbox.py", line 144, in resume
        six.reraise(type, exc, self._tb)
      File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/setuptools/sandbox.py", line 157, in save_modules
        yield saved
      File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/setuptools/sandbox.py", line 198, in setup_context
        yield
      File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/setuptools/sandbox.py", line 255, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/setuptools/sandbox.py", line 285, in run
        return func()
      File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/setuptools/sandbox.py", line 253, in runner
        _execfile(setup_script, ns)
      File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/setuptools/sandbox.py", line 47, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-64ysl24e/cffi-1.10.0/setup.py", line 232, in <module>
      File "/usr/lib/python3.5/distutils/core.py", line 163, in setup
        raise SystemExit("error: " + str(msg))
    SystemExit: error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ai8kv871/cairocffi/setup.py", line 44, in <module>
        extras_require={'xcb': ['xcffib>=0.3.2']},
      File "/usr/lib/python3.5/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/setuptools/dist.py", line 318, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/setuptools/dist.py", line 375, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/pkg_resources/__init__.py", line 851, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1123, in best_match
        return self.obtain(req, installer)
      File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1135, in obtain
        return installer(requirement)
      File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/setuptools/dist.py", line 443, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 673, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 699, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 880, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 1119, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 1107, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by bameda** [comment]
Have you installed `libcairo2-dev`?
```
sudo apt-get install libcairo2-dev
```
And try again

**Comment by Arthanarisamy** [comment]
Its installed and already the latest.

    admin@lap132:~$ sudo apt-get install libcairo2-dev
    [sudo] password for admin: 
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    libcairo2-dev is already the newest version.
    libcairo2-dev set to manually installed.
    0 upgraded, 0 newly installed, 0 to remove and 10 not upgraded.

**Comment by mikaoelitiana** [comment]
I have same issue updating taiga to latest version today. 
```
Collecting asana==0.6.2 (from -r requirements.txt (line 43))
  Using cached asana-0.6.2.tar.gz
    Complete output from command python setup.py egg_info:
    error in asana setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
```
I tried skiping this part (as I don't use asana) and tried `python manage.py migrate --noinput`but got other errors 

```
Trying import local.py settings...
Traceback (most recent call last):
  File "/usr/lib/python3.4/logging/config.py", line 381, in resolve
    found = getattr(found, frag)
AttributeError: 'module' object has no attribute 'ServerFormatter'

During handling of the above exception, another exception occurred:
```

**Comment by mikaoelitiana** [comment]
Upgrading `pip` as suggested in #951 solved my first issue. I need to fix one remaining issue

**Comment by guapyo** [comment]
Hi, 
I have the same issue as @Arthanarisamy, upgrading pip doesn't solve it. It seems to be a problem in CairoSVG lib. Pip install CairoSVG fails too.
Is this lib mandatory or can we skip it ? Thanks

**Comment by bameda** [comment]
You can skip it, is only to generate thumbnails of svg files

**Comment by bameda** [comment]
Just one test, try to install `libffi-dev` and `python-dev`. Maybe this could resolve the problem.

**Comment by aricav96** [comment]
If anyone stumbles upon this (or anything similar regarding this step): I was having some problems which I solved by installing libssl-dev. I also had some problems (probably a timeout) when pip tried cloning the markdown repo. I changed the requirements file to read git+https rather than git+git. (Do consider that I was trying to do this from a fresh Debian VM; odds are that libssl-dev is already installed under other circumstances).
